### ISSUE TITLE
php-fpm 无法正常启动

### ISSUE THREAD

**Issue by DavenAaron** [SkyAPM/SkyAPM-php-sdk#101]
php-fpm: v7.2.7 zts

extension=skywalking.so
skywalking.enable=1
skywalking.version=6
skywalking.app_code=hello_skywalking
skywalking.sock_path=/tmp/sky_agent.sock

Jul 29 17:16:26 applicaton-proving systemd: Started The PHP FastCGI Process Manager.
Jul 29 17:16:26 applicaton-proving systemd: Starting The PHP FastCGI Process Manager...
Jul 29 17:16:26 applicaton-proving kernel: php-fpm[32446]: segfault at 0 ip 00007fe15f910cca sp 00007ffcba47f3d0 error 4 in skywalking.so[7fe15f90c000+9000]
Jul 29 17:16:26 applicaton-proving systemd: php-fpm.service: main process exited, code=killed, status=11/SEGV
Jul 29 17:16:26 applicaton-proving systemd: Unit php-fpm.service entered failed state.
Jul 29 17:16:26 applicaton-proving systemd: php-fpm.service failed.

**Comment by heyanlong** [comment]
系统环境发一下

**Comment by DavenAaron** [comment]
CentOS Linux release 7.4.1708 (Core)
PHP 7.2.7 (cli) (built: Jun 24 2018 21:59:08) ( ZTS )

**Comment by heyanlong** [comment]
为什么要用ZTS，Linux下NZTS更稳一点吧

**Comment by DavenAaron** [comment]
目前不支持zts是么？

**Comment by heyanlong** [comment]
没进行测试

**Comment by dshowing** [comment]
所以这个问题解决了吗？

**Comment by heyanlong** [comment]
@dshowing 没有进行有效测试
