### ISSUE TITLE
php可以跟踪具体应用代码么？

### ISSUE THREAD

**Issue by stonerczl** [SkyAPM/SkyAPM-php-sdk#112]
php系统追踪项里，可以跟踪到具体代码调用哪个方法？执行情况么？目前好像只可以看到比如数据库的
![image](https://user-images.githubusercontent.com/44865951/62671171-9c268780-b94a-11e9-8ae4-a3de038e8693.png)

**Comment by heyanlong** [comment]
比如和？

**Comment by bostin** [comment]
Skywalking是请求链路跟踪，强调的是应用于应用之间的调用关系的打通和连接。
调用方法的跟踪请使用 xhprof/tideways等

**Comment by stonerczl** [comment]
> Skywalking是请求链路跟踪，强调的是应用于应用之间的调用关系的打通和连接。
> 调用方法的跟踪请使用 xhprof/tideways等

好的，谢谢
