### ISSUE TITLE
编译安装插件后 php7.2 ubuntu环境 phpinfo 中没有插件的信息，怎么解决

### ISSUE THREAD

**Issue by txgwind** [SkyAPM/SkyAPM-php-sdk#113]
ubuntu 试了5.6，和7.2版本，然后编译安装插件，完成后，在phpinfo 中没有看到插件已安装，可能是什么问题，？php错误日志也没有任何相关错误，怎么排查问题？如何解决呢

**Comment by heyanlong** [comment]
操作过程发一下


发自我的 iPhone

**Comment by bostin** [comment]
请检查是否配置了skywalking.ini文件

**Comment by heyanlong** [comment]
@txgwind 有反馈吗？没有的话就关闭了
