### ISSUE TITLE
并发请求触发502的问题

### ISSUE THREAD

**Issue by geteng-zyp** [SkyAPM/SkyAPM-php-sdk#118]
开启skywalking扩展后，通过队列并发请求aaa.com/a.php（a.php里会请求bbb.com/b.php），前100次正常，从第101次开始nginx日志就都显示502了，php-fpm日志也记录到fpm子进程被频繁杀死，日志如下：
[25-Aug-2019 20:21:39] WARNING: [pool www] child 25539 exited on signal 11 (SIGSEGV) after 85.174560 seconds from start

**Comment by heyanlong** [comment]
fpm配置发一下

发自我的 iPhone

**Comment by geteng-zyp** [comment]
![image](https://user-images.githubusercontent.com/54018376/63660906-154b2900-c7eb-11e9-850d-369c617b8fdf.png)

大致圈定是a.php里curl请求b.php后，后续对请求结果的操作导致php-fpm挂掉的，对请求结果的后续
操作比较复杂，暂未定位到具体操作语句，但直接注释掉对请求结果的操作就不会出现这种情况，感觉是第100次后，请求b.php后返回的内容有问题。

**Comment by heyanlong** [comment]
两个文件部分代码发一下


发自我的 iPhone

**Comment by geteng-zyp** [comment]
我缩小了一下场景，总体过程如下
1.用一个php脚本将test.php压入队列，并发150次
$i=0;
while ($i<150) {
    add_message_to_queue(['url' => 'http://test1234_api.local.com/test.php?i='.$i]);
    $i++;
}

2.test.php用nategood/httpful来实现对test_skywalking.php的请求（单纯用curl实现请求不会触发，用nategood/httpful则会）
$url = 'http://test1234_api.local.com/test_skywalking.php?i='.$_GET['i'];
$response = \Httpful\Request::get($url)->send();
var_dump($response);die();

3.test_skywalking.php中只简单打印GET参数
var_dump($_GET);die();

**Comment by heyanlong** [comment]
Send coredump to me
