### ISSUE TITLE
Do you have plan to support guzzle.HttpPool

### ISSUE THREAD

**Issue by xiaoayu** [SkyAPM/SkyAPM-php-sdk#119]
The request class we used is guzzle HttpPool， Do you have plan to support guzzle.HttpPool。

**Comment by heyanlong** [comment]
@xiaoayu I am very sympathetic to your experience, but we don’t have this plan yet, but we will evaluate it and he will take a long time.

**Comment by xiaoayu** [comment]
> @xiaoayu I am very sympathetic to your experience, but we don’t have this plan yet, but we will evaluate it and he will take a long time.

thanks for your answer~
