### ISSUE TITLE
make failed, help

### ISSUE THREAD

**Issue by wzfjesun** [SkyAPM/SkyAPM-php-sdk#120]
php7.2
ubuntu18.04

I follow this step：
    git clone https://github.com/SkyAPM/SkyAPM-php-sdk.git && cd SkyAPM-php-sdk && \
    phpize && ./configure && make && make install
I got this error bellow:
```
/root/src/SkyAPM-php-sdk/skywalking.c:46:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
make: *** [skywalking.lo] Error 1
Makefile:193: recipe for target 'skywalking.lo' failed
```

**Comment by heyanlong** [comment]
Whether the curl extension is installed
