### ISSUE TITLE
php7-fpm  启动失败 Segmentation fault

### ISSUE THREAD

**Issue by shiyapeng** [SkyAPM/SkyAPM-php-sdk#124]
php 7.2.7
SkyAPM-php-sdk 3.1.7
sky_php_agent_linux_x64 3.1.7

php.ini 
[skywalking]
extension=skywalking.so
skywalking.enable=1
skywalking.version=6
skywalking.app_code=app-php7
skywalking.sock_path=/tmp/sky_agent.sock

php7 -m 显示已经加载了模块，但是php7-fpm启动时报段错误，请大神帮忙看下

**Comment by heyanlong** [comment]
retry last commit

**Comment by shiyapeng** [comment]
> retry last commit

请问哪个版本比较稳定

**Comment by shiyapeng** [comment]
> retry last commit
经过测试发现，把zts关掉就可以启动了，由于我们线上都是开启zts的，请问打算什么时候支持zts呢？

**Comment by heyanlong** [comment]
目前暂不支持zts
