### ISSUE TITLE
skywalking后台陆续出现承受不住压力卡死的情况

### ISSUE THREAD

**Issue by Martin-Gao** [SkyAPM/SkyAPM-php-sdk#125]
据服务端反馈skywalking后台陆续出现承受不住压力卡死的情况，日志量不大，但是请求次数太多，php项目没有接入之前一天收集的日志量是300多G，而现在时常卡死导致日志量反而减少了。初步评估还是因为上报过程是每个请求上报一次，过于频繁的请求导致。基于此想提出两点建议：
1、是否可以配置采样率，通过采样上报来减少请求量，而且还可以保证有问题的请求链不被遗漏
2、是否可以将上报处理逻辑修改为批量上报，据服务端反馈java的上报处理就是批量的，日志量很大，但是没有出现过问题

**Comment by kcloze** [comment]
也准备上生产环境，如果不是批量提交，希望尽快实现抽样率监测

**Comment by heyanlong** [comment]
retry 3.2.0

**Comment by Martin-Gao** [comment]
> 重试3.2.0

nice
