### ISSUE TITLE
执行redis::set(k, v, ttl)时返回失败的问题

### ISSUE THREAD

**Issue by DeeCen** [SkyAPM/SkyAPM-php-sdk#126]
centos 7   
PHP 7.0.13   
php redis扩展3.1.6

开启扩展后php代码执行原生redis::set(key_str, val_str, ttl_int)指令时会返回失败
因为不懂c  以下原因纯猜测

查看当前代码skywalking.c  (当前时间2019.09.17)
560行
zval *p = ZEND_CALL_ARG(execute_data, i);
565行
if (Z_TYPE_P(p) != IS_STRING) {
    convert_to_string(p);
}
指针p被改为字符串   是否因此导致redis::set参数3也会变为字符串从而导致失败?
目前尝试深copy指针p做后续处理问题消失

**Comment by heyanlong** [comment]
@bostin

**Comment by bostin** [comment]
@heyanlong @DeeCen 
#128 

![image](https://user-images.githubusercontent.com/17870778/65219695-a7dda000-daeb-11e9-8b09-8b6bc8d7298d.png)
![image](https://user-images.githubusercontent.com/17870778/65219709-b2983500-daeb-11e9-87bd-3a0f363ab8fe.png)
![image](https://user-images.githubusercontent.com/17870778/65219729-bd52ca00-daeb-11e9-96ae-099f6293097f.png)
