### ISSUE TITLE
可以更改下文档的php.ini的注释符吗？

### ISSUE THREAD

**Issue by jmjoy** [SkyAPM/SkyAPM-php-sdk#127]
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/zh/install-sdk.md
第5点
PHP.ini用;做注释而不是#
我就疑惑了为什么配置不生效，过了好一阵子才发觉。。

**Comment by bostin** [comment]
@jmjoy done

**Comment by jmjoy** [comment]
@bostin Thanks
