### ISSUE TITLE
sky_php_agent_linux_x64（3.1.7）运行报错

### ISSUE THREAD

**Issue by laster-bin** [SkyAPM/SkyAPM-php-sdk#130]
./sky_php_agent_linux_x64 -grpc=192.168.1.250:11800
hello skywalking
GRPC Host:  -grpc=192.168.1.250:11800
Sock Path:  /tmp/sky_agent.sock
listen: /tmp/sky_agent.sock

Service register protocol
register => Start register...
register error rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup -grpc=192.168.1.250: no such host"
register =>  <nil>
register => Start register error...
Close conn..

**Comment by laster-bin** [comment]
> telnet 192.168.1.250:11800
不能带参数-grpc

**Comment by laster-bin** [comment]
有没有支持php5.4以上的探针

**Comment by laster-bin** [comment]
> telnet 192.168.1.250:11800
有没有支持php5.4以上的探针

**Comment by heyanlong** [comment]
没有5.x支持

**Comment by FeiYuJun** [comment]
#环境：   
server： skywalking6.4 , ip : 192.168.146.147
agent: sky_php_agent3.1.7 php7.2.22  , ip : 192.168.146.148

#运行报错
[root@147 SkyAPM-php-sdk]# /usr/local/SkyAPM-php-sdk/sky_php_agent_linux_x64 192.168.146.147:11800 /tmp/sky_agent.sock
hello skywalking
GRPC Host:  192.168.146.147:11800
Sock Path:  /tmp/sky_agent.sock
listen: /tmp/sky_agent.sock
Service register protocol
register => Start register...
Close conn..
register error rpc error: code = DeadlineExceeded desc = context deadline exceeded
register =>  <nil>
register => Start register error...

#排查
agent检查端口通
[root@148 etc]# telnet 192.168.146.147 11800
Trying 192.168.146.147...
Connected to 192.168.146.147.
Escape character is '^]'.

server端，看已连接
[root@147 ~]# netstat -nat|grep 11800
tcp6       0      0 :::11800                :::*                    LISTEN     
tcp6       0      0 192.168.146.147:11800   192.168.146.148:52182   ESTABLISHED

**Comment by heyanlong** [comment]
请求超时，排查一下网络吧

**Comment by FeiYuJun** [comment]
我吧环境重搭了一次，sky_php_agnet 和skywalking都部署在一台机器上，还是有这个问题

**Comment by FeiYuJun** [comment]
[root@localhost bin]# netstat -nat|grep 11800
tcp        0      0 127.0.0.1:39828         127.0.0.1:11800         ESTABLISHED
tcp6       0      0 :::11800                :::*                    LISTEN     
tcp6       0      0 127.0.0.1:11800         127.0.0.1:39828         ESTABLISHED
[root@localhost bin]# lsof -i:39828
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java      18815 root  230u  IPv6 419926      0t0  TCP localhost:11800->localhost:39828 (ESTABLISHED)
sky_php_a 19066 root    5u  IPv4 418011      0t0  TCP localhost:39828->localhost:11800 (ESTABLISHED)

**Comment by FeiYuJun** [comment]
[root@localhost bin]# netstat -nat|grep 11800
tcp        0      0 127.0.0.1:39828         127.0.0.1:11800         ESTABLISHED
tcp6       0      0 :::11800                :::*                    LISTEN     
tcp6       0      0 **127.0.0.1:11800         127.0.0.1:39828         ESTABLISHED**
[root@localhost bin]# lsof -i:39828
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java      18815 root  230u  IPv6 419926      0t0  TCP localhost:11800->localhost:39828 (ESTABLISHED)
**sky_php_a** 19066 root    5u  IPv4 418011      0t0  TCP localhost:39828->localhost:11800 (ESTABLISHED)

**Comment by heyanlong** [comment]
你的PHP配置发一下，version配置的多少

**Comment by FeiYuJun** [comment]
php7.2.22

[root@localhost bin]# cat /usr/local/php72/etc/php-fpm.conf
[global]
;process.max = 
error_log = log/php-fpm.log
[www]
user = nobody
group = nobody
listen = 0.0.0.0:9000
;listen = /dev/shm/php-cgi.sock
listen.backlog = 8192
listen.owner = nobody
listen.group = nobody
listen.mode = 0660
pm = static
pm.max_children = 3
pm.status_path = /fpm-status
request_terminate_timeout = 10
rlimit_files = 65535
pm.max_requests = 1000
slowlog = var/log/$pool.log.slow
request_slowlog_timeout = 10s

**Comment by FeiYuJun** [comment]
[root@localhost bin]# cat /usr/local/php72/etc/php.ini 
[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = 17
disable_functions =
disable_classes =
zend.enable_gc = On
expose_php = On
max_execution_time = 30
max_input_time = 60
memory_limit = 128M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
track_errors = Off
html_errors = On
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 8M
auto_prepend_file =
auto_append_file =
default_mimetype = "text/html"
default_charset = "UTF-8"
doc_root =
user_dir =
enable_dl = Off
file_uploads = On
upload_max_filesize = 2M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60
[CLI Server]
cli_server.color = On
[Date]
[filter]
[iconv]
[intl]
[sqlite3]
[Pcre]
[Pdo]
[Pdo_mysql]
pdo_mysql.cache_size = 2000
pdo_mysql.default_socket=
[Phar]
[mail function]
SMTP = localhost
smtp_port = 25
mail.add_x_header = On
[SQL]
sql.safe_mode = Off
[ODBC]
odbc.allow_persistent = On
odbc.check_persistent = On
odbc.max_persistent = -1
odbc.max_links = -1
odbc.defaultlrl = 4096
odbc.defaultbinmode = 1
[Interbase]
ibase.allow_persistent = 1
ibase.max_persistent = -1
ibase.max_links = -1
ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
ibase.dateformat = "%Y-%m-%d"
ibase.timeformat = "%H:%M:%S"
[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.cache_size = 2000
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.default_host =
mysqli.default_user =
mysqli.default_pw =
mysqli.reconnect = Off
[mysqlnd]
mysqlnd.collect_statistics = On
mysqlnd.collect_memory_statistics = Off
[OCI8]
[PostgreSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0
[bcmath]
bcmath.scale = 0
[browscap]
[Session]
session.save_handler = files
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.hash_function = 0
session.hash_bits_per_character = 5
url_rewriter.tags = "a=href,area=href,frame=src,input=src,form=fakeentry"
[Assertion]
zend.assertions = -1
[COM]
[mbstring]
[gd]
[exif]
[Tidy]
tidy.clean_output = Off
[soap]
soap.wsdl_cache_enabled=1
soap.wsdl_cache_dir="/tmp"
soap.wsdl_cache_ttl=86400
soap.wsdl_cache_limit = 5
[sysvshm]
[ldap]
ldap.max_links = -1
[mcrypt]
[dba]
[opcache]
[curl]
[openssl]
**[skywalking]
skywalking.enable=1
skywalking.version=6
skywalking.app_code=hello
skywalking.sock_path=/tmp/sky_agent.sock
extension=/usr/local/php72/lib/php/extensions/no-debug-non-zts-20170718/skywalking.so**

**[root@localhost bin]# /usr/local/php72/bin/php -m|grep sky
skywalking**

**Comment by krahser** [comment]
Hi!
Any other idea about this? 
`register error rpc error: code = DeadlineExceeded desc = context deadline exceeded`
I'm having the same issue using skywalking server 6.2.0 and agent 3.2.0 on PHP 7.1.30.
Thanks in advance

**Comment by FeiYuJun** [comment]
抱歉，我也没找到问题，重新搭建解决的
