### ISSUE TITLE
重启sky_php_agent，界面的service消息，但endpoint能获取数据

### ISSUE THREAD

**Issue by laster-bin** [SkyAPM/SkyAPM-php-sdk#131]
![image](https://user-images.githubusercontent.com/31149409/65490300-7bf15e80-dedf-11e9-9259-13d742b7a63f.png)

**Comment by heyanlong** [comment]
日志

**Comment by laster-bin** [comment]
> 日志

要那个日志？

**Comment by heyanlong** [comment]
sky_php_agent日志

**Comment by laster-bin** [comment]
> sky_php_agent日志


[nohup.txt](https://github.com/SkyAPM/SkyAPM-php-sdk/files/3650211/nohup.txt)

**Comment by heyanlong** [comment]
根据日志来看，没有任何问题，扩大一下搜索范围试试

**Comment by laster-bin** [comment]
> 根据日志来看，没有任何问题，扩大一下搜索范围试试

具体操作？

**Comment by heyanlong** [comment]
在UI上查询两天前到现在的数据

**Comment by heyanlong** [comment]
只重启agent没重启php？
