### ISSUE TITLE
curl_setopt丢失用户自定义头部问题

### ISSUE THREAD

**Issue by DeeCen** [SkyAPM/SkyAPM-php-sdk#132]
`a.php
$ch = curl_init('127.0.0.1/b.php');
curl_setopt($ch, CURLOPT_HTTPHEADER, ['user-key: important-key', 'content-type: application/json']);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, 'post_data');
curl_exec($ch);

b.php
echo $_SERVER['HTTP_CONTENT_TYPE'] ?? 'null';
echo PHP_EOL;
echo $_SERVER['HTTP_USER_KEY'] ?? 'null';`

执行a.php不开启扩展结果:
application/json
important-key

执行a.php开启扩展结果
application/x-www-form-urlencoded
null

查看源码发现sky_curl_setopt_handler函数875行(当前时间2019.09.24),收集头部信息后,没有把头部发送至curl? 879行的else不应存在?

**Comment by heyanlong** [comment]
感谢，我排查一下

**Comment by heyanlong** [comment]
缺少http scheme
```php
$ch = curl_init('http://127.0.0.1/b.php');
```
