### ISSUE TITLE
dnmp docker   

### ISSUE THREAD

**Issue by ming200825** [SkyAPM/SkyAPM-php-sdk#133]
![image](https://user-images.githubusercontent.com/4900401/65828995-732fcc80-e2d3-11e9-87a6-10e76d198d9a.png)

没有日志 输出 
![image](https://user-images.githubusercontent.com/4900401/65828931-dc631000-e2d2-11e9-9d3e-baa43ae28360.png)

以下是配置
![image](https://user-images.githubusercontent.com/4900401/65828953-18967080-e2d3-11e9-8b1f-7421189c09f9.png)

![image](https://user-images.githubusercontent.com/4900401/65828955-277d2300-e2d3-11e9-8612-bda38f6325f4.png)

![image](https://user-images.githubusercontent.com/4900401/65828966-44195b00-e2d3-11e9-8b01-d68af0fe842b.png)

php7.2-dev  不知道 怎么装  在 alpine  没有源

**Comment by ming200825** [comment]
请问一下 可能是哪的问题吗.

**Comment by ming200825** [comment]
是控制台程序 才能监控吗

**Comment by ming200825** [comment]
这个是 dotnet 程序 已经部署上去了 所以 不是oap 这边的问题
![image](https://user-images.githubusercontent.com/4900401/65829055-e5a0ac80-e2d3-11e9-8e1d-f6e7781fb711.png)

**Comment by heyanlong** [comment]
ps aux | grep php 执行一下，看看

**Comment by ming200825** [comment]
> ps aux | grep php 执行一下，看看

![image](https://user-images.githubusercontent.com/4900401/65832298-4b049580-e2f4-11e9-9ae0-c67d3bad5b79.png)

**Comment by ming200825** [comment]
![image](https://user-images.githubusercontent.com/4900401/65832420-eea27580-e2f5-11e9-828a-246aa61013dd.png)

**Comment by heyanlong** [comment]
大概是 PHP没有sock写入权限。
