### ISSUE TITLE
错误的解析

### ISSUE THREAD

**Issue by dosgou** [SkyAPM/SkyAPM-php-sdk#135]
root@1f5f7cdbb4b5:/var/www/html# sky_php_agent skywalking_oap_server_hellocdj:11800
INFO[2019-10-08 21:53:36] hello skywalking                             
INFO[2019-10-08 21:53:36] connection 127.0.0.1:11800...                
INFO[2019-10-08 21:54:51] start register pid 8 used SkyWalking v6      
ERRO[2019-10-08 21:54:51] register error:rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11800: connect: connection refused" 
ERRO[2019-10-08 21:54:51] register error:<nil>  
链接的地址不对 grpc

docker-ccompose

**Comment by dosgou** [comment]
skywalking_oap_server_hellocdj 
root@1f5f7cdbb4b5:/var/www/html# ping skywalking_oap_server_hellocdj
PING skywalking_oap_server_hellocdj (172.18.0.9): 56 data bytes
64 bytes from 172.18.0.9: icmp_seq=0 ttl=64 time=0.167 ms
64 bytes from 172.18.0.9: icmp_seq=1 ttl=64 time=0.142 ms
64 bytes from 172.18.0.9: icmp_seq=2 ttl=64 time=0.084 ms

**Comment by heyanlong** [comment]
sky_php_agent --grpc skywalking_oap_server_hellocdj:11800

**Comment by dosgou** [comment]
请教一个问题，sky_php_agent能做成守护进程么或是后台运行 -d

**Comment by dosgou** [comment]
端点:Redis->get
跨度类型:Exit
组件:Jedis
Peer:No Peer
失败:false
redis.command: get uc_at_b_t_d0ac0bb586586e7856e5f1dd40e2124e6c7d85d44f72ef67c3ca81808e3c950e
db.type: redis
redis.key: UC_AT_B_T_d0ac0bb586586e7856e5f1dd40e2124e6c7d85d44f72ef67c3ca81808e3c950e

用的是redis扩展，在追踪信息显示的是jedis

在拓扑图没有显示redis服务，redis是另一台主机
