### ISSUE TITLE
redis 扩展问题

### ISSUE THREAD

**Issue by dosgou** [SkyAPM/SkyAPM-php-sdk#137]
端点:Redis->get
跨度类型:Exit
组件:Jedis
Peer:No Peer
失败:false
redis.command: get uc_at_b_t_d0ac0bb586586e7856e5f1dd40e2124e6c7d85d44f72ef67c3ca81808e3c950e
db.type: redis
redis.key: UC_AT_B_T_d0ac0bb586586e7856e5f1dd40e2124e6c7d85d44f72ef67c3ca81808e3c950e

用的是redis扩展，在追踪信息显示的是jedis

在拓扑图没有显示redis服务，redis是另一台主机

**Comment by heyanlong** [comment]
显示Jedis正常，为了兼容SkyWalking UI上的图标

**Comment by dosgou** [comment]
redis是另一台主机，在拓扑图上没有这个节点？
