### ISSUE TITLE
自定义sock文件生效了文件没生成

### ISSUE THREAD

**Issue by neighbour-oldhuang** [SkyAPM/SkyAPM-php-sdk#138]
![image](https://user-images.githubusercontent.com/23180415/66620499-418ffd00-ec13-11e9-8b9b-1be3015d50ac.png)
![image](https://user-images.githubusercontent.com/23180415/66620513-5a98ae00-ec13-11e9-8106-772e39fb32dd.png)

php版本:
PHP 7.3.6 (cli) (built: Jun 17 2019 21:27:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies

**Comment by heyanlong** [comment]
这个需要在agent也配置一个一样的

**Comment by neighbour-oldhuang** [comment]
> 这个需要在agent也配置一个一样的

原来是agent生成的....
