### ISSUE TITLE
php 7.3 运行agent 之后没有数据到服务端

### ISSUE THREAD

**Issue by wolfguoliang** [SkyAPM/SkyAPM-php-sdk#139]
系统centos 7 ，网络通端口通，和服务端已经建立链接了！
执行情况如下：
hello skywalking
GRPC Host:  10.111.10.145:11800
Sock Path:  /data/webroot/sky-agent.sock
listen: /data/webroot/sky-agent.sock

**Comment by heyanlong** [comment]
使用最新版本的agent试试，好像是3.2.0

**Comment by wolfguoliang** [comment]
感谢，我下载的是最新的agent，请问centos 都需要额外装哪些插件？除了 php-dev curl-dev，再次感谢。

**Comment by heyanlong** [comment]
不需要其他的了

**Comment by wolfguoliang** [comment]
好的，感谢，我再试试。

**Comment by wolfguoliang** [comment]
我安装make test 的时候报如下错误：
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
skywalking extension is available [tests/curl_001.phpt]
skywalking extension is available [tests/curl_002.phpt]
skywalking extension is available [tests/curl_003.phpt]
skywalking extension is available [tests/curl_004.phpt]
skywalking extension is available [tests/curl_005.phpt]
skywalking extension is available [tests/curl_006.phpt]
skywalking extension is available [tests/curl_007.phpt]
skywalking extension is available [tests/curl_009.phpt]
skywalking extension is available [tests/curl_010.phpt]
skywalking extension is available [tests/curl_011.phpt]
skywalking extension is available [tests/curl_012.phpt]
skywalking extension is available [tests/curl_013.phpt]
skywalking extension is available [tests/curl_016.phpt]
skywalking extension is available [tests/curl_017.phpt]
skywalking extension is available [tests/curl_018.phpt]
skywalking extension is available [tests/curl_019.phpt]
skywalking extension is available [tests/curl_020.phpt]
skywalking extension is available [tests/curl_021.phpt]
skywalking extension is available [tests/curl_023.phpt]
skywalking extension is available [tests/curl_024.phpt]
skywalking extension is available [tests/curl_025.phpt]

**Comment by heyanlong** [comment]
忽略即可

**Comment by wolfguoliang** [comment]
但是安装完成之后就是无法不往服务端注册传输数据，也没有报错。我有什么办法测试吗？感谢

**Comment by wolfguoliang** [comment]
客户端：3.1.7 运行状态如下：
INFO[2019-10-12 14:50:20] hello skywalking                             
INFO[2019-10-12 14:50:20] connection 10.111.10.145:11800...  

客户端：3.2 运行状态如下：
hello skywalking
GRPC Host: 10.111.10.145:11800
Sock Path: /data/webroot/sky-agent.sock
listen: /data/webroot/sky-agent.sock

**Comment by heyanlong** [comment]
agent 有日志输出吗

**Comment by wolfguoliang** [comment]
没有任何输出

**Comment by wolfguoliang** [comment]
我通tomcat 做测试，服务端可以接收数据。

**Comment by heyanlong** [comment]
那是PHP和agent通信失败了，看一下docs下的常见问题

**Comment by wolfguoliang** [comment]
好嘞，感谢

**Comment by wolfguoliang** [comment]
感谢，问题解决了，还是socket 地址配置的问题，建议作者把socket 配置默认就指定到：
/lib/systemd/system/sky-agent.sock 这样能少走弯路，再次感谢！

**Comment by heyanlong** [comment]
默认应该是/var/run吧
