### ISSUE TITLE
怎么查看 sky_php_agent_linux_x64 帮助

### ISSUE THREAD

**Issue by liaoqiArno** [SkyAPM/SkyAPM-php-sdk#140]
`wget https://github.com/SkyAPM/SkyAPM-php-sdk/releases/download/3.0.0/sky_php_agent_linux_x64
chmox +x sky_php_agent_linux_x64`
文档里说-h查看帮助
`[root@localhost ~]# ./sky_php_agent_linux_x64 --help
2019/10/12 11:53:37 hello
^C
[root@localhost ~]# ./sky_php_agent_linux_x64 -version`
、、怎么整！

**Comment by heyanlong** [comment]
下载3.2.0的把
