### ISSUE TITLE
HTTP_SW6

### ISSUE THREAD

**Issue by dosgou** [SkyAPM/SkyAPM-php-sdk#142]
在php $_SERVER中，没有发现这个HTTP_SW6，是3.2已经取消了么？我在skywalking.c中看到了是有这个字样“HTTP_SW6”。
以下是我本地的$_SERVER的打印数据：
[PHP_EXTRA_CONFIGURE_ARGS] => --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
    [HOSTNAME] => b70d92c228b7
    [PHP_INI_DIR] => /usr/local/etc/php
    [HOME] => /var/www
    [PHP_LDFLAGS] => -Wl,-O1 -Wl,--hash-style=both -pie
    [PHP_CFLAGS] => -fstack-protector-strong -fpic -fpie -O2
    [PHP_MD5] => 
    [PHP_VERSION] => 7.1.32
    [GPG_KEYS] => A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0 528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 1729F83938DA44E27BA0F4D3DBDB397470D12172
    [PHP_CPPFLAGS] => -fstack-protector-strong -fpic -fpie -O2
    [PHP_ASC_URL] => https://www.php.net/get/php-7.1.32.tar.xz.asc/from/this/mirror
    [PHP_URL] => https://www.php.net/get/php-7.1.32.tar.xz/from/this/mirror
    [TERM] => xterm
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [PHPIZE_DEPS] => autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c
    [PWD] => /var/www/html
    [PHP_SHA256] => 7f38b5bdaae3184d325a8c70e86c010afcc33651d15faafe277a0db6d2ea2741
    [TZ] => Asia/Shanghai
    [DB_PASSWORD] => 123
    [USER] => www-data
    [HTTP_ACCEPT_LANGUAGE] => zh-CN,zh;q=0.9
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_CACHE_CONTROL] => max-age=0
    [HTTP_CONNECTION] => keep-alive
    [HTTP_HOST] => 172.16.64.111
    [REDIRECT_STATUS] => 200
    [SERVER_NAME] => hellocdj.dosgou.com
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 172.18.0.6
    [REMOTE_PORT] => 50685
    [REMOTE_ADDR] => 172.16.64.199
    [SERVER_SOFTWARE] => nginx/1.15.8
    [GATEWAY_INTERFACE] => CGI/1.1
    [REQUEST_SCHEME] => http
    [SERVER_PROTOCOL] => HTTP/1.1
    [DOCUMENT_ROOT] => /www/hellocdj
    [DOCUMENT_URI] => /index.php
    [REQUEST_URI] => /
    [SCRIPT_NAME] => /index.php
    [CONTENT_LENGTH] => 
    [CONTENT_TYPE] => 
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [PATH_TRANSLATED] => /www/hellocdj
    [PATH_INFO] => 
    [SCRIPT_FILENAME] => /www/hellocdj/index.php
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1570978899.7365
    [REQUEST_TIME] => 1570978899

**Comment by heyanlong** [comment]
会出现在接收方的$_SERVER里面

**Comment by dosgou** [comment]
您好，您指的接收端是oap?还是curl请求的服务端？还请给详细的指导一下，谢谢！

**Comment by dosgou** [comment]
已经看到了，在curl的服务端
