### ISSUE TITLE
php linux 64 agent运行报错

### ISSUE THREAD

**Issue by dosgou** [SkyAPM/SkyAPM-php-sdk#144]
oap服务停止后，agent报错后停止运行。
      time" 2019-10-15 10:58:13 l evel=error msg=' heartbeat :rpc error: code = Unavailable desc = all SubConns are in TransientFailest connection error: connection error: desc F Y transport: Error while dialing dial tcp 172. 16. 64.111 :11800 connect: connemed out""

      time= " 2019-10-15 10:58:43 level=info msg= í start sending trace. count 4

      time=' I 2019-10-15 10:58:43 levelwarning msg=' rpc error: code F Unavailable desc F all SubConns are in TransientFailure, latection error: connection error: desc F Y transport: Error while dialing dial tcp 172. 16. 64.111 :11800 connect: connection tiW

      time= 2019-10-15 10:58:43 levelwarning msg= rpc error: code = Unavailable desc = all SubConns are in Transi entF ailure, latection error: connection error: desc F Y transport: Error while dialing dial tcp 172.16.64.111 :11800 connect: connection ti

      time= Í 2019-10-15 10:58:43 level=error msg= í no stream available

      time= 2019-10-15 10:58:43 level-warning msg= I stream not open, sending failtime" 2019-10-15 10:58:43 levelwarning msg= í stream not open, sending failtime 2019-10-15 10:58:43 level-warning msg=' stream not open, senđing failtime= I 2019-10-15 10:58:43 levelwarning msg=" stream not open, sending failpanic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x853708 I

      goroutine 10931 [running]: I

      agent/agent. /servi ce. (*Agent). send(0xc000156000, 0xc000392420, 0x4, 0x4)

      /Users/yanl ong/workspace/ SkyAPM- php -sdk -gol ang/src/ agent/service/ trace. go:120 +0x758created by agent/agent/service. (*Agent). sub 

      /Users/yanl ong/workspace/SkyAPM-php-sdk -gol ang/src/agent/service/agent go:142 +0x496

**Comment by heyanlong** [comment]
正常情况
