### ISSUE TITLE
SkyWalking PHP Agent启动后工作不正常

### ISSUE THREAD

**Issue by Cuigeek** [SkyAPM/SkyAPM-php-sdk#145]
#####sky-php-agent --grpc 192.168.8.7:11800 --socket /tmp/sky-agent.sock 启动后就一直卡在这里，Server端也没有收到数据
INFO[2019-10-18 16:42:31] hello skywalking                             
INFO[2019-10-18 16:42:31] connection 192.168.8.7:11800...  

ps：php skywalking扩展模块已安装，工作也正常

**Comment by heyanlong** [comment]
php是不是没权限读写这个sock

**Comment by Cuigeek** [comment]
不会的sock的权限是777
srwxrwxrwx 1  root  root  0 Oct 18 17:30 /tmp/sky-agent.sock

**Comment by heyanlong** [comment]
奇怪。。改一下sock目录试试

**Comment by Cuigeek** [comment]
修改sock路径后就无法正常创建sock了，php-fpm启动后skywalking模块加载正常。
/data/backup $ php -m|grep sky
skywalking
重新把sock修改到/tmp目录下依旧无法创建sock 这个应该怎么处理呢？

**Comment by heyanlong** [comment]
agent负责创建sock

**Comment by Cuigeek** [comment]
我这边PHP Agent工作正常了，感谢！！！！

**Comment by mahb2018** [comment]
@Cuigeek 你好，你这个问题怎么解决的 ，我现在也遇到和你相似的问题了，麻烦说一下解决方法，谢谢

**Comment by Cuigeek** [comment]
启动sky-php-agent
然后重启下php-fpm试试
