### ISSUE TITLE
php 调用使用socket 的方式是不是抓取不到数据

### ISSUE THREAD

**Issue by wolfguoliang** [SkyAPM/SkyAPM-php-sdk#146]

**Comment by heyanlong** [comment]
描述一下细节

**Comment by heyanlong** [comment]
发一下agent日志

**Comment by wolfguoliang** [comment]
我们现在只能抓到访问redis 和mysql 的数据，抓不到访问对应url的数据！

**Comment by arthron** [comment]
INFO[2019-10-19 10:27:18] hello skywalking                             
INFO[2019-10-19 10:27:18] connection 127.0.0.1:11800...                
INFO[2019-10-19 10:27:25] start register pid 1451 used SkyWalking v6   
INFO[2019-10-19 10:27:28] register pid 1451 appid 3 insId 3            
INFO[2019-10-19 10:27:30] register => pid 1451 appid 3 insId 3         
INFO[2019-10-19 10:27:30] register => pid 1451 appid 3 insId 3         
INFO[2019-10-19 10:27:31] register => pid 1451 appid 3 insId 3         
INFO[2019-10-19 10:27:31] start sending trace..., count 4              
INFO[2019-10-19 10:27:31] sending success...                           
INFO[2019-10-19 10:27:32] start sending trace..., count 2              
INFO[2019-10-19 10:27:32] sending success...                           
INFO[2019-10-19 10:27:33] start sending trace..., count 1              
INFO[2019-10-19 10:27:33] sending success...                           
INFO[2019-10-19 10:27:37] start sending trace..., count 1              
INFO[2019-10-19 10:27:37] sending success...                           
INFO[2019-10-19 10:27:41] register => pid 1451 appid 3 insId 3         
INFO[2019-10-19 10:27:45] start sending trace..., count 1              
INFO[2019-10-19 10:27:45] sending success...                           
INFO[2019-10-19 10:27:56] start sending trace..., count 1              
INFO[2019-10-19 10:27:56] sending success...                           
INFO[2019-10-19 10:27:57] start sending trace..., count 1              
INFO[2019-10-19 10:27:57] sending success...                           
INFO[2019-10-19 10:27:58] start sending trace..., count 6              
INFO[2019-10-19 10:27:58] heartbeat                                    
INFO[2019-10-19 10:27:58] sending success...                           
INFO[2019-10-19 10:27:58] heartbeat appId 3 appInsId 3                 
INFO[2019-10-19 10:27:59] start sending trace..., count 1              
INFO[2019-10-19 10:27:59] sending success...                           
INFO[2019-10-19 10:28:08] start sending trace..., count 1              
INFO[2019-10-19 10:28:08] sending success...                           
INFO[2019-10-19 10:28:09] start sending trace..., count 3              
INFO[2019-10-19 10:28:09] sending success...                           
INFO[2019-10-19 10:28:10] start sending trace..., count 5              
INFO[2019-10-19 10:28:10] sending success...                           
INFO[2019-10-19 10:28:15] start sending trace..., count 1              
INFO[2019-10-19 10:28:15] sending success...                           
INFO[2019-10-19 10:28:16] start sending trace..., count 2              
INFO[2019-10-19 10:28:16] sending success...                           
INFO[2019-10-19 10:28:38] heartbeat                                    
INFO[2019-10-19 10:28:38] heartbeat appId 3 appInsId 3

ui上服务为0，端点为4，数据库为1，ui上没有任何数据，ui和oap是docker安装的

**Comment by heyanlong** [comment]
UI厂查看最近7天是一下
