### ISSUE TITLE
单机模式PHP agent发送数据成功，web界面无数据

### ISSUE THREAD

**Issue by arthron** [SkyAPM/SkyAPM-php-sdk#147]
ui和oap使用6.4版本，使用默认的h2，配置仅修改了web端口，其他均未修改，agent使用3.2版本，未修改配置，安装了grpc扩展与protoc，请问还需要安装其他依赖吗？
### agent日志
root@ubuntu-xenial:/tmp# sky-php-agent 127.0.0.1:11800
INFO[2019-10-21 09:57:15] hello skywalking
INFO[2019-10-21 09:57:15] connection 127.0.0.1:11800...
INFO[2019-10-21 09:57:20] start sending trace..., count 1
INFO[2019-10-21 09:57:20] sending success...
INFO[2019-10-21 09:57:22] start sending trace..., count 3
INFO[2019-10-21 09:57:22] sending success...
INFO[2019-10-21 09:57:25] start sending trace..., count 1
INFO[2019-10-21 09:57:25] sending success...
INFO[2019-10-21 09:57:30] start sending trace..., count 1
INFO[2019-10-21 09:57:30] sending success...
INFO[2019-10-21 09:57:32] start sending trace..., count 1
INFO[2019-10-21 09:57:32] sending success...
INFO[2019-10-21 09:57:55] heartbeat
INFO[2019-10-21 09:57:55] heartbeat appId 2 appInsId 2
INFO[2019-10-21 09:58:35] heartbeat
INFO[2019-10-21 09:58:35] heartbeat appId 2 appInsId 2
INFO[2019-10-21 09:59:15] heartbeat
INFO[2019-10-21 09:59:15] heartbeat appId 2 appInsId 2
INFO[2019-10-21 09:59:55] heartbeat
INFO[2019-10-21 09:59:55] heartbeat appId 2 appInsId 2

ui界面
![image](https://user-images.githubusercontent.com/48424420/67171504-f7183880-f3e9-11e9-81b8-c965439bd11e.png)
![image](https://user-images.githubusercontent.com/48424420/67171519-08f9db80-f3ea-11e9-834d-d3023ecb9bc7.png)

**Comment by heyanlong** [comment]
可能时区不对，ui上查看最近7天试试

**Comment by arthron** [comment]
也是没有呢，ui上也没有服务
