### ISSUE TITLE
提供的sky-php-agent不能下载

### ISSUE THREAD

**Issue by xuqh123** [SkyAPM/SkyAPM-php-sdk#149]
wget https://github.com/SkyAPM/SkyAPM-php-sdk/releases/download/3.2.0/sky-php-agent-linux-x64

下载不了。
有别的地址么？

**Comment by xuqh123** [comment]
![image](https://user-images.githubusercontent.com/15340588/67210141-257a3000-f44b-11e9-83e2-d40d51285db8.png)

**Comment by xuqh123** [comment]
![image](https://user-images.githubusercontent.com/15340588/67254206-70795f00-f4ae-11e9-98ff-a35f7d57d448.png)

**Comment by xuqh123** [comment]
网络问题，github国内访问不稳定，今天试了下可以下载。

**Comment by heyanlong** [comment]
Going over the Great Wall and going to the world
