### ISSUE TITLE
接口502错误

### ISSUE THREAD

**Issue by DavenAaron** [SkyAPM/SkyAPM-php-sdk#150]
PHP Fatal error:  Can't use method return value in write context in xxxxxx on line 402

 388         //组装系统参数
 389         $sysParams["app_id"] = $this->appId;
 390         $sysParams["version"] = $iv;
 391         $sysParams["format"] = $this->format;
 392         $sysParams["sign_type"] = $this->signType;
 393         $sysParams["method"] = $request->getApiMethodName();
 394         $sysParams["timestamp"] = date("Y-m-d H:i:s");
 395         $sysParams["auth_token"] = $authToken;
 396         $sysParams["alipay_sdk"] = $this->alipaySdkVersion;
 397         $sysParams["terminal_type"] = $request->getTerminalType();
 398         $sysParams["terminal_info"] = $request->getTerminalInfo();
 399         $sysParams["prod_code"] = $request->getProdCode();
 400         $sysParams["charset"] = $this->postCharset;
 401         $sysParams["app_auth_token"] = $appInfoAuthtoken;
 402         if(!empty($request->getNotifyUrl())){
 403             $sysParams["notify_url"] = $request->getNotifyUrl();
 404         }
 405
 406
 407         //获取业务参数
 408         $apiParams = $request->getApiParas();
 409

**Comment by heyanlong** [comment]
这我也看不出来，提供点详细数据吧
