### ISSUE TITLE
agent端可以对实例进行命名吗？

### ISSUE THREAD

**Issue by arthron** [SkyAPM/SkyAPM-php-sdk#152]
一个项目部署了多台实例，service相同，如何对实例赋予不同的命名？

**Comment by heyanlong** [comment]
多实例建议用一个service_name

**Comment by arthron** [comment]
> 多实例建议用一个service_name

如何命名一个service_name下的不同实例？看文档没有给出实例名称的参数

**Comment by heyanlong** [comment]
php.ini

skywalking.app_code

**Comment by heyanlong** [comment]
agent只是透明代理，没有改名操作

**Comment by choldrim** [comment]
我也想问这个问题，一个k8s的服务起了多个实例，每个设置如果设置成相同的 app_code，那所有的instance看到都是相同的，区分不出来哪个instance是哪个，如下图：
![image](https://user-images.githubusercontent.com/6734555/75878924-5f296180-5e55-11ea-9b99-bda70bd4739a.png)

如果把所有的pod带上一个不一样的标识，如带上 pod 的 ip，那服务看到就变成是多个的了，有点尴尬
![image](https://user-images.githubusercontent.com/6734555/75879044-9d268580-5e55-11ea-8881-cde0318c33a0.png)

有没有可以设置instance的参数呢？如：
app_code 用来配置服务名
多加一个 instance_id 用来配置 instance 的名字？

不知道是否有这样的参数呢？

**Comment by heyanlong** [comment]
@choldrim 一个好的问题，这个在k8s中可以很好的解决，每一个pod中的PHP进程，都拥有独立的ip地址和端口号，这个可以很好的区分出来

**Comment by choldrim** [comment]
> @choldrim 一个好的问题，这个在k8s中可以很好的解决，每一个pod中的PHP进程，都拥有独立的ip地址和端口号，这个可以很好的区分出来

@heyanlong 

我测试了一下是我的server端的版本问题，重新部署了一个新的版本的server就能识别到instance的名字了，是用 `k8s-ldap-service-pid:47@tgit-dev-k8s-code-service-ldap-58fc944dxx-vrjxx` 类似这种方式命名的

另外，前几天看了下skywalking server那边，新的版本支持了uuid直接命名instance的名字，把UUID设置成  `NAME:Instance_name` ，后台会切割 `NAME:` 取后半部分作为instance的名字，这样子名字不会太长，还可以支持自定义，也挺好的一个功能：https://github.com/apache/skywalking/pull/4148


我看了下这边SDK的代码，现在的UUID是随机生成的，不支持参数配置，还不支持不了这个feature呢

**Comment by heyanlong** [comment]
我看一下这个pr
