### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by Cuigeek** [SkyAPM/SkyAPM-php-sdk#153]
INFO[2019-10-29 10:05:05] hello skywalking                             
INFO[2019-10-29 10:05:05] connection 192.168.8.7:11800...              
INFO[2019-10-29 10:05:08] start register pid 2634 used SkyWalking v6   
ERRO[2019-10-29 10:05:11] register error:rpc error: code = DeadlineExceeded desc = context deadline exceeded 
ERRO[2019-10-29 10:05:11] register error:<nil>                         
INFO[2019-10-29 10:05:11] start register pid 2634 used SkyWalking v6   
ERRO[2019-10-29 10:05:14] register error:rpc error: code = DeadlineExceeded desc = context deadline exceeded 
ERRO[2019-10-29 10:05:14] register error:<nil>                         
INFO[2019-10-29 10:05:14] start register pid 2634 used SkyWalking v6

**Comment by arthron** [comment]
看看防火墙

**Comment by Cuigeek** [comment]
SkyWalking Server端问题，已经解决，谢谢

**Comment by paff** [comment]
> SkyWalking Server端问题，已经解决，谢谢

我也遇到了同样的问题，请问您是如何解决的，谢谢？

**Comment by silverkorn** [comment]
On my end, the `/usr/share/elasticsearch/data/` from the ElasticSearch was mounted on an `Azure Files` for persistence but it seems to have an important impact on the files read/write operation speed. (See https://github.com/Azure/AKS/issues/223)

I plan to put backups instead on the external mount and keep the active database directly on the container/pod.
