### ISSUE TITLE
如何查看日志

### ISSUE THREAD

**Issue by caoxiaojian** [SkyAPM/SkyAPM-php-sdk#155]
[root@t1-php-01-172 src 10:00:59]# sky-php-agent --grpc 1.1.1.1:11800
INFO[2019-10-31 10:01:22] hello skywalking                             
INFO[2019-10-31 10:01:22] connection 1.1.1.1:11800... 
执行后server端没有收到消息，agent端只显示这些信息，网络是通的，server端没有问题，我想看下agent端的日志或者哪里能查看下日志下，排查下错误。
谢谢大神们

**Comment by heyanlong** [comment]
反复刷新页面agent会打印发送日志

**Comment by caoxiaojian** [comment]
我刷新访问我PHP的网站也没有任何的反应。没有一个想Java agent那样专门打印日志的目录吗，我看了-h   help，没有什么帮助

**Comment by heyanlong** [comment]
会输出到std

**Comment by caoxiaojian** [comment]
我现在在agent和server在一台机器
[root@jenkins SkyAPM-php-sdk 18:25:45]# php -v
PHP 7.3.11 (cli) (built: Oct 22 2019 08:11:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
[root@jenkins SkyAPM-php-sdk 18:24:04]# php -m | grep skywalking
skywalking
[root@jenkins SkyAPM-php-sdk 18:24:44]# cat /etc/php.d/skywalking.ini 
; 扩展so
extension=skywalking.so
; 是否启用：0 关闭；1 启用 (默认值为0)
skywalking.enable=1
; skywalking的版本：5或者6（默认值为6）
skywalking.version=6
; app_code代码，不要含特殊字符，请使用数字、字母、下换线。(默认为：hello_skywalking)
skywalking.app_code=cgt_test
; sock文件路径（默认值为/tmp/sky-agent.sock）
skywalking.sock_path=/tmp/sky-agent.sock


[root@jenkins SkyAPM-php-sdk 18:22:16]# sky-php-agent --grpc 127.0.0.1:11800
INFO[2019-10-31 18:22:21] hello skywalking                             
INFO[2019-10-31 18:22:21] connection 127.0.0.1:11800...                

server可以正常监控Java。我请求PHP页面，前台没有任何的输出。后端也没有接收到数据

**Comment by heyanlong** [comment]
telnet 127.0.0.1:11800 看看什么反应

**Comment by caoxiaojian** [comment]
root@jenkins ~ 20:03:45]# telnet 127.0.0.1 11800
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'

**Comment by caoxiaojian** [comment]
[root@jenkins ~ 20:12:32]# netstat -antlp|grep 11800
tcp        0      0 172.16.31.171:42433     172.16.31.171:11800     TIME_WAIT   -                   
tcp6       0      0 :::11800                :::*                    LISTEN      30526/java          
tcp6       0      0 172.16.31.171:11800     172.18.130.90:6339      ESTABLISHED 30526/java          

我现在agent和server在同一台机器。  server端Java监控正常

**Comment by heyanlong** [comment]
可能是sock权限问题

**Comment by heyanlong** [comment]
要不你试试3.2.1？刚发布的

**Comment by caoxiaojian** [comment]
我试了还是不行啊，同样的问题，您这边测试可以吗？

**Comment by caoxiaojian** [comment]
可以了。谢谢大神

**Comment by heyanlong** [comment]
怎么调试的

**Comment by liyantaotop** [comment]
> 可以了。谢谢大神

我遇到跟你一样的问题 。怎么解决的

**Comment by heyanlong** [comment]
1、socket权限
2、agent使用最新release

**Comment by caoxiaojian** [comment]
是的，我是更新了最新的release可以的
