### ISSUE TITLE
是否可以支持swoole?

### ISSUE THREAD

**Issue by marlonfan** [SkyAPM/SkyAPM-php-sdk#157]
**Is your feature request related to a problem? Please describe.**
因为主要技术栈偏向swoole这边 我看到源码中写如果是cli环境就跳过执行流程了

**Describe the solution you'd like**
不知道放开cli环境是否有什么隐患? 或者是否支持一个类似go agent的一个主动埋点的client?

**Comment by heyanlong** [comment]
1、暂不支持swoole，未来也没计划支持
2、目标是热插拔，无侵入监控，所以不提供主动埋点功能
