### ISSUE TITLE
Predis和Redis扩展Peer为空

### ISSUE THREAD

**Issue by zhangxuewei** [SkyAPM/SkyAPM-php-sdk#158]
Predis和Redis扩展能够正确上传Trace信息到服务段， 但是Peer信息均为空;有什么方式可以拿到Peer信息么？

**Comment by heyanlong** [comment]
Please provide more information

**Comment by zhangxuewei** [comment]
我用的是docker容器（network）， 一个主应用（包含agent），一个redis服务;
然后调用redis服务使用了Predis和PHPredis两种方式，这两种方式trace能够正常发送，不过peer信息都为空。对比了一下sdk源码 ，在skywalking.c文件308行，predis的peer赋值是空，不知道是不是这个原因。
