### ISSUE TITLE
能不能加入一个针对laravel的跟踪

### ISSUE THREAD

**Issue by niko-liu** [SkyAPM/SkyAPM-php-sdk#160]
如题

**Comment by heyanlong** [comment]
针对laravel哪一块呢？

**Comment by niko-liu** [comment]
> 针对laravel哪一块呢？

针对laravel http转发那一块，laravel这块有点像springboot，一个php容器启动了就不会停下来，用现在插件的做法抓不到它的网络请求

**Comment by niko-liu** [comment]
> 针对laravel哪一块呢？

还有个问题，现在的插件没有提交hostname到skywalking，导致在web服务上看到所有实例都是同一个instance名称，跟appcode一样，没办法区分

**Comment by heyanlong** [comment]
有上传本机IP
“一个php容器启动了就不会停下来” 这个不太理解

**Comment by heyanlong** [comment]
ping
