### ISSUE TITLE
怎么确定agent 是否连上oap server

### ISSUE THREAD

**Issue by liyantaotop** [SkyAPM/SkyAPM-php-sdk#162]
**启动agent时，只有两行输出,怎么判断已经连接server.**

我可以ping通oap所在机器

**Comment by liyantaotop** [comment]
![image](https://user-images.githubusercontent.com/20124333/70119287-e58ea580-16a4-11ea-8474-e0b9dd722298.png)

**Comment by liyantaotop** [comment]
![image](https://user-images.githubusercontent.com/20124333/70119358-1242bd00-16a5-11ea-8912-624ffd2b6374.png)

**Comment by heyanlong** [comment]
没有发生错误就是已经与aop建立链接

**Comment by liyantaotop** [comment]
已解决。多谢
