### ISSUE TITLE
通讯正常 显示不正常

### ISSUE THREAD

**Issue by liyantaotop** [SkyAPM/SkyAPM-php-sdk#163]
![image](https://user-images.githubusercontent.com/20124333/70198778-c8acad80-174a-11ea-9c9c-eff2e7495d08.png)

![image](https://user-images.githubusercontent.com/20124333/70198808-e0843180-174a-11ea-9a20-c693ff254ef4.png)

**Comment by liyantaotop** [comment]
服务起来的时候  显示是正常的。等了会  ui显示就不对了。缺少服务显示。但是数据库  端点都还在

**Comment by liyantaotop** [comment]
同时开启多个agent    skywalking.app_code 如果一样 会不会有问题

**Comment by liyantaotop** [comment]
ui 默认启动时 是有个SkyWalking的服务吧？昨天跑起来的时候看到的。今天都没了。我自己加的服务也没了

**Comment by heyanlong** [comment]
1、为什么要开多个agent？在一台机器上吗？
2、UI 只是客户端，和服务没关系

**Comment by liyantaotop** [comment]
1.我说的多个agent 是多机部署。经测试  发现没问题。app_code在ui上显示的是实例名
2.UI显示  是我的问题  勾选的时间不正确 导致数据没有展示
