### ISSUE TITLE
root用户操作sky-php-agent  删除了整个目录

### ISSUE THREAD

**Issue by xuqh123** [SkyAPM/SkyAPM-php-sdk#168]
**Describe the bug**
root用户操作sky-php-agent  删除了整个目录

**To Reproduce**

按文档中的方法操作执行。

> // download sky-php-agent
// e.g. 3.2.0
wget https://github.com/SkyAPM/SkyAPM-php-sdk/releases/download/3.2.0/sky-php-agent-linux-x64
mv sky-php-agent-linux-x64 sky-php-agent
chmod +x sky-php-agent
cp sky-php-agent /usr/bin

执行sky-php-agent --grpc 127.0.0.1 --socket=/tmp/test/
_注意这里--socket指定的是目录 没有填写sky-agent.sock文件_
执行结果会先如下
`PANI[2019-12-12 15:14:51] listen unix /tmp/test/: bind: no such file or directory 
ERRO[2019-12-12 15:14:51] &{0xc0000a2070 map[] 2019-12-12 15:14:51.742603362 +0800 CST m=+0.002871420 panic <nil> listen unix /tmp/test/: bind: no such file or directory <nil> <nil> } 
`
但是会把 /tmp目录下的/test目录下所有的目录文件（若有）全部删除。

**Expected behavior**
不要删除目录下所有的文件删除

**Screenshots**

**PHP (please complete the following information):**
 - OS: [Centos7]

**SkyWalking (please complete the following information):**
 - OS: [Centos7]
 - Version [6.4]

**Comment by heyanlong** [comment]
Thanks for feedback
