### ISSUE TITLE
How to configure a controler  cluster with mutiple addresses?

### ISSUE THREAD

**Issue by liheng0507** [SkyAPM/SkyAPM-php-sdk#169]
I'm tryed to configure three nodes ,but it's invalid.
    sky-php-agent --socket /var/run/sky-agent.sock --grpc 192.168.1.1:11800,192.168.1.2:11800,192.168.1.3:11800
then I choose one node of them,it's working.

WARN[2019-12-12 16:07:16] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address 192.168.1.1:11800,192.168.1.2:11800,192.168.1.3:11800: too many colons in address" 
WARN[2019-12-12 16:07:16] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address 192.168.1.1:11800,192.168.1.2:11800,192.168.1.3:11800: too many colons in address" 
ERRO[2019-12-12 16:07:16] no stream available

**Comment by liheng0507** [comment]
Then,how to define a namespace for the php instances,as the java instance namespace.

**Comment by heyanlong** [comment]
1. Thanks for your feedback, multi-address support will be supported in version 3.2.5, **which is expected to be completed this week**
2. Namespace can view `skywalking.app_name` configuration item

**Comment by liheng0507** [comment]
Thank you! Good work.
Look forward to the new release.

**Comment by heyanlong** [comment]
Reopen, close after publishing version 😄

**Comment by liheng0507** [comment]
Is the new release pushed？I‘ll reclose the question.Ha ha…

**Comment by liheng0507** [comment]
Is the new release pushed？I‘ll reclose the issue.Ha ha…

**Comment by heyanlong** [comment]
https://github.com/urfave/cli/issues/1003

**Comment by heyanlong** [comment]
[https://github.com/urfave/cli/issues/1003](https://github.com/urfave/cli/issues/1003)

**Comment by heyanlong** [comment]
reopen
