### ISSUE TITLE
sky-php-agent connection fail

### ISSUE THREAD

**Issue by roverliang** [SkyAPM/SkyAPM-php-sdk#170]
**chinese**
客户端的sky-php-agent 无法和服务端通信，一直卡在connection这里，java 的agent 正常。
```
INFO[2019-12-17 10:22:50] hello skywalking                             
INFO[2019-12-17 10:22:50] connection 127.0.0.1:11800...
```
php 的配置文件也是正常的。

**English**

The client's sky-php-agent is unable to communicate with the server and has been stuck at the connection. The java agent is normal.

```
INFO[2019-12-17 10:22:50] hello skywalking                             
INFO[2019-12-17 10:22:50] connection 127.0.0.1:11800...
```
The php configuration file is also normal.

**Comment by paff** [comment]
检查php.ini配置是否指定了sock path，默认是/var/run/sky-agent.sock，也可sky-php-agent -h查看

**Comment by zzjie871** [comment]
我也遇到了同样的情况，排查了那些参数，没有问题。

**Comment by meiliangdeng** [comment]
i had the same question，how to resolve it？

**Comment by meiliangdeng** [comment]
my os environment is the centos 7.2 ,the php7.2

**Comment by heyanlong** [comment]
Check if sock path is specified in the php.ini configuration or /var/run/sky-agent.sock, or you can view it in sky-php-agent -h
