### ISSUE TITLE
针对LNMP环境下，多个Nginx项目的code名称配置问题

### ISSUE THREAD

**Issue by zhangiwei** [SkyAPM/SkyAPM-php-sdk#171]
在部署SkyWalking的PHP扩展时，我们是在php.ini文件中添加skywalking.app_code=xxxx来指定该代码名称以便在UI界面展示做区分的。如果在现有的LNMP环境下，我的同一主机上的PHP项目有Pay、Shop、Listening等，针对这样的情况，我们该如何来进行配置以便在SkyWalking UI界面区别展示呢?

**Comment by heyanlong** [comment]
try
index.php
```
ini_set() ??
```

**Comment by jmjoy** [comment]
遇到相同的需求，但是看源码，`skywalking.app_code`在`PHP_RINIT_FUNCTION`的``时候被使用，后续`init_set`并没有作用。

**Comment by heyanlong** [comment]
那只能运行多个PHP来实现了

**Comment by jmjoy** [comment]
@heyanlong  建议在`php.ini`增加一个配置项将`sky_register`设置成可选地在`PHP_RINIT_FUNCTION`时调用，如果设置不自动调用，则提供一个php函数`sky_register`并接受`app_code`参数，让程序自行调用，可以达到相同php-fpm多个app_code的目的。但是改动量可以比较大，涉及到全局变量`application_instance`的逻辑需要修改。

**Comment by heyanlong** [comment]
@jmjoy 目标是无侵入监控，所以不提供register函数，另外PHP_RINIT_FUNCTION 注册可能会拖慢请求

**Comment by heyanlong** [comment]
@jmjoy 可以为Pay、Shop 各配置一个PHP运行端口
Pay 9000
Shop 9001
这样，每个端口然后加载各自的php.ini
