### ISSUE TITLE
SkyWalking PHP Agent 是否支持对RabbitMQ队列消费的链路追踪？

### ISSUE THREAD

**Issue by zhangiwei** [SkyAPM/SkyAPM-php-sdk#172]
在SkyWalking的Java Agent端的目录中有RabbitMQ相关的Plugins插件，Java程序在生产和消费队列时就会在SkyWalking UI上显示，而对于PHP 程序貌似还不支持？我们这边PHP程序在生产和消费队列在UI界面未显示

**Comment by heyanlong** [comment]
Does not support RabbitMQ

**Comment by zhangiwei** [comment]
Do you have any ideas or methods to resolve it?

**Comment by heyanlong** [comment]
What is the rabbitmq library you use?

**Comment by zhangiwei** [comment]
enqueue/amqp-lib

**Comment by heyanlong** [comment]
Supported
