### ISSUE TITLE
SkyWalking PHP Agent无法连接SkyWalking服务端

### ISSUE THREAD

**Issue by mahb2018** [SkyAPM/SkyAPM-php-sdk#175]
**Describe the bug**
when i start sky_php_agent ,only input hello, another server is ok（php7.1.18）

**To Reproduce**
sky_php_agent *.*.*.*:11800 /tmp/sky_agent.sock

**PHP (please complete the following information):**
 - OS: [Centos 7.7]
 - Version [e.g. 7.1.33]
 - PHP ini

**SkyWalking (please complete the following information):**
 - OS: [Centos 7.7.1908]
 - Version [6.5]

**Comment by heyanlong** [comment]
截个图

**Comment by mahb2018** [comment]
您好：
&nbsp; &nbsp; &nbsp; 环境说明：
&nbsp; &nbsp; &nbsp; php版本：v7.1.33
&nbsp; &nbsp; &nbsp; skywalking.ini&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp;


&nbsp; &nbsp; &nbsp;客户端启动：只显示hello
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;


&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"何延龙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月13日(星期一) 晚上7:43
收件人:&nbsp;"SkyAPM/SkyAPM-php-sdk"<SkyAPM-php-sdk@noreply.github.com&gt;;
抄送:&nbsp;"我爱美人"<313538639@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] SkyWalking PHP Agent无法连接SkyWalking服务端 (#175)




截个图

**Comment by heyanlong** [comment]
这点信息实在排查不出问题，可以参考 #145

**Comment by mahb2018** [comment]
您好:&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;那个帖子之前看过了，和我的还不一样 我socket目录都换过，没有作用。你这边需要什么信息 ，主要是我使用sky_php_agent -h&nbsp; 也只输出hello，根本没有其它输出。
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"何延龙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 上午10:43
收件人:&nbsp;"SkyAPM/SkyAPM-php-sdk"<SkyAPM-php-sdk@noreply.github.com&gt;;
抄送:&nbsp;"我爱美人"<313538639@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] SkyWalking PHP Agent无法连接SkyWalking服务端 (#175)




这点信息实在排查不出问题，可以参考 #145

**Comment by heyanlong** [comment]
你用的什么版本

**Comment by mahb2018** [comment]
skywalking的版本是6.5，另外一台php服务器（php版本：7.1.18）可以正常监控

**Comment by heyanlong** [comment]
怀疑socket路径的问题

**Comment by mahb2018** [comment]
socket我对比了一下可以正常监控的位置和有问题的都在/tmp下 权限也一样 ，有问题的socket我昨天换了一个目录，同样也不行

**Comment by heyanlong** [comment]
换到 /usr/run下

**Comment by zzjie871** [comment]
我也遇到同样的问题。
我是这样解决的：
1、admin 用户运行 php-fpm。
2、创建存放 sock 目录
mkdir -p /var/lib/sky-agent; chown -R admin:admin /var/lib/sky-agent
3、同样使用 admin 用户运行 sky-php-agent;
su - admin ;sky-php-agent --grpc 192.168.168.101:11800 --socket /var/lib/sky-agent/sky-agent.sock

我这里报了一个错，只有用 remi 源安装 php-fpm 时才出现这个报错，
# tail -f /var/opt/remi/php72/log/php-fpm/www-error.log
[04-Jan-2020 08:59:47 UTC] PHP Warning:  Unknown: [skywalking] failed to connect the sock. in Unknown on line 0
[04-Jan-2020 08:59:51 UTC] PHP Warning:  Unknown: [skywalking] failed to connect the sock. in Unknown on line 0
希望有用。

**Comment by mahb2018** [comment]
经过官方人员指导，问题已解决，更改了socket的目录（此目录需要有php启动用户的权限，最好是777）
