### ISSUE TITLE
While restart php-fpm after setup getting warning related to skywalking.so and json

### ISSUE THREAD

**Issue by ajay8310** [SkyAPM/SkyAPM-php-sdk#178]
After following all the steps in the documentation, when I restart php-fpm, I get following warning - 

<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/lib64/php/modules/skywalking.so (/usr/lib64/php/modules/skywalking.so: undefined symbol: php_json_encode), /usr/lib64/php/modules/skywalking.so.so (/usr/lib64/php/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in <b>Unknown</b> on line <b>0</b><br />

The agent does get heartbeat in console and as a result there is nothing in gui as well.

Please help.

**Comment by ajay8310** [comment]
When I do a ps aux, it is the screen 
![Screenshot from 2020-01-15 16-07-54](https://user-images.githubusercontent.com/28084402/72427502-dfb2d680-37b1-11ea-8b11-2867bd7142c7.png)

**Comment by ajay8310** [comment]
The following is the environment - 
PHP 7.2.26 (php-fpm)
nginx/1.16.1
centos 7

**Comment by ajay8310** [comment]
![Screenshot from 2020-01-15 16-42-54](https://user-images.githubusercontent.com/28084402/72429505-260a3480-37b6-11ea-8e07-6378f5a74d17.png)
sky-agent.sock has user permission as root. Please see the above screen shot.

**Comment by ajay8310** [comment]
Also, the php info shows that json is enabled. See the screen shot - 
![Screenshot from 2020-01-15 16-50-15](https://user-images.githubusercontent.com/28084402/72430029-4ab2dc00-37b7-11ea-8edc-c8c59e39c117.png)

**Comment by heyanlong** [comment]
What are the compilation parameters

**Comment by heyanlong** [comment]
#176

**Comment by heyanlong** [comment]
#145

**Comment by heyanlong** [comment]
Still having problems?
