### ISSUE TITLE
一台服务器器有多个php程序，agent的配置文件应该怎么写呢？

### ISSUE THREAD

**Issue by huohuanhuan** [SkyAPM/SkyAPM-php-sdk#189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heyanlong** [comment]
Does multiple PHP share PHP.ini

**Comment by huohuanhuan** [comment]
不好意思 描述错了。只有1个PHP，但是有多个项目，多个域名

**Comment by heyanlong** [comment]
One of the best suggestions. Provide a separate PHP process for each website
