### ISSUE TITLE
php执行超长(1min+)的请求，扩展没有记录到

### ISSUE THREAD

**Issue by ScorpiusJin** [SkyAPM/SkyAPM-php-sdk#190]
7s以下的请求记录正常，有几个性能较差的case，时间跑到了3分钟以上。

检查skywalking ui和es都没有记录上。

```
docker run --name apm-oap --restart always -d -e SW_STORAGE=elasticsearch \
-e SW_STORAGE_ES_CLUSTER_NODES=192.168.2.254:9200 apache/skywalking-oap-server:6.6.0-es6
```

```
docker run --name apm-ui --restart always -d -e SW_OAP_ADDRESS=127.0.0.1:12800 \
--net=host apache/skywalking-ui:6.6.0

```

php ext版本: 3.2.6

go sky-php-agent-linux-arm64版本: 3.2.5

**Comment by ScorpiusJin** [comment]
armv64的机器 
cpu: ft2000+  
os: uos20
php: 7.2.26

**Comment by heyanlong** [comment]
![image](https://user-images.githubusercontent.com/3367958/76928207-c8ac7400-691b-11ea-9b18-425f7f1a6846.png)
测试了一下，还可以啊

**Comment by ScorpiusJin** [comment]
> 测试了一下，还可以啊

跑了一段时间，大部分请求都可以分析到，极个别超长请求记录不到，原因不详。

skywalking是个好项目，加油。

**Comment by heyanlong** [comment]
我在加长一下时间
