### ISSUE TITLE
A way of reset

### ISSUE THREAD

**Issue by mikkeschiren** [SkyAPM/SkyAPM-php-sdk#191]
I can not find a way to reset service instance id, but maybe I am doing something wrong.

**Comment by heyanlong** [comment]
modify app_code

**Comment by wu-sheng** [comment]
> I can not find a way to reset service instance id, but maybe I am doing something wrong.

What do you mean reset? it looks like a strange requirement for me.

**Comment by mikkeschiren** [comment]
@wu-sheng - when testing the application I would find it useful to be able to reset it, but the simple solution to modify app_code does it for me, so I'm fine with that :-)

**Comment by wu-sheng** [comment]
Got it, have fun.
