### ISSUE TITLE
不能区分当前实例么？

### ISSUE THREAD

**Issue by huohuanhuan** [SkyAPM/SkyAPM-php-sdk#194]
通过skywalking的展示，发现当前实例与服务名称是一样的，这个不能自动区分吗？

**Comment by heyanlong** [comment]
嘿～晒出你的配置

**Comment by huohuanhuan** [comment]
; 扩展so
extension=skywalking.so
; 是否启用：0 关闭；1 启用 (默认值为0)
skywalking.enable=1
; skywalking的版本：5或者6（默认值为6）
skywalking.version=6
; app_code代码，不要含特殊字符，请使用数字、字母、下换线。(默认为：hello_skywalking)
skywalking.app_code=huohh
; sock文件路径（默认值为/var/run/sky-agent.sock）
skywalking.sock_path=/tmp/sky-agent.sock

**Comment by heyanlong** [comment]
如果服务都是houhh，而有多个实例，那么多个实例是使用ip+port进行区分

**Comment by huohuanhuan** [comment]
这个ip和端口在哪里配置？ 实际上在skywalking上并不显示的

**Comment by heyanlong** [comment]
ip 端口 自动发现，不用配置

**Comment by heyanlong** [comment]
![image](https://user-images.githubusercontent.com/3367958/76277043-869f8480-62c2-11ea-8918-481c81f1f11c.png)

**Comment by huohuanhuan** [comment]
大哥，你的是java的，java的确实可以，php的不行啊。
![QQ图片20200313120124](https://user-images.githubusercontent.com/38578400/76588630-6cfc7800-6522-11ea-95d8-6157fabaa51b.png)

**Comment by heyanlong** [comment]
版本都发一下，我本地做个测试

**Comment by huohuanhuan** [comment]
skywalking6.5。ES6.6, agent就是按照你的文档安装的

**Comment by heyanlong** [comment]
好

**Comment by huohuanhuan** [comment]
你的中文文档，和英文文档。我都试过了。都有这个问题。

**Comment by kilingzhang** [comment]
同上问题 😂

**Comment by huohuanhuan** [comment]
![image](https://user-images.githubusercontent.com/38578400/76928387-46707f80-691c-11ea-9277-fabb72d22ceb.png)

**Comment by huohuanhuan** [comment]
我尝试了，似乎并没有修复

**Comment by heyanlong** [comment]
重启PHP和sky-agent，sky-agent需要重新编译

**Comment by huohuanhuan** [comment]
可以了。感谢，对了，你的文档里面并没有告诉他们使用build-sky-php-agent.sh去编译agent，而你的源码包里也没有agent文件，所以会让人很迷惑。
