### ISSUE TITLE
在一台实例上部署agent，出现多个实例

### ISSUE THREAD

**Issue by huohuanhuan** [SkyAPM/SkyAPM-php-sdk#195]

**Comment by huohuanhuan** [comment]
![image](https://user-images.githubusercontent.com/38578400/76601742-857d8a00-6544-11ea-9079-5bae358d7982.png)

**Comment by huohuanhuan** [comment]
我只部署了一台实例

**Comment by heyanlong** [comment]
部署过程和配置参数发一下

**Comment by huohuanhuan** [comment]
部署过程就是按照你的中文文档来的，只不过编译的时候，我使用了你的build-sky-php-agent.sh编译的，后来我换成英文文档的编译方法，似乎是解决解决了这个问题。还有ES升级的时候，agent会负载突高

**Comment by heyanlong** [comment]
ES 升级和agent没有直接关系

**Comment by huohuanhuan** [comment]
ES升级的时候可能导致数据写入不进去。

**Comment by huohuanhuan** [comment]
你可以试试把服务端关掉，这个比较直观，负载就会上去
