### ISSUE TITLE
收集不到实例信息

### ISSUE THREAD

**Issue by huohuanhuan** [SkyAPM/SkyAPM-php-sdk#196]
![image](https://user-images.githubusercontent.com/38578400/76605546-95e53300-654b-11ea-8c26-4d550299b684.png)

**Comment by heyanlong** [comment]
agent有日志输出吗

**Comment by huohuanhuan** [comment]
agent只有常规日志输出

**Comment by heyanlong** [comment]
贴上来

**Comment by huohuanhuan** [comment]
time="2020-03-16 12:04:36" level=info msg="sending success..."
time="2020-03-16 12:04:36" level=info msg="start sending trace..., count 120"
time="2020-03-16 12:04:37" level=info msg="sending success..."
time="2020-03-16 12:04:37" level=info msg="start sending trace..., count 127"
time="2020-03-16 12:04:38" level=info msg="sending success..."
time="2020-03-16 12:04:38" level=info msg="start sending trace..., count 134"
time="2020-03-16 12:04:39" level=info msg="sending success..."
time="2020-03-16 12:04:39" level=info msg=heartbeat
time="2020-03-16 12:04:39" level=info msg="heartbeat appId 41 appInsId 531"
time="2020-03-16 12:04:39" level=info msg="start sending trace..., count 118"
time="2020-03-16 12:04:40" level=info msg="sending success..."
time="2020-03-16 12:04:40" level=info msg="start sending trace..., count 138"
time="2020-03-16 12:04:40" level=info msg="sending success..."


只有这种提交的日志。其他的都没有

**Comment by huohuanhuan** [comment]
time="2020-03-16 12:04:36" level=info msg="sending success..."
time="2020-03-16 12:04:36" level=info msg="start sending trace..., count 120"
time="2020-03-16 12:04:37" level=info msg="sending success..."
time="2020-03-16 12:04:37" level=info msg="start sending trace..., count 127"
time="2020-03-16 12:04:38" level=info msg="sending success..."
time="2020-03-16 12:04:38" level=info msg="start sending trace..., count 134"
time="2020-03-16 12:04:39" level=info msg="sending success..."
time="2020-03-16 12:04:39" level=info msg=heartbeat
time="2020-03-16 12:04:39" level=info msg="heartbeat appId 41 appInsId 531"
time="2020-03-16 12:04:39" level=info msg="start sending trace..., count 118"
time="2020-03-16 12:04:40" level=info msg="sending success..."
time="2020-03-16 12:04:40" level=info msg="start sending trace..., count 138"
time="2020-03-16 12:04:40" level=info msg="sending success..."

### **只有这种提交的日志。其他的都没有**###

**Comment by kilingzhang** [comment]
同上面问题
