### ISSUE TITLE
agent连接不上服务端，或者服务端异常的时候，部署agent的机器负载会暴增

### ISSUE THREAD

**Issue by huohuanhuan** [SkyAPM/SkyAPM-php-sdk#197]
skyalking6.5，es6.6，最新的php_agent
我是在请求量比较大的机器发现这个问题的。

**Comment by huohuanhuan** [comment]
正常的1分钟的负载是1-2  出现问题后1分钟的负载增加到10-25

**Comment by heyanlong** [comment]
把你的所有问题整理到一个issues吧

**Comment by huohuanhuan** [comment]
这样不好吧。。万一有同样的人遇到了这个问题，搜索的时候会很难受把。

**Comment by heyanlong** [comment]
可以提供一下每一个进程的信息吗？

**Comment by huohuanhuan** [comment]
可以详细点么。是agent进程的信息吗？你都要哪些信息，最好能告诉我一个工具，我用这个工具给你收集

**Comment by huohuanhuan** [comment]
如果你想看到这个问题，你就找一个流量高的机器，这个问题很容易复现！

**Comment by heyanlong** [comment]
agent 负载高，那个进程高，高的时候内存占了多少，cpu占了多少这样的信息

**Comment by heyanlong** [comment]
> 如果你想看到这个问题，你就找一个流量高的机器，这个问题很容易复现！

我没有高流量机器

**Comment by huohuanhuan** [comment]
![image](https://user-images.githubusercontent.com/38578400/76932172-41fc9480-6925-11ea-9d92-50aa706d1158.png)
![image](https://user-images.githubusercontent.com/38578400/76932190-4de85680-6925-11ea-828f-980e70a40169.png)
load 会突然增加到30多，我的服务器只有8核心，而且开启agent后，load似乎是慢慢会一直往上增长

**Comment by huohuanhuan** [comment]
![image](https://user-images.githubusercontent.com/38578400/76937353-9d338480-692f-11ea-9e55-2e4b791c60e3.png)
给你看一下监控数据吧，比较直观，这是我的一组服务器，是均衡负载的，黑色圈住的那条线就是装agent的机器

**Comment by huohuanhuan** [comment]
你点开大图看，不然看不到黑线

**Comment by huohuanhuan** [comment]
我现在线上根本没法用，负载太高了。

**Comment by heyanlong** [comment]
ping
