### ISSUE TITLE
agent自动退出

### ISSUE THREAD

**Issue by huohuanhuan** [SkyAPM/SkyAPM-php-sdk#198]
skyawkling6.5
error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x854ca8]

goroutine 7021792 [running]:
agent/agent/service.(*Agent).send(0xc00016a000, 0xc000bde000, 0x96, 0x100)
        /root/SkyAPM-php-sdk-3.2.6/agent/service/trace.go:121 +0x758
created by agent/agent/service.(*Agent).sub
        /root/SkyAPM-php-sdk-3.2.6/agent/service/agent.go:159 +0x48f

**Comment by huohuanhuan** [comment]
https://blog.csdn.net/qq_36431213/article/details/82967982

**Comment by heyanlong** [comment]
3.2.7 已修复
