### ISSUE TITLE
Unable to connect SkyWalking Agent to a php application for monitoring.

### ISSUE THREAD

**Issue by Debanjan05** [SkyAPM/SkyAPM-php-sdk#201]
Unable to connect SkyWalking Agent to a php application for monitoring.

I’m trying to install PHP Agent with SkyWalking collector and also using a sample PHP CRUD application with MySQL, which I want to monitor. 
I have installed them in a Ubuntu system using the steps given in 
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/install-agent.md

When I’m executing the command to start the agent --
$ sky-php-agent --grpc 127.0.0.1:11800 
from my php application after configuring the php.ini file with the given configuration for skywalking, its not getting connected to the agent and hence I’m not able to monitor the application in SkyWalking UI, however there are no errors in the log. I have earlier installed Java and Node JS agent for SkyWalking, it worked fine. But I don’t seem to find a solution to install php agent. Please help.

Screenshots of the log file of oap-server and when trying to start sky-php-agent but there is no progress.

![image](https://user-images.githubusercontent.com/32065582/77116854-e3cfce80-6a56-11ea-8bed-67ed327609d7.png)
![image](https://user-images.githubusercontent.com/32065582/77116872-eaf6dc80-6a56-11ea-8095-5edbaf012c06.png)
![image](https://user-images.githubusercontent.com/32065582/77116880-ee8a6380-6a56-11ea-85ef-f3c0d0e74a77.png)

 - OS: Ubuntu
 - Browser Chrome
 - PHP Version - 7.2

**Comment by heyanlong** [comment]
Please try 3.2.8

**Comment by Forestsoft-de** [comment]
Hey @Debanjan05 check your skywalking.sock_path in php.ini. by default its located in /tmp/

**Comment by heyanlong** [comment]
😎in slack
