### ISSUE TITLE
skywalking 7.0 新特性

### ISSUE THREAD

**Issue by kilingzhang** [SkyAPM/SkyAPM-php-sdk#209]
请问一下 agent 未来是否会支持skywalking 7.0的新特性  如果支持大概在什么时间能发版呢？

**Comment by heyanlong** [comment]
已支持7.0，你说的新特性具体指什么？

**Comment by wu-sheng** [comment]
He is asking for the new profile, implemented in Java. https://www.infoq.cn/article/CWUOl1JA0EyXw0CxQ4Zm

**Comment by kilingzhang** [comment]
是的是的 这部分会做支持吗
