### ISSUE TITLE
PHP-SDK报错提示：error:rpc error: code = DeadlineExceeded desc = context deadline exceeded 

### ISSUE THREAD

**Issue by binghun0518** [SkyAPM/SkyAPM-php-sdk#214]
PHP-SDK报错提示：
INFO[2020-04-10 09:36:54] connection 10.16.166.79:11800...            
INFO[2020-04-10 09:36:56] start register pid 985524 used SkyWalking v6 
ERRO[2020-04-10 09:36:59] register error:rpc error: code = DeadlineExceeded desc = context deadline exceeded 
ERRO[2020-04-10 09:36:59] register error:<nil>

**Comment by heyanlong** [comment]
OAP服务器超载了吧

**Comment by heyanlong** [comment]
ping

**Comment by zhegexiaohuozi** [comment]
或者尝试调大客户端设置的默认超时时间，这里默认的是3S可以根据自己的情况适当调大一下。涉及以下几个文件，以OAPServer V7版本为例：
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/5b17d3fa95ee0036d38cef6331cefd019e2c9ec3/reporter/service/trace.go#L84

https://github.com/SkyAPM/SkyAPM-php-sdk/blob/5b17d3fa95ee0036d38cef6331cefd019e2c9ec3/reporter/service/register.go#L130

https://github.com/SkyAPM/SkyAPM-php-sdk/blob/5b17d3fa95ee0036d38cef6331cefd019e2c9ec3/reporter/service/heartbeat.go#L40
