### ISSUE TITLE
获取日志失败

### ISSUE THREAD

**Issue by kechujian** [SkyAPM/SkyAPM-php-sdk#224]
开启agent后，获取php日志，显示
 ./sky-php-agent --grpc  127.0.0.1:11800 --socket /var/run/sky-agent.sock 
INFO[2020-05-07 17:39:18] hello skywalking                             
INFO[2020-05-07 17:39:18] connection 127.0.0.1:11800...            
INFO[2020-05-07 17:39:21] start register pid 10342 used SkyWalking v6  
ERRO[2020-05-07 17:39:21] register error:rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed 
ERRO[2020-05-07 17:39:21] register error:<nil>   
这是哪里配置不对吗？

**Comment by heyanlong** [comment]
什么版本，各项配置是什么？

**Comment by heyanlong** [comment]
ping
