### ISSUE TITLE
php加载插件报错，麻烦协助看看，非常感谢！

### ISSUE THREAD

**Issue by xieazu** [SkyAPM/SkyAPM-php-sdk#225]
提示/usr/lib64/php/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
报错截图如下：
![image](https://user-images.githubusercontent.com/65211579/81640219-8b162400-9450-11ea-8eeb-b249e372b0fb.png)

环境信息：centos7.3 php7.2.27 根据以下官方教程加载：
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/zh/install-sdk.md

php.ini配置如下：
![image](https://user-images.githubusercontent.com/65211579/81640505-4939ad80-9451-11ea-8e13-6bbd41871aae.png)
非常感谢！

**Comment by heyanlong** [comment]
PHP有json扩展吗？

**Comment by xieazu** [comment]
> PHP有json扩展吗？

感谢，安装了json扩展的
![image](https://user-images.githubusercontent.com/65211579/81643975-670b1080-9459-11ea-89ff-76344a236d36.png)

**Comment by heyanlong** [comment]
skywalking.so的路径在哪？

**Comment by xieazu** [comment]
非常感谢，我已经解决了该问题，可能和加载顺序有关，删除php.d下的json.ini，在php.ini中手动添加加载json即可：
![image](https://user-images.githubusercontent.com/65211579/81645109-8dca4680-945b-11ea-976a-cb6ca2bda5d6.png)
