### ISSUE TITLE
sky-php-agent启动后，用户登录页面的验证码图片无法显示，图片URL的返回码为502 Bad Gateway。

### ISSUE THREAD

**Issue by xujia3111** [SkyAPM/SkyAPM-php-sdk#226]
sky-php-agent版本3.2.8
启动命令：
sky-php-agent --grpc 127.0.0.1:11800  --socket=/var/run/sky-agent.sock --sky-version=6
php扩展skywalking已加载。
sky-php-agent的log看起来时正常的：
INFO[2020-05-12 17:05:47] connection 127.0.0.1:11800...                
INFO[2020-05-12 17:05:47] 🍺 skywalking php agent started successfully, enjoy yourself 
INFO[2020-05-12 17:05:49] start register pid 95090 used SkyWalking v6  
INFO[2020-05-12 17:05:50] register pid 95090 appid 2 insId 47          
INFO[2020-05-12 17:05:51] register cache => pid 95090, service hello_skywalking, appId 2 insId 47 
INFO[2020-05-12 17:05:51] start sending trace..., count 1              
INFO[2020-05-12 17:05:51] ✅ sending success     
把sky-php-agent关停后，登录页面可以正常显示验证码。
请问下，这是什么情况？
能否在sky-php-agent中添加可选的详细调试信息，以便排查问题。

**Comment by heyanlong** [comment]
只有验证码？这可能需要提供一下代码片段了

**Comment by xujia3111** [comment]
查看/usr/local/php/var/log/php-fpm.log，看到是php-fpm进程崩溃退出了，导致502。
[15-May-2020 16:31:45] WARNING: [pool 7000] child 106245 exited on signal 11 (SIGSEGV) after 60.480132 seconds from start
[15-May-2020 16:31:45] NOTICE: [pool 7000] child 106669 started
[15-May-2020 16:31:45] WARNING: [pool 7000] child 106669 exited on signal 11 (SIGSEGV) after 0.180825 seconds from start
[15-May-2020 16:31:45] NOTICE: [pool 7000] child 106672 started
[15-May-2020 16:31:45] WARNING: [pool 7000] child 106672 exited on signal 11 (SIGSEGV) after 0.178812 seconds from start

**Comment by xujia3111** [comment]
查看/var/log/messages:
May 15 18:09:09 localhost kernel: php-fpm[17667]: segfault at 0 ip 00007f39ed156b40 sp 00007ffebb5c1f50 error 4 in skywalking.so[7f39ed154000+b000]

**Comment by heyanlong** [comment]
验证码内部逻辑方便说一下吗？

**Comment by heyanlong** [comment]
或者提供一个coredump

**Comment by xujia3111** [comment]
内部逻辑我也不懂。按网上设置
echo '/tmp/core-%e.%p' > /proc/sys/kernel/core_pattern
echo 0 > /proc/sys/kernel/core_uses_pid
ulimit -c unlimited
重启php-fpm
但没有在/tmp生成coredump。
通过objdump 反汇编得到以下信息：
00007f39ed156b40 - 7f39ed154000 = 2b40
objdump -d /usr/lib64/php/modules/skywalking.so >dumpcode
0000000000002b20 <get_spans>:
    2b20:       48 83 ec 08             sub    $0x8,%rsp
    2b24:       48 8b 05 75 84 20 00    mov    0x208475(%rip),%rax        # 20afa0 <_DYNAMIC+0x218>
    2b2b:       48 8d 35 8e 65 00 00    lea    0x658e(%rip),%rsi        # 90c0 <_fini+0x24>
    2b32:       ba 07 00 00 00          mov    $0x7,%edx
    2b37:       48 8b 78 18             mov    0x18(%rax),%rdi
    2b3b:       e8 d0 fc ff ff          callq  2810 <zend_hash_str_find@plt>
    **2b40:       48 8b 38                mov    (%rax),%rdi**
    2b43:       48 8d 35 7e 65 00 00    lea    0x657e(%rip),%rsi        # 90c8 <_fini+0x2c>
    2b4a:       ba 05 00 00 00          mov    $0x5,%edx
    2b4f:       48 83 c4 08             add    $0x8,%rsp
    2b53:       e9 b8 fc ff ff          jmpq   2810 <zend_hash_str_find@plt>
    2b58:       0f 1f 84 00 00 00 00    nopl   0x0(%rax,%rax,1)
    2b5f:       00
请问下，还有什么方法排查吗？

**Comment by heyanlong** [comment]
不需要反汇编，要不你提供一个能502的小demo把

**Comment by heyanlong** [comment]
ping
