### ISSUE TITLE
客户端日志提示register error:<nil>，麻烦帮忙看看，非常感谢！

### ISSUE THREAD

**Issue by xieazu** [SkyAPM/SkyAPM-php-sdk#228]
报错截图如下：
![image](https://user-images.githubusercontent.com/65211579/81768453-ab57e880-950d-11ea-8c4a-9b32b0447f15.png)
已测试服务器端正常监听端口和iptables已放通：
![image](https://user-images.githubusercontent.com/65211579/81768544-db06f080-950d-11ea-8242-903ea1279677.png)
客户端telnet服务器11800端口正常：
![image](https://user-images.githubusercontent.com/65211579/81768627-0d185280-950e-11ea-9eeb-6e26394449d9.png)

**Comment by heyanlong** [comment]
启动参数是什么？各个版本是什么

**Comment by xieazu** [comment]
非常感谢，服务端版本是skywalking 7，agent版本是SkyAPM-php-sdk-3.2.8
启动参数如下，如果添加文档中--sky-version=7参数，执行会报错。
![image](https://user-images.githubusercontent.com/65211579/81772928-b1ec5d00-9519-11ea-956d-8046b92948af.png)

**Comment by heyanlong** [comment]
你这个是从master下载的？

**Comment by heyanlong** [comment]
php.ini 配置的什么

**Comment by xieazu** [comment]
根据以下文档下载，编译执行了shell脚本生成agent，以下文档的路径与实际不符。
![image](https://user-images.githubusercontent.com/65211579/81773519-ff1cfe80-951a-11ea-9d71-3ee68f24265c.png)

skywalking 7则是根据英文文档部署。

php.ini的配置如下：
; 扩展so
extension=json.so
; Loading extensions in PHP
extension=skywalking.so
; enable skywalking
skywalking.enable = 1
; Set skyWalking collector version (5 or 6 or 7 or 8)
skywalking.version = 7
; Set app code e.g. MyProjectName
skywalking.app_code = nono
; sock file path（default /tmp/sky-agent.sock）
skywalking.sock_path=/tmp/sky-agent.sock

**Comment by heyanlong** [comment]
skywalking.version = 7 改成 skywalking.version = 6
你用的文档是给今天要发的3.3.0准备的

**Comment by xieazu** [comment]
我改了重启问题依旧哦，3.3.0适用于skywalking7吗？我试一下该版本，是否将文档中的skywalking.version = 8改为skywalking.version = 7即可？

**Comment by heyanlong** [comment]
是的

**Comment by heyanlong** [comment]
ping

**Comment by sikelangya** [comment]
3.3.0的我也遇到了问题，

**Comment by sikelangya** [comment]
![image](https://user-images.githubusercontent.com/31874857/82007834-d2ddbb00-969d-11ea-96ea-1d2439b09782.png)
又这个报错ti'shi提示 但是  agent已经启动成功了
![image](https://user-images.githubusercontent.com/31874857/82007870-e426c780-969d-11ea-87b6-210f826f2f25.png)
