### ISSUE TITLE
Config done but nothing send to Skywalking

### ISSUE THREAD

**Issue by RyoSanka** [SkyAPM/SkyAPM-php-sdk#229]
I config PHP Agent Done and this is status Agent:

May 14 16:20:39 guess.com systemd[1]: Started The SkyWalking PHP-Agent Process Manager.
May 14 16:20:39 guess.com sky-php-agent[65036]: time="2020-05-14 16:20:39" level=info msg="hello skywalking"
May 14 16:20:39 guess.com sky-php-agent[65036]: time="2020-05-14 16:20:39" level=info msg="connection 192.168.1.50:11800..."
May 14 16:20:39 guess.com sky-php-agent[65036]: time="2020-05-14 16:20:39" level=info msg="🍺 skywalking php agent started successfully, enjoy yourself"

I check Log SkyWalking Web and Collector but no error.
And in my UI, no data sended.

Pleass help me. Thank you.

**Comment by sikelangya** [comment]
我也是安装了php的agent，   用的官方的3.3版本  pip7.0 ，但是php-v时一直提示：PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/skywalking.so' - /usr/lib64/php/modules/skywalking.so: undefined symbol: php_json_encode in Unknown on line 0     我在php.ini中已经按照官方提供的配置写好了   还是报错skywalking.so的问题

**Comment by heyanlong** [comment]
@sikelangya 需要json扩展才能运行
@RyoSanka Please check if PHP has read and write permissions for socks

**Comment by sikelangya** [comment]
![image](https://user-images.githubusercontent.com/31874857/82012512-be53ef80-96aa-11ea-8cd5-9bdb6e0631b0.png)
已经安装了的

**Comment by sikelangya** [comment]
![image](https://user-images.githubusercontent.com/31874857/82012572-f0fde800-96aa-11ea-8070-cfa994aabcb1.png)
配置都是按照这个来的，我的sw时7的版本  所以 里面的dui对应的版本也改成了7

**Comment by heyanlong** [comment]
所以，你改成01-json.ini 或者把里面内容放到php.ini ? 这一堆文件，很可能先加载skywalking.so 后加载json.so

**Comment by sikelangya** [comment]
这个我也已经操作了，改了php.d下面json.ini的名字 然后将引入json.so的加到了php.ini中然后重启了php-fpm  还是现在一样的样子

**Comment by RyoSanka** [comment]
![Untitled](https://user-images.githubusercontent.com/65341565/82025704-e435c000-96bb-11ea-8eb2-279282c9a8c0.png)
Yes, but nothing change.

**Comment by RyoSanka** [comment]
Oh, when i use: vi /var/run/sky-agent.sock, it's: Permission Denied.
But i use Chmod 777 and Chown to Apache... Am i do something wrong ?

**Comment by RyoSanka** [comment]
NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/lib64/php/modules/skywalking.so (/usr/lib64/php/modules/skywalking.so: undefined symbol: php_json_encode), /usr/lib64/php/modules/skywalking.so.so (/usr/lib64/php/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

New thing...

**Comment by RyoSanka** [comment]
Fixed, i remove module json.ini in my /etc/php.d/ and config /etc/php.ini add extension: extension=json.so and it's run ok.
But nothing send, fixing XD

**Comment by RyoSanka** [comment]
sky-php-agent.service - The SkyWalking PHP-Agent Process Manager
   Loaded: loaded (/usr/lib/systemd/system/sky-php-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-05-15 17:43:14 +07; 8min ago
  Process: 1805 ExecStop=/bin/kill -SIGINT $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 1807 (sky-php-agent)
   CGroup: /system.slice/sky-php-agent.service
           └─1807 /usr/local/bin/sky-php-agent --grpc=192.168.1.50:11800 --sky-version=7 --socket=/var/run/sky-agent.sock

May 15 17:43:14 guess.com systemd[1]: Stopped The SkyWalking PHP-Agent Process Manager.
May 15 17:43:14 guess.com systemd[1]: Started The SkyWalking PHP-Agent Process Manager.
May 15 17:43:14 guess.com sky-php-agent[1807]: time="2020-05-15 17:43:14" level=info msg="hello skywalking"
May 15 17:43:14 guess.com sky-php-agent[1807]: time="2020-05-15 17:43:14" level=info msg="connection 192.168.1.50:11800..."
May 15 17:43:14 guess.com sky-php-agent[1807]: time="2020-05-15 17:43:14" level=info msg="🍺 skywalking php agent started successfully, enjoy yourself"

Updated more Information.

**Comment by RyoSanka** [comment]
When i run command:
cat /var/run/sky-agent.sock 
cat: /var/run/sky-agent.sock: No such device or address

Hope have more information for you to help me.

**Comment by heyanlong** [comment]
@sikelangya 你的问题新开一个issue

**Comment by heyanlong** [comment]
@RyoSanka retry config socks to /tmp/sky-agent.sock

**Comment by RyoSanka** [comment]
I try but nothing change.
New thing, I chown sky-agent.sock
Return:
srwxrwxrwx 1 apache apache     0 May 23 10:13 sky-agent.sock
But when i restart services:
- systemctl restart php-fpm
- systemctl restart sky-php-agent
It's return:
srwxrwxrwx 1 root root     0 May 23 10:16 sky-agent.sock
Why :v ?

**Comment by RyoSanka** [comment]
sky-php-agent.service - The SkyWalking PHP-Agent Process Manager
   Loaded: loaded (/usr/lib/systemd/system/sky-php-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-05-23 10:40:57 +07; 12min ago
  Process: 4216 ExecStop=/bin/kill -SIGINT $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 4218 (sky-php-agent)
   CGroup: /system.slice/sky-php-agent.service
           └─4218 /usr/local/bin/sky-php-agent --grpc=192.168.1.50:11800 --sky-version=7 --socket=/tmp/sky-agent.sock

May 23 10:40:57 guess.com systemd[1]: Stopped The SkyWalking PHP-Agent Process Manager.
May 23 10:40:57 guess.com systemd[1]: Started The SkyWalking PHP-Agent Process Manager.
May 23 10:40:57 guess.com sky-php-agent[4218]: time="2020-05-23 10:40:57" level=info msg="hello skywalking"
May 23 10:40:57 guess.com sky-php-agent[4218]: time="2020-05-23 10:40:57" level=info msg="connection 192.168.1.50:11800..."
May 23 10:40:57 guess.com sky-php-agent[4218]: time="2020-05-23 10:40:57" level=info msg="🍺 skywalking php agent started successfully, enjoy yourself"

If config socks wrong, why status like this: "skywalking php agent started successfully, enjoy yourself "

**Comment by heyanlong** [comment]
need disable privatetmp feature
