### ISSUE TITLE
使用github最新php 探针v3.3,无报错，却一直无法识别应用

### ISSUE THREAD

**Issue by sikelangya** [SkyAPM/SkyAPM-php-sdk#230]
**Describe the bug**
使用github最新php 探针v3.3,无报错，却一直无法识别应用

agent配置如下（通github一样）：

“”“”“”“”
Install sky-php-agent
Build
For installing the sky-php-agent, you first need to build it:

cd SkyAPM-php-sdk-3.3.0
go build -o sky-php-agent cmd/main.go
chmod +x sky-php-agent
cp sky-php-agent /usr/local/bin
How to use
Add SkyWalking config to php.ini and restart php-fpm
; Loading extensions in PHP
extension=skywalking.so

; enable skywalking
skywalking.enable = 1

; Set skyWalking collector version (5 or 6 or 7 or 8)
skywalking.version = 8

; Set app code e.g. MyProjectName
skywalking.app_code = MyProjectName

; sock file path default /tmp/sky-agent.sock
; Warning *[systemd] please disable PrivateTmp feature*
; Warning *Make sure PHP has read and write permissions on the socks file*
skywalking.sock_path=/tmp/sky-agent.sock
sky-php-agent systemd example
[Unit]
Description=The SkyWalking PHP-Agent Process Manager
After=syslog.target network.target

[Service]
Type=simple
# Modify the corresponding directory and address here
ExecStart=/usr/local/bin/sky-php-agent --grpc=127.0.0.1:11800 --sky-version=8 --socket=/tmp/sky-agent.sock
ExecStop=/bin/kill -SIGINT $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
“”“”“”“”“”“”“”“”“”

我的sw时7.0的版本，因为如上图中对应的sw版本我以改成7

agent 所在服务器，服务检测及启动情况

![image](https://user-images.githubusercontent.com/31874857/82181244-be572800-9914-11ea-919d-80da40e2fc28.png)
![image](https://user-images.githubusercontent.com/31874857/82181290-d038cb00-9914-11ea-82e8-076ccddbd9f2.png)

**Comment by sikelangya** [comment]
php版本7.0  ，php应用程序为apache+php应用（dzzoffice）+mysql

**Comment by sikelangya** [comment]
我开始也将php.d下面的 json.so文件给重命名了  将json.so手动加如到php.ini中，还是不行

**Comment by heyanlong** [comment]
把你的skywalking.ini发一下

**Comment by sikelangya** [comment]
教程上没有写需要我配置skywalking.ini文件   我也没有找到这个文件呢
这个是我的 php.ini
![image](https://user-images.githubusercontent.com/31874857/82198407-d9369600-992e-11ea-8e32-5d3b5867995d.png)

**Comment by sikelangya** [comment]
教程上没有写需要我配置skywalking.ini文件 我也没有找到这个文件呢
这个是我的 php.ini
![image](https://user-images.githubusercontent.com/31874857/82198500-fd927280-992e-11ea-8527-c990bb348241.png)

**Comment by sikelangya** [comment]
![image](https://user-images.githubusercontent.com/31874857/82277515-a2a65d00-99ba-11ea-85f5-83cf12648080.png)

**Comment by heyanlong** [comment]
请把json放skywalking前面
谢谢

**Comment by sikelangya** [comment]
![image](https://user-images.githubusercontent.com/31874857/82278414-bbb00d80-99bc-11ea-94af-05aa2a549aa7.png)
![image](https://user-images.githubusercontent.com/31874857/82278475-e00bea00-99bc-11ea-9e8e-b24b9adc9290.png)
![image](https://user-images.githubusercontent.com/31874857/82278547-10ec1f00-99bd-11ea-8c4f-97e34536b10e.png)
![image](https://user-images.githubusercontent.com/31874857/82278706-688a8a80-99bd-11ea-821b-fd2ab1986783.png)
没有任何报错了，但是  sw上还是没有识别到 应用

**Comment by heyanlong** [comment]
查看PHP日志是否有警告信息，你这情况应该是sock文件不可读写导致的

**Comment by sikelangya** [comment]
我看看日志有没有报错   
![image](https://user-images.githubusercontent.com/31874857/82280521-996cbe80-99c1-11ea-8519-751697799e52.png)
sock文件支持读写的

**Comment by heyanlong** [comment]
PHP是systemd 管理的？

**Comment by sikelangya** [comment]
是的  这是配置文件
![image](https://user-images.githubusercontent.com/31874857/82290856-6daa0280-99da-11ea-9881-61af126cace8.png)

**Comment by heyanlong** [comment]
把PrivateTmp设置为false试一下

**Comment by sikelangya** [comment]
请问，还要怎么排查呢

**Comment by sikelangya** [comment]
把PrivateTmp设置为false   这个是要卸载systemd里面 还是php。ini里面呢

**Comment by sikelangya** [comment]
已经将php-fpm.service中的PrivateTmp设置为false了   还是没有识别我的php应用

**Comment by sikelangya** [comment]
我在我的sky-php.service文件里面也加了这行，httpd.service中也改成了 false   重启后  还是没有的我应用

**Comment by heyanlong** [comment]
都重启了？你的网站有流量没？

**Comment by sikelangya** [comment]
有的 我自己搭建的 zabbix5.0    网站实时在获取数据  我也在访问  刷新各个页面

**Comment by heyanlong** [comment]
把 php, apache, agent 的systemd配置发出来吧

**Comment by sikelangya** [comment]
这个是nginx的
![image](https://user-images.githubusercontent.com/31874857/82397688-88848180-9a83-11ea-81b6-e006cdd60178.png)
这个是SW_ anget的
![image](https://user-images.githubusercontent.com/31874857/82397721-9b975180-9a83-11ea-9885-35bb0c46e2b6.png)
这个是php-fpm的
![image](https://user-images.githubusercontent.com/31874857/82397797-d1d4d100-9a83-11ea-9b33-58e93fc222cd.png)

**Comment by heyanlong** [comment]
配置都对

**Comment by sikelangya** [comment]
那要怎么测试  问题出在哪里?

**Comment by heyanlong** [comment]
我怀疑PHP没有读取这个sock的权限，你写个fopen("/tmp/xx") 看看在fpm下运行，能打开吗

**Comment by sikelangya** [comment]
![image](https://user-images.githubusercontent.com/31874857/82428860-aff84000-9abd-11ea-8576-df9dc48f92ac.png)
我的 sock文件大小一直是0

**Comment by heyanlong** [comment]
这个文件本来就是0，QQ我吧

**Comment by sikelangya** [comment]
2777055213   麻烦您加我下把

**Comment by YaphetsFans** [comment]
@sikelangya 您好，我也遇到了这个问题，请问方便沟通一下吗？
