### ISSUE TITLE
skywalking收不到php数据

### ISSUE THREAD

**Issue by embrace-jy** [SkyAPM/SkyAPM-php-sdk#231]
我按照攻略安装完成后，skywalking收不到php的数据，message日志里有报错如下：
sky-php-agent: time="2020-05-20 10:01:41" level=info msg="start register pid 31251 used SkyWalking v7"
sky-php-agent: time="2020-05-20 10:01:41" level=error msg="register error:<nil>"
sky-php-agent: time="2020-05-20 10:01:41" level=info msg="start register pid 31251 used SkyWalking v7"
sky-php-agent: time="2020-05-20 10:01:41" level=error msg="register error:<nil>"
sky-php-agent: time="2020-05-20 10:01:41" level=info msg="start register pid 31251 used SkyWalking v7"
sky-php-agent: time="2020-05-20 10:01:41" level=error msg="register error:<nil>"
sky-php-agent: time="2020-05-20 10:01:41" level=info msg="start register pid 31251 used SkyWalking v7"
sky-php-agent: time="2020-05-20 10:01:41" level=error msg="register error:<nil>"

帮忙看看怎么修复。。。谢谢

**Comment by heyanlong** [comment]
配置发一下

**Comment by embrace-jy** [comment]
php.ini
extension=json.so
extension=skywalking.so
skywalking.enable = 1
skywalking.version = 7
skywalking.app_code = php
;skywalking.grpc = 192.168.0.130:11800
skywalking.sock_path=/tmp/sky-agent.sock

sky-php-agent.service
[Unit]
Description=The SkyWalking PHP-Agent Process Manager
After=syslog.target network.target

[Service]
Type=simple
# Modify the corresponding directory and address here
ExecStart=/usr/bin/sky-php-agent --grpc=192.168.0.130:11800 --socket=/tmp/sky-agent.sock
ExecStop=/bin/kill -SIGINT $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target

/usr/lib/systemd/system/php-fpm.service
[Unit]
Description=The PHP FastCGI Process Manager
After=syslog.target network.target

[Service]
Type=notify
PIDFile=/var/run/php-fpm/php-fpm.pid
EnvironmentFile=/etc/sysconfig/php-fpm
ExecStart=/usr/sbin/php-fpm --nodaemonize --fpm-config /etc/php-fpm.conf
ExecReload=/bin/kill -USR2 $MAINPID
PrivateTmp=false

[Install]
WantedBy=multi-user.target

**Comment by heyanlong** [comment]
/usr/bin/sky-php-agent 需要写个sky-version把

**Comment by embrace-jy** [comment]
![image](https://user-images.githubusercontent.com/65637904/82397792-ced9e080-9a83-11ea-8788-05257a871686.png)
加了这个就会报错

**Comment by embrace-jy** [comment]
cd SkyAPM-php-sdk-3.3.0
go build -o sky-php-agent cmd/main.go
go: google.golang.org/grpc@v1.21.1: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
执行这个命令会有个报错

**Comment by heyanlong** [comment]
好吧，稍等

**Comment by heyanlong** [comment]
大概理解你的思路，php是编译的3.3.0版本，但是agent是随便找了一个？

https://github.com/SkyAPM/SkyAPM-php-sdk/releases/tag/v3.3.0

我刚上传3.3.0的agent了，下载一下吧

**Comment by embrace-jy** [comment]
我试一下，谢啦，agent是下载的，地址如下：
https://github.com/SkyAPM/SkyAPM-php-sdk/releases/download/3.2.0/sky-php-agent-linux-x64

**Comment by embrace-jy** [comment]
您好，新的agent能跑起来，但是还是有报错
time="2020-05-20 13:00:07" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:07" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:07" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:07" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:07" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:07" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:07" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:07" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:07" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:07" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:08" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:08" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:08" level=info msg="start register pid 31251 used SkyWalking v7"
time="2020-05-20 13:00:08" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties"
time="2020-05-20 13:00:08" level=info msg="start register pid 31251 used SkyWalking v7"

**Comment by embrace-jy** [comment]
可以了。。。谢谢帮助，skywalking已经收到数据了

**Comment by aoxiang0070** [comment]
@embrace-jy 你好，我也遇到你最后的那个问题了，请问下，你是怎么解决的，谢谢

**Comment by heyanlong** [comment]
应该是设置 sky-version 吧

**Comment by aoxiang0070** [comment]
> 应该是设置 sky-version 吧

是这个问题，现在解决了，谢谢
