### ISSUE TITLE
php post请求报502

### ISSUE THREAD

**Issue by stonehun** [SkyAPM/SkyAPM-php-sdk#232]
[20-May-2020 18:26:28] WARNING: [pool www] child 13 exited on signal 11 (SIGSEGV - core dumped) after 828.547791 seconds from start

**Comment by heyanlong** [comment]
什么版本？可以给一个复现代码吗？

**Comment by stonehun** [comment]
public static function sendHttp($url, $type = 'POST', $params = [], $header = [], $cookies=[])
    {
        $time = -microtime(true);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_REFERER, CURRENT_URL);
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 YKJ-COMMON-CLIENT");
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // 对认证证书来源的检查
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); // 从证书中检查SSL加密算法是否存在
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_TIMEOUT, 3); // 设置超时限制防止死循环
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $type); //设置提交方式
        if (!empty($params)) {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $params); // Post提交的数据包
        }
        if (!empty($cookies)){
            curl_setopt($ch,CURLOPT_COOKIE, self::cookieToString($cookies));
        }

        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json; charset=UTF-8']); // 设置HTTP头

        $result = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        $time += microtime(true);

        \Yii::info([
            'file' => __FILE__,
            'url' => $url,
            'params' => $params,
            'time' => $time,
            'response_code' => $httpCode
        ], 'sdk_utils_request_helper');

       // var_dump($params);die();

        return $result;
    }
curl 有自定义header就502 取掉就ok php版本7.08 扩展最新master

**Comment by stonehun** [comment]
如果设置了自定义header 取掉 curl_close502也会消失

**Comment by heyanlong** [comment]
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json; charset=UTF-8']); 有这一行就出问题？

**Comment by stonehun** [comment]
void sky_curl_close_handler(INTERNAL_FUNCTION_PARAMETERS) {

  
    orig_curl_close(INTERNAL_FUNCTION_PARAM_PASSTHRU);
}
对 但是去掉 curl_close 有这一行也正常

上面源码我改成这样也不会502
