### ISSUE TITLE
没有日志产生

### ISSUE THREAD

**Issue by YeDongaidiiqu** [SkyAPM/SkyAPM-php-sdk#235]
**Describe the bug**
没有日志产生

**To Reproduce**
![image](https://user-images.githubusercontent.com/25131877/83229630-e79c7180-a1ba-11ea-8c9e-d89bb2b953bf.png)

**Expected behavior**

**Screenshots**

**PHP (please complete the following information):**

**SkyWalking (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 6.4]

**Additional context**
一直没有日志生成

**Comment by gclove** [comment]
需要看一下 php 是否加载插件，以及  skywalking.sock_path 配置

**Comment by YeDongaidiiqu** [comment]
> 需要看一下 php 是否加载插件，以及 skywalking.sock_path 配置

配置错了
