### ISSUE TITLE
sky-php-agent: report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties

### ISSUE THREAD

**Issue by Jonybin** [SkyAPM/SkyAPM-php-sdk#238]
when i run as sky-php-agent, the error is coming;
```
INFO[2020-05-31 21:06:46] hello skywalking
INFO[2020-05-31 21:06:46] connection 127.0.0.1:11800...
INFO[2020-05-31 21:06:46] ðº skywalking php agent started successfully, enjoy yourself
INFO[2020-05-31 21:06:48] start register pid 28750 used SkyWalking v8
ERRO[2020-05-31 21:06:48] report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties
```

I follow this blog to install skywalking
  [the blog quick start ](http://skywalking.apache.org/zh/blog/2020-04-19-skywalking-quick-start.html)

**skywalking version:** 6.6

**elasticsearch:**  6.5

then installing the php-sdk:

following the blog: [sky-php-agent](https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/install.md) 

the config as the blog's config

**php.ini:** 
extension=skywalking.so
skywalking.enable = 1
skywalking.version = 8
skywalking.app_code = myskywalk
skywalking.sock_path=/tmp/sky-agent.sock

**Comment by Jonybin** [comment]
Who can help me to see this problem？thanks

**Comment by heyanlong** [comment]
```
skywalking.version = 6
```
and

```
sky-agent --sky-version=6
```

**Comment by Jonybin** [comment]
> ```
> skywalking.version = 6
> ```
> 
> and
> 
> ```
> sky-php-agent --sky-version=6
> ```

yeah!, it works, thank you very much.


but the new errror is occuring. 

```
register error:<nil>
INFO[2020-06-01 14:24:52] start register pid 2297 used SkyWalking v6
ERRO[2020-06-01 14:24:55] register error:rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

 i  find another one solution: [PHP-SDK报错提示：error:rpc error: code = DeadlineExceeded desc = context deadline exceeded #214
](https://github.com/SkyAPM/SkyAPM-php-sdk/issues/214)

and the error is :
elasticsearch Exception in thread "main" java.nio.file.AccessDeniedException

the solution is [Elasticsaerch启动报错：Exception in thread "main" java.nio.file.AccessDeniedException:](https://blog.csdn.net/qq_31674359/article/details/80671749)
