### ISSUE TITLE
k8s中cronjob pod结束了日志没上报上去

### ISSUE THREAD

**Issue by YeDongaidiiqu** [SkyAPM/SkyAPM-php-sdk#239]
用的是k8s的cronjob  执行的脚本，脚本执行完后，日志没发上去，这个有手动触发日志发送的机制么

**Comment by heyanlong** [comment]
cronjob 工作流程是什么

**Comment by YeDongaidiiqu** [comment]
apiVersion: batch/v1beta1
kind: CronJob
k8s的cronjob 调度，
脚本执行的是cli,我改了下扩展，支持cli
![image](https://user-images.githubusercontent.com/25131877/84243151-5e7b2800-ab34-11ea-90dc-c35865fdbdd0.png)

但是k8s在脚本执行完后就把pod杀掉， 日志没来得及上报上去，有没有办法手动触发上报呢

**Comment by heyanlong** [comment]
首先支持cli意义不大，然后数据上报需要有个注册过程，cli生命周期是一次性的，所以没注册成功

**Comment by YeDongaidiiqu** [comment]
![image](https://user-images.githubusercontent.com/25131877/87897168-12999800-ca7d-11ea-8816-62dee62ad331.png)
注册成功了，但是没上报上去， @heyanlong

**Comment by heyanlong** [comment]
你是cli吗？

**Comment by YeDongaidiiqu** [comment]
> 吗

对的，我看你代码里面写了，为啥不放开cli呢
![image](https://user-images.githubusercontent.com/25131877/88033088-7c936980-cb71-11ea-800c-ddf5d0b8ee39.png)
我把这个改成了1 ，能收到消息

**Comment by heyanlong** [comment]
因为cli的生命周期有一点问题
