### ISSUE TITLE
如何设置实例的名称（service instance）？

### ISSUE THREAD

**Issue by laster-bin** [SkyAPM/SkyAPM-php-sdk#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**PHP (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 7.0.0]
 - PHP ini

**SkyWalking (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 6.4]

**Additional context**
![image](https://user-images.githubusercontent.com/31149409/88151334-24be3680-cc35-11ea-9f03-8aec3d51f823.png)
![instance-name](https://user-images.githubusercontent.com/31149409/88151478-56cf9880-cc35-11ea-9828-07d68436b14f.png)

**Comment by heyanlong** [comment]
防止重复，这里为自动生成
