### ISSUE TITLE
开启sky-php-agent后elasticsearch7 查询报错

### ISSUE THREAD

**Issue by NicholasChan1025** [SkyAPM/SkyAPM-php-sdk#244]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**PHP (please complete the following information):**
 - OS: ubuntu
 - Version 7.2.31
 - PHP ini

**SkyWalking (please complete the following information):**
 - OS: 官方docker
 - Version [e.g. 6.4]

**Additional context**

开启sky-php-agent
使用ruflin/elastica 7x的拓展查询会报
Content-Type header [application/x-www-form-urlencoded] is not supported
的Http请求错误，关闭sky-php-agent后正常

**Comment by heyanlong** [comment]
感谢反馈
