### ISSUE TITLE
sky-php-agent支持authentication验证吗？没找到相应的配置参数

### ISSUE THREAD

**Issue by Tan-Pchan** [SkyAPM/SkyAPM-php-sdk#245]
INFO[ ] start register pid 6492 used SkyWalking v8   
ERRO[ ] report instance properties:rpc error: code = PermissionDenied desc =

**Comment by heyanlong** [comment]
java是怎么配置的？

**Comment by Tan-Pchan** [comment]
java agent有配置该参数。
agent.authentication = ${SW_AGENT_AUTHENTICATION:Yt1NaTHbMechI9C}

**Comment by heyanlong** [comment]
感谢，最近会加上
