### ISSUE TITLE
time="2020-07-31 11:20:55" level=error msg="report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties" time="2020-07-31 11:20:55" level=info msg="start register pid 16652 used SkyWalking v6"

### ISSUE THREAD

**Issue by lycclsltt** [SkyAPM/SkyAPM-php-sdk#246]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**PHP (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 7.0.0]
 - PHP ini

**SkyWalking (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 6.4]

**Additional context**

**Comment by heyanlong** [comment]
sky-agent start parameter add version = 6
