### ISSUE TITLE
这个扩展对php会造成多大的性能损耗呢？是否有对比结果？

### ISSUE THREAD

**Issue by lycclsltt** [SkyAPM/SkyAPM-php-sdk#247]
如题

**Comment by ximply** [comment]
同问

**Comment by wanghoneygit** [comment]
@lycclsltt 
![image](https://user-images.githubusercontent.com/20147781/90353005-9bedbb80-e077-11ea-8220-ab3ef380c374.png)
![image](https://user-images.githubusercontent.com/20147781/90353030-aad46e00-e077-11ea-8d75-c8c359a28e09.png)
![image](https://user-images.githubusercontent.com/20147781/90353072-d35c6800-e077-11ea-9ed5-e62ed3ce1ab3.png)
我已经安装了 go 1.13.15 ，grpc 和 protobuf 也安装了，skyWalking 扩展也安装了。但是执行「/usr/local/bin/sky-php-agent --grpc=test.uc.host.dxy:888 --sky-version=8 --socket=/tmp/sky-agent.sock」 ，再访问了对应的项目，就报了这个错，能麻烦帮忙瞅瞅么。

**Comment by lycclsltt** [comment]
@wanghoneygit  看起来是agent rpc请求 skywalking失败了

**Comment by wanghoneygit** [comment]
@lycclsltt 是的，因为我请求的地址需要使用到证书。所以 agent rpc 请求失败了，但是请教下哪个参数指定证书文件位置？

后来，我麻烦同事在本地起了一个 skywalking 服务，但是返回结果还是失败了，能麻烦帮忙瞅瞅么。
![image](https://user-images.githubusercontent.com/20147781/90466906-7929d880-e145-11ea-855e-cc05d521624e.png)

**Comment by wu-sheng** [comment]
你贴的第二个错误，应该是版本不对应，后端提示的这个是8.0+版本的，agent也需要开启指定版本。

**Comment by wu-sheng** [comment]
另外，不同问题请不要在一个issue中讨论。

**Comment by wanghoneygit** [comment]
好的。。
