### ISSUE TITLE
是否支持命令行跑的任务

### ISSUE THREAD

**Issue by ijackwu** [SkyAPM/SkyAPM-php-sdk#249]
比如直接 `php test.php` 不使用`php-fpm` 
像swoole开发的项目都是命令行的

**Comment by heyanlong** [comment]
cli模式，如果内部死循环处理一些事情，比如mq消费者，这种是没法判定是否结束的，导致trace无法上报

**Comment by ijackwu** [comment]
明白，谢谢！
