### ISSUE TITLE
sky-php-agent启动后，报错report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties

### ISSUE THREAD

**Issue by wanghoneygit** [SkyAPM/SkyAPM-php-sdk#252]
sky-php-agent版本3.3.2
skywalking 服务端链接的是我公司的测试环境，但是连接该链接的话，需要证书，
「 /usr/local/bin/sky-php-agent --grpc=*****:888 --sky-version=8 --socket=/tmp/sky-agent.sock」
出现错误：`INFO[2020-08-17 18:00:39] hello skywalking
INFO[2020-08-17 18:00:39] connection oap-test.uc.host.dxy:888...
INFO[2020-08-17 18:00:39] 🍺 skywalking php agent started successfully, enjoy yourself

INFO[2020-08-17 18:01:57] start register pid 11558 used SkyWalking v8
ERRO[2020-08-17 18:01:57] report instance properties:rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed`
![image](https://user-images.githubusercontent.com/20147781/90463316-319f4e80-e13d-11ea-8838-abcdd6c9e3c8.png)

后来同事在本地起了一个skywalking，「/usr/local/bin/sky-php-agent --grpc=192.168.201.179:11800 --sky-version=8 --socket=/tmp/sky-agent.sock」，

出现错误：`~ /usr/local/bin/sky-php-agent --grpc=192.168.201.179:11800 --sky-version=8 --socket=/tmp/sky-agent.sock
INFO[2020-08-17 18:32:24] hello skywalking
INFO[2020-08-17 18:32:24] connection 192.168.201.179:11800...
INFO[2020-08-17 18:32:24] 🍺 skywalking php agent started successfully, enjoy yourself

INFO[2020-08-17 18:32:32] start register pid 17037 used SkyWalking v8
ERRO[2020-08-17 18:32:33] report instance properties:rpc error: code = Unimplemented desc = Method not found: ManagementService/reportInstanceProperties
![image](https://user-images.githubusercontent.com/20147781/90463306-2b10d700-e13d-11ea-809a-e0955f783c27.png)

**Comment by heyanlong** [comment]
oap版本是多少？看样子是两个版本不匹配导致的

**Comment by wanghoneygit** [comment]
当前使用的php版本：7.4.9
sky-sdk版本：SkyAPM-php-sdk-3.3.2
skywalking server 版本：v8.0 

![image](https://user-images.githubusercontent.com/20147781/91717097-6d1d2c80-ebc3-11ea-9709-d7e99ce0f040.png)
我在 php.ini 填写的也是  「skywalking.version = 8」

**Comment by heyanlong** [comment]
agent也需要设置为8
