### ISSUE TITLE
sky-php-agnet panic when oap service down

### ISSUE THREAD

**Issue by ximply** [SkyAPM/SkyAPM-php-sdk#254]
panic error log as follows:

WARN[2020-08-20 10:24:29] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.17.3.54:11800: connect: connection refused" 
ERRO[2020-08-20 10:24:29] no stream available                          
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x85d4a2]

goroutine 30 [running]:
github.com/SkyAPM/SkyAPM-php-sdk/reporter/service.(*Agent).send(0xc000176000, 0xc0000ac218, 0x1, 0x1)
        /root/SkyAPM-php-sdk-3.3.2/reporter/service/trace.go:114 +0x3a2
created by github.com/SkyAPM/SkyAPM-php-sdk/reporter/service.(*Agent).sub
        /root/SkyAPM-php-sdk-3.3.2/reporter/service/agent.go:184 +0x3a8

**Comment by heyanlong** [comment]
Thanks for feedback

**Comment by ximply** [comment]
New versions do not use this.
