### ISSUE TITLE
sky-php-agent not receiving peerId from oapserver[v-7]  

### ISSUE THREAD

**Issue by rohan2546** [SkyAPM/SkyAPM-php-sdk#257]
when connecting a php agent to oap server, with php being connected to mysql, mysql data doesn't get populated.

The mysql data is being sent by the php agent but peerId remains 0, and I cannot find peerId anywhere in sky-php-sdk.

Can you please suggest from where I can retrieve peerId in sky-php-sdk

**Comment by heyanlong** [comment]
What version to use?

**Comment by rohan2546** [comment]
I am using skywalking 7.0.0 and php-sdk 3.3.2

**Comment by heyanlong** [comment]
No peerId is 0, can you provide more information?

**Comment by rohan2546** [comment]
peerId is used in MultiScopesSpanListener and if (peerId ==0) the control doesn't save db data,

In php-sdk, peerId is not getting updated, so peerId remains 0 therefore db data for php in sw-7 doesn't get populated

**Comment by heyanlong** [comment]
Can you take a screenshot？

**Comment by rohan2546** [comment]
sw screenshots

<img width="888" alt="Screenshot 2020-08-24 at 11 21 49 AM" src="https://user-images.githubusercontent.com/31701608/91008610-5ba0b700-e5fc-11ea-99e6-a2dfacd3dfbb.png">
<img width="780" alt="Screenshot 2020-08-24 at 11 22 03 AM" src="https://user-images.githubusercontent.com/31701608/91008636-68bda600-e5fc-11ea-9e2f-6a2cf7a9a402.png">
<img width="783" alt="Screenshot 2020-08-24 at 11 22 24 AM" src="https://user-images.githubusercontent.com/31701608/91008643-6eb38700-e5fc-11ea-9157-46d0eb7205c2.png">

IN php-sdk

<img width="277" alt="Screenshot 2020-08-24 at 11 23 10 AM" src="https://user-images.githubusercontent.com/31701608/91008667-78d58580-e5fc-11ea-9909-f2569a696dac.png">
<img width="437" alt="Screenshot 2020-08-24 at 11 22 57 AM" src="https://user-images.githubusercontent.com/31701608/91008675-7bd07600-e5fc-11ea-9f89-d9a8a70cd2c6.png">

**Comment by heyanlong** [comment]
How is pdo initialized?

**Comment by rohan2546** [comment]
i am reading from mysql using php, on localhost:3306 and this scenario happens for any statement related to db , even SELECT, INSERT

**Comment by heyanlong** [comment]
Can you provide an example

**Comment by rohan2546** [comment]
basically any data related to db is not getting stored related to php agent, other agents are working fine

**Comment by heyanlong** [comment]
Discussion without code is messy and meaningless

**Comment by rohan2546** [comment]
So, when db data is sent for other agents
In MultiScopesSpanListener, peerId check is there, which is also the addressId, so for other agents data received contain that peerId but for php agent db data peerId is always 0.

Also, skywalking.c in php-sdk-agent contains initialisation for peer but not for peerId

**Comment by heyanlong** [comment]
So I need you to provide code to execute the test

**Comment by rohan2546** [comment]
I am using the original SkyAPM-php-sdk 3.3.2 and skywalking-7.0.0 with no changes and a normal php app. If you want I can share code for php app

**Comment by heyanlong** [comment]
Ok, share it

**Comment by rohan2546** [comment]
https://github.com/kiran1095/medibed

**Comment by heyanlong** [comment]
https://github.com/kiran1095/medibed/blob/be2c348ba4a84dd4361af87877ae4f70eab9307c/api/config/database.php#L17

Missing port

e.g. mysql:host=127.0.0.1;port=3306;dbname=test

**Comment by rohan2546** [comment]
I have made these changes and my application is working just fine I am able to get data from db, but db's metrices are not getting stored in sw-7

**Comment by heyanlong** [comment]
This is another question
