### ISSUE TITLE
php swoole场景如何应用skywalking

### ISSUE THREAD

**Issue by zyanru** [SkyAPM/SkyAPM-php-sdk#260]
公司基本上弃用了php-fpm，使用swoole，skywalking是否支持这种场景

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by feng99** [comment]
不支持    刚才我把所有的issues看了一遍  建议放弃吧.   自己写一个

**Comment by heyanlong** [comment]
master已支持，未来会发布到4.1.0
