### ISSUE TITLE
异常信息没有显示出来

### ISSUE THREAD

**Issue by joshua317** [SkyAPM/SkyAPM-php-sdk#262]
环境：
系统：centos7.4
php版本：php7.2
skywalking:7.0.0
SkyAPM-php-sdk:v3.3.2

**故意抛出异常，链路请求上报成功，但查看的时候异常信息没有显示,是需要在哪设置吗？？**
![image](https://user-images.githubusercontent.com/12826232/91969225-5e13b700-ed48-11ea-8440-9e19fcd4b4a4.png)

**Comment by heyanlong** [comment]
可以提供一下测试代码吗？

**Comment by joshua317** [comment]
我尝试了下语法错误和抛异常
`echo 'test'
exit;
`

`try {
    throw new \Exception('测试抛出异常');
} catch (\Exception $e) {
    echo $e->getMessage();
}`

php_errors.log里面的日志里面有记录
`[09-Sep-2020 19:25:10 PRC] PHP Parse error:  syntax error, unexpected 'exit' (T_EXIT), expecting ',' or ';' in /home/joshua317/public/index.php on line 12`

`[09-Sep-2020 19:30:30 PRC] PHP Fatal error:  Uncaught Error: Class 'TestException' not found in /home/joshua317/public/index.php:11
Stack trace:
#0 {main}
  thrown in /home/joshua317/public/index.php on line 11`


如果异常被捕获的话，是不是就没法上报了
