### ISSUE TITLE
kernel: php-fpm[27693]: segfault at 0 ip 000000000083ef62 sp 00007fff4829f050 error 4 in php-fpm[400000+ac9000]

### ISSUE THREAD

**Issue by ximply** [SkyAPM/SkyAPM-php-sdk#263]
php: 7.1.10
sky-sdk: SkyAPM-php-sdk-3.3.2
skywalking: apache-skywalking-apm-es7-8.1.0
os: CentOS 6.4 X64 
kernrl: Linux base_app_30_145 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

sometimes， /var/log/message will report kernel error message as title.

**Comment by heyanlong** [comment]
Can you provide more information?

**Comment by tristan-tsl** [comment]
i also encountered this problem

**Comment by heyanlong** [comment]
@tristan-tsl os? php version? skywalking-php version?
