### ISSUE TITLE
在php-fpm下是正常的，swoole下的数据就没有上传，是不支持吗还是缺少了配置呢

### ISSUE THREAD

**Issue by allenbin** [SkyAPM/SkyAPM-php-sdk#265]

**Comment by allenbin** [comment]
我用的是laravels ,并没有用协程功能！

**Comment by heyanlong** [comment]
不支持swoole

**Comment by devbian** [comment]
您好，我在support list中看到已经支持laravels了，但是我用最新版编译后，依然不能正常抓取laravels的请求信息。这个是还需要哪些配置吗？

**Comment by heyanlong** [comment]
使用的master？

**Comment by devbian** [comment]
> 使用的master？

使用的是4.1.2，不过后来我们测试ok了。
如果使用 `php bin/laravels start -d ` 的方式来启动，就不能抓取到数据，通过 nohup & 来运行，可以抓取到数据。

**Comment by heyanlong** [comment]
thanks for the feedback
