### ISSUE TITLE
An error occurred when compiling skywalking.so with master

### ISSUE THREAD

**Issue by xinfeingxia85** [SkyAPM/SkyAPM-php-sdk#268]
**The error message is as follows**:
/tmp/source/skywalking/src/manager.cc:27:10: fatal error: management/Management.grpc.pb.h: No such file or directory
 #include "management/Management.grpc.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Because grpc was installed incorrectly or other reasons, the system is ubuntu18.04.

**The first error**:
>checking for gpr_now in -lgpr... no
>configure: error: wrong gpr lib version or lib not found.

When the problem of installing libgrpc-dev is solved, compile again, the problem described above appears.
Whether to solve the "configure: error: wrong gpr lib version or lib not found" problem caused by the wrong method

Help to see what might be the problem? thanks!

**Comment by heyanlong** [comment]
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/install.md

**Comment by xinfeingxia85** [comment]
> https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/install.md

OK
Thank you!
