### ISSUE TITLE
想咨询下容器化部署sky-php的使用建议

### ISSUE THREAD

**Issue by shukuiyan** [SkyAPM/SkyAPM-php-sdk#269]
您好
1 我看到新版本的dockerfile中，没有启动sky-php-agent的过程，新版本不需要启动agent，只需要引入skywalking.so到php运行即可？https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docker/Dockerfile

2 按照上面这个dockerfile进行build镜像后，镜像大小超过了1G，主要应该是grpc组件比较大，这块有什么好的建议么，能缩小使用sky-php的镜像的依赖。

**Comment by heyanlong** [comment]
减少image层数

**Comment by heyanlong** [comment]
1、是的
