### ISSUE TITLE
SkyAPM-php-sdk使用过程中问题请教

### ISSUE THREAD

**Issue by hello-sky-main** [SkyAPM/SkyAPM-php-sdk#270]
各位大神好，我在容器化部署php应用，当前做法是：将nginx、php-fpm、sky-php-sdk打到同一个镜像里，容器启动时，通过supervisor启动nginx、fmp和sky-php-agent，但是在使用过程中遇到了下面几个问题，望不吝赐教，感谢感谢
1 php-agent日志的level级别在哪里调整，默认的info级别仅打印如下sending结果和数量，怎样能打印发送的具体数据内容？
time="2020-09-23 15:41:17" level=info msg="start sending trace..., count 1"
time="2020-09-23 15:41:17" level=info msg="  sending success"
2 请求进入应用系统后，怎样获取php-agent生成的traceId，因为后续定位问题时，需要拿traceId去定位nginx或者业务日志，目前想把调用链路中的traceId打印到nginx和业务日志中；
3 容器化部署时，实例名是随机生成的吗，怎样跟宿主机或者pod关联？
4 在ui中，选择特定服务，特定端点，当前实例下拉框经常显示不全，比如一共应该有3个实例，但是下拉框里仅展示了一个或者一个都没有展示（确认3个pod都有在上报）
5 sky-php-agent可以忽略掉特定的端点上报吗，比如健康检查接口等

**Comment by heyanlong** [comment]
1. 不可调整
1. 不可获取
1. 4.0.0 会有 IP 关联
1. 4.0.0 已修复
1. 目前不可忽略

**Comment by hello-sky-main** [comment]
> * 4.0.0 会有 IP 关联
> 
> * 4.0.0 已修复

感谢，4.0.0大概什么时候能发布呢

**Comment by daisanmu** [comment]
2，获取traceId 感觉也是挺刚需的，希望能提上日程。

**Comment by heyanlong** [comment]
获取ID没有实际意义，去skywalking UI 查看即可

**Comment by MingH-Chen** [comment]
获取ID还是有意义的，系统里面会打日志，有id可以更方便的追踪问题
