### ISSUE TITLE
Query regarding Support for Apache with PHP

### ISSUE THREAD

**Issue by Debanjan05** [SkyAPM/SkyAPM-php-sdk#277]
This is not a bug, but a query regarding Sky-php-sdk.

I have done the setup for nginx, it works fine. I want to connect a PHP application started using Apache instead of nginx, will it be supported normally? Or do I have to do some special configuration as mostly the documentation is nginx based.

Environment: Ubuntu 16
Skywalking collector: version 7

**Comment by heyanlong** [comment]
What is the running mode of apache + php?

**Comment by Debanjan05** [comment]
It is Apache + PHP-FPM
uses fastcgi

**Comment by heyanlong** [comment]
This mode can work
