### ISSUE TITLE
curl_setopt() expects exactly 2 parameters, 3 given at

### ISSUE THREAD

**Issue by nickfan** [SkyAPM/SkyAPM-php-sdk#284]
**Describe the bug**
phpenmod -v 7.3 skywalking cause:
curl_setopt() expects exactly 2 parameters, 3 given at

```
$php -v
PHP 7.3.23-4+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 18 2020 21:21:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.23-4+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
$ php -i |grep curl
/etc/php/7.3/cli/conf.d/20-curl.ini,
curl
curl.cainfo => no value => no value
libcurl => 7.58.0 => 7.58.0
```
curl_setopt() expects exactly 2 parameters, 3 given at

/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:73

guzzle version 6.3.3
laravel 5.8
disable skywalking ext works fine.

![image](https://user-images.githubusercontent.com/100613/97275851-6af8e680-1871-11eb-9ea5-88168fb84555.png)

![image](https://user-images.githubusercontent.com/100613/97276282-ef4b6980-1871-11eb-9fdd-5b28ad4b3d60.png)

**Comment by heyanlong** [comment]
Please use master or wait for 4.0.1
