### ISSUE TITLE
三天前发布的4.1.0是否已经支持swoole

### ISSUE THREAD

**Issue by Arealm** [SkyAPM/SkyAPM-php-sdk#295]
三天前发布的4.1.0是否已经支持swoole啦，谢谢？

**Comment by heyanlong** [comment]
已经支持，后续又修了两个bug，可以使用master或者4.1.1进行构建

**Comment by Arealm** [comment]
![image](https://user-images.githubusercontent.com/26957122/99384923-22ca6280-290b-11eb-9d46-53dea2f902d0.png)
thank you

**Comment by Arealm** [comment]
先跑起来，不辜负你们的劳作👍
