### ISSUE TITLE
configure: error: skywalking does not support ZTS

### ISSUE THREAD

**Issue by Arealm** [SkyAPM/SkyAPM-php-sdk#296]
目前安装文档好像不是很完善，安装起来很吃力

执行以下命令
**[root@izbp161nuocc3ipbqk68kez ext]# cd SkyAPM-php-sdk-4.1.0/
[root@izbp161nuocc3ipbqk68kez SkyAPM-php-sdk-4.1.0]# ./configure  --with-php-config=/usr/local/php72/bin/php-config**

checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php72
checking for PHP includes... -I/usr/local/php72/include/php -I/usr/local/php72/include/php/main -I/usr/local/php72/include/php/TSRM -I/usr/local/php72/include/php/Zend -I/usr/local/php72/include/php/ext -I/usr/local/php72/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php72/lib/php/extensions/no-debug-zts-20170718
checking for PHP installed headers prefix... /usr/local/php72/include/php
checking if debug is enabled... no
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 0.14.3 (ok)
checking for gawk... gawk
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether to enable skywalking support... yes, shared
configure: error: skywalking does not support ZTS

**Comment by heyanlong** [comment]
configure: error: skywalking does not support ZTS

**Comment by zengxio** [comment]
这个问题。我也遇到了。不晓得怎么处理。。
![image](https://user-images.githubusercontent.com/26474304/110726447-59c6da00-8254-11eb-9827-f99981d530dd.png)

**Comment by heyanlong** [comment]
skywalking does not support ZTS
