### ISSUE TITLE
重启系统后上报5分钟左右php-fpm就假死了，nginx显示502

### ISSUE THREAD

**Issue by MrYzys** [SkyAPM/SkyAPM-php-sdk#303]
每次需要重启系统才能正常上传，上传大概5分钟左右就502了，手动重启fpm之后就不会上报了。之前在7.4.1上编译的版本一直是不会上报，在扩展的源代码中增加日志发现线程挂掉了，本人C/C++渣渣，也没法更深一步DEBUG

php版本：7.4.12
编译参数：--prefix=/fix-data/bin/php --with-config-file-path=/fix-data/bin/php/etc --with-config-file-scan-dir=/fix-data/bin/php/conf.d --enable-fpm --with-fpm-user=app --with-fpm-group=app --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-iconv-dir --with-freetype=/fix-data/bin/freetype --with-jpeg --with-png --with-zlib --enable-xml --disable-rpath --enable-bcmath --enable-shmop --enable-sysvsem --enable-inline-optimization --with-curl=/fix-data/bin/curl --enable-mbregex --enable-mbstring --enable-intl --enable-ftp --enable-gd --with-openssl=/fix-data/bin/openssl --with-mhash --enable-pcntl --enable-sockets --with-xmlrpc --with-zip --without-libzip --enable-soap --with-gettext --enable-opcache --with-xsl --with-pear

SkyAPM-php-sdk版本：4.1.1

**Comment by heyanlong** [comment]
日志方便提供一下吗？

**Comment by MrYzys** [comment]
php-skywalking 的日志
![截屏2020-11-20 下午1 58 22](https://user-images.githubusercontent.com/35891752/99764637-766dc380-2b38-11eb-85e7-a679432f9d43.png)

php-fpm 的日志
[20-Nov-2020 13:53:28] NOTICE: fpm is running, pid 545
[20-Nov-2020 13:53:28] NOTICE: ready to handle connections

日志上看起来是正常的

root         553  0.0  0.7 623788 31584 ?        Ssl  14:53   0:00 php-fpm: master process (/fix-data/bin/php/etc/php-fpm.conf)
app          678  0.0  0.2 411236 10564 ?        S    14:53   0:00 php-fpm: pool www
app          679  0.0  0.2 411236 10560 ?        S    14:53   0:00 php-fpm: pool www
app          680  0.0  0.2 411236 10564 ?        S    14:53   0:00 php-fpm: pool www
app          681  0.0  0.2 411236 10564 ?        S    14:53   0:00 php-fpm: pool www
app          682  0.0  0.2 411236 10564 ?        S    14:53   0:00 php-fpm: pool www
app          713  0.0  0.2 411236 10568 ?        S    14:53   0:00 php-fpm: pool www
app          714  0.0  0.2 476772 10616 ?        S    14:53   0:00 php-fpm: pool www
app          716  0.0  0.2 484968 10624 ?        S    14:53   0:00 php-fpm: pool www
app          718  0.0  0.2 484968 10628 ?        S    14:53   0:00 php-fpm: pool www
app          719  0.0  0.2 550504 10680 ?        S    14:53   0:00 php-fpm: pool www
app          720  0.0  0.2 550504 10680 ?        S    14:53   0:00 php-fpm: pool www
app          721  0.0  0.2 550504 10680 ?        S    14:53   0:00 php-fpm: pool www
app          722  0.0  0.2 550504 10688 ?        S    14:53   0:00 php-fpm: pool www
app          723  0.0  0.2 550504 10700 ?        S    14:53   0:00 php-fpm: pool www
app          724  0.0  0.2 550504 10700 ?        S    14:53   0:00 php-fpm: pool www
app          725  0.0  0.2 550504 10700 ?        S    14:53   0:00 php-fpm: pool www
app          726  0.0  0.2 550508 10700 ?        S    14:53   0:00 php-fpm: pool www
app          727  0.0  0.2 550508 10700 ?        S    14:53   0:00 php-fpm: pool www
app          728  0.0  0.2 550508 10700 ?        S    14:53   0:00 php-fpm: pool www
app          729  0.0  0.2 550508 10704 ?        S    14:53   0:00 php-fpm: pool www

ps 看起来fpm也没有异常退出
strace php-fpm master 进程 看起来也是正常的：
strace: Process 553 attached
getpid()                                = 553
epoll_wait(10, [], 1, 274)              = 0
getpid()                                = 553
getpid()                                = 553
getpid()                                = 553
epoll_wait(10, [], 1, 1000)             = 0
getpid()                                = 553
getpid()                                = 553
getpid()                                = 553
epoll_wait(10, [], 1, 414)              = 0
getpid()                                = 553
getpid()                                = 553
getpid()                                = 553
epoll_wait(10, [], 1, 586)              = 0
getpid()                                = 553
getpid()                                = 553
getpid()                                = 553
epoll_wait(10, [], 1, 1000)             = 0
getpid()                                = 553
getpid()                                = 553
getpid()                                = 553
epoll_wait(10, [], 1, 1000)             = 0
getpid()                                = 553
getpid()                                = 553
getpid()                                = 553

**Comment by MrYzys** [comment]
这是我增加日志的版本的日志记录，看起来一切正常，有点难过，折腾了好几天了
to login
end login
to consumer
start login
getCredentials
consumer started
to sender
grpc_lts = false
sender started
the apache skywalking php plugin mounted
start consumer
start sender
getCredentials
grpc_lts = false
return creds
getIps
getIps failed
tempAddress != nullptr
tempAddress != nullptr
tempAddress != nullptr
tempAddress->ifa_addr->sa_family == AF_INET
tempAddress != nullptr
tempAddress->ifa_addr->sa_family == AF_INET
ip.find("127") != 0
tempAddress != nullptr
tempAddress != nullptr
!ips.empty()
generateUUID:
b767db46-58cc-badf-050d-2ea872728e81
return creds
connect report service
rc.ok()
rc.ok() && info != nullptr
start heartbeat
getCredentials
grpc_lts = false
return creds
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
login success
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
generateUUID:
79dc5ed5-42ad-5c97-b514-2703962c893e
consume new trace
s_info->sem_id != -1
full.length() > 0
start write
write success
{"traceId":"79dc5ed542ad5c97b5142703962c893e.684.1369772354","traceSegmentId":"79dc5ed542ad5c97b5142703962c893e.684.1369772354","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1605855858091","endTime":"1605855858578","refs":[],"operationName":"/api/resume/highlight/example","peer":"wapi.hechuan.dev.weiheinc.com:40083","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/api/resume/highlight/example?limit=10&_debug=666&_client_id=78c870b8863d9fb47d167066ede3c334&resume_id=1"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false},{"spanId":1,"parentSpanId":0,"startTime":"1605855858475","endTime":"1605855858477","refs":[],"operationName":"PDO-\u003eexec","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"use `new_user_db`;"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":2,"parentSpanId":0,"startTime":"1605855858477","endTime":"1605855858480","refs":[],"operationName":"PDO-\u003eprepare","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"set names 'utf8mb4' collate 'utf8mb4_bin'"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":3,"parentSpanId":0,"startTime":"1605855858480","endTime":"1605855858482","refs":[],"operationName":"PDOStatement-\u003eexecute","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"set names 'utf8mb4' collate 'utf8mb4_bin'"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":4,"parentSpanId":0,"startTime":"1605855858482","endTime":"1605855858484","refs":[],"operationName":"PDO-\u003eprepare","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"insert into `t_session_web`(`iCurrentIp`, `sClientId`, `iLoginUserId`, `iLoginExpireTime`, `iCurrentUserId`, `iCreateTime`, `_iModifyTime`, `_iInsertTime`)values('1918230990', '78c870b8863d9fb47d167066ede3c334', '0', '0', '0', '1605855858', '1605855858', '1605855858')\n                    on duplicate key update\n                    iCurrentIp='1918230990' ,_iModifyTime='1605855858';"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":5,"parentSpanId":0,"startTime":"1605855858484","endTime":"1605855858489","refs":[],"operationName":"PDOStatement-\u003eexecute","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"insert into `t_session_web`(`iCurrentIp`, `sClientId`, `iLoginUserId`, `iLoginExpireTime`, `iCurrentUserId`, `iCreateTime`, `_iModifyTime`, `_iInsertTime`)values('1918230990', '78c870b8863d9fb47d167066ede3c334', '0', '0', '0', '1605855858', '1605855858', '1605855858')\n                    on duplicate key update\n                    iCurrentIp='1918230990' ,_iModifyTime='1605855858';"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":6,"parentSpanId":0,"startTime":"1605855858510","endTime":"1605855858514","refs":[],"operationName":"PDO-\u003eexec","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"use `new_user_db`;"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":7,"parentSpanId":0,"startTime":"1605855858514","endTime":"1605855858518","refs":[],"operationName":"PDO-\u003eprepare","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"set names 'utf8mb4' collate 'utf8mb4_bin'"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":8,"parentSpanId":0,"startTime":"1605855858518","endTime":"1605855858522","refs":[],"operationName":"PDOStatement-\u003eexecute","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"set names 'utf8mb4' collate 'utf8mb4_bin'"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":9,"parentSpanId":0,"startTime":"1605855858522","endTime":"1605855858526","refs":[],"operationName":"PDO-\u003eprepare","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"select * from `t_session_web` where `t_session_web`.`sClientId` = ? and `t_session_web`.`_iDeleteTime` = ? limit 1"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false},{"spanId":10,"parentSpanId":0,"startTime":"1605855858526","endTime":"1605855858530","refs":[],"operationName":"PDOStatement-\u003eexecute","peer":"rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com:3306","spanType":"Exit","spanLayer":"Database","componentId":8003,"isError":false,"tags":[{"key":"db.statement","value":"select * from `t_session_web` where `t_session_web`.`sClientId` = ? and `t_session_web`.`_iDeleteTime` = ? limit 1"},{"key":"db.type","value":"mysql"},{"key":"db.data_source","value":"host=rm-uf6019g2x6m9o739d8o.mysql.rds.aliyuncs.com;port=3306;dbname=new_user_db"}],"logs":[],"skipAnalysis":false}],"service":"service","serviceInstance":"service_instance","isSizeLimited":false}
messageQueue.empty
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);
send heartbeat
ping.set_serviceinstance(serviceInstance);
stub->keepAlive(&context, ping, &commands);

**Comment by MrYzys** [comment]
在重启php-fpm的时候还可以在oap-server日志上检测到断开连接的日志：
2020-11-20 15:08:13,015 - org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler - 84 [grpcServerPool-1-thread-6] ERROR [] - CANCELLED: cancelled before receiving half close
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.32.1.jar:1.32.1]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:273) [grpc-stub-1.32.1.jar:1.32.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353) [grpc-core-1.32.1.jar:1.32.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341) [grpc-core-1.32.1.jar:1.32.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:861) [grpc-core-1.32.1.jar:1.32.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.32.1.jar:1.32.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.32.1.jar:1.32.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

**Comment by MrYzys** [comment]
启动到502期间 oap-server的日志：
2020-11-20 15:09:58,169 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 7340 millis, size: 131
2020-11-20 15:10:08,173 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 7000 millis, size: 87
2020-11-20 15:10:11,175 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:14,177 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:17,179 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:20,181 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:23,182 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:26,185 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:29,187 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:32,188 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:35,191 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:35,472 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 81 [pool-6-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.
2020-11-20 15:10:38,193 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:41,195 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:44,196 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1
2020-11-20 15:10:47,198 - org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client - 294 [pool-5-thread-1] INFO  [] - Synchronous bulk took time: 0 millis, size: 1

**Comment by MrYzys** [comment]
手动重启php-fpm后skywalking的日志，手动重启后是不会上报的，必须要重启服务器才会开始上报
to login
start login
getCredentials
end login
to consumer
grpc_lts = false
consumer started
to sender
sender started
the apache skywalking php plugin mounted
return creds
getIps
getIps failed
tempAddress != nullptr
tempAddress != nullptr
tempAddress != nullptr
tempAddress->ifa_addr->sa_family == AF_INET
tempAddress != nullptr
tempAddress->ifa_addr->sa_family == AF_INET
ip.find("127") != 0
tempAddress != nullptr
tempAddress != nullptr
!ips.empty()
generateUUID:
2b809601-5bb3-1b81-e516-e7e2d642a522
start sender
getCredentials
grpc_lts = false
return creds
connect report service
rc.ok()
rc.ok() && info != nullptr
start heartbeat
getCredentials
grpc_lts = false
return creds
send heartbeat
ping.set_serviceinstance(serviceInstance);
start consumer
stub->keepAlive(&context, ping, &commands);

**Comment by heyanlong** [comment]
现在是什么问题呢？

**Comment by MrYzys** [comment]
已经放弃4.x版本的扩展了，改用3.x的方案可以稳定运行。没有找到问题的根本原因

**Comment by heyanlong** [comment]
重启命令是什么？

**Comment by MrYzys** [comment]
reboot

**Comment by heyanlong** [comment]
fpm是前台模式吗？

**Comment by MrYzys** [comment]
1、之前没详细翻看issue，是后台运行的问题导致不上报的，现在改为前台可以正常推了。中途踩的坑比较多，可能还有别的不清楚的问题。好在现在已经正常了～ 感恩～
2、4.1.1和guzzlehttp存在兼容问题，在使用aliyunsdk的时候触发了这个问题，表现为fpm子进程被SIGSEGV信号杀死。我昨日clone最新的代码编译的扩展就没有这个问题了，看到是更新了curl的部分，不知道具体是哪一块影响的。

注：因为编译安装文档里面并没有提及前后台运行的影响，折腾了很久，希望尽可能的完善文档。

PS. 感谢你们的贡献，不过现在的版本还是不太敢在生产环境部署。
