### ISSUE TITLE
仅安装PHP扩展和Skywalking服务器端后 不显示性能信息

### ISSUE THREAD

**Issue by lesecho** [SkyAPM/SkyAPM-php-sdk#304]
我根据github这上面的文档，仅仅为了部署一下，体验如何收集PHP服务器的性能数据，所以：
1.web服务器安装PHP扩展
由于protobuf和grpc各种依赖问题，最后找了许多版本，最终安装成功：
CentOS Linux release 7.6.1810 (Core)
gcc-4.9.0.tar.gz
protobuf-all-3.7.1.tar.gz
grpc_v1.24.0.tar.gz

skywalking.so也成功加载：
[root@ecs-69b0-0001 72]# php -r 'phpinfo();' | grep skywalking
skywalking
skywalking.app_code => ajy_skywalking => ajy_skywalking
skywalking.authentication => no value => no value
skywalking.enable => On => On
skywalking.grpc => xxx.ccc.vvv.bbb:11800 => xxx.ccc.vvv.bbb:11800
skywalking.grpc_tls_enable => 0 => 0
skywalking.grpc_tls_pem_cert_chain => no value => no value
skywalking.grpc_tls_pem_private_key => no value => no value
skywalking.grpc_tls_pem_root_certs => no value => no value
skywalking.log_enable => 0 => 0
skywalking.log_path => /tmp/sky => /tmp/sky
skywalking.version => 8 => 8

2.部署一个单节点skywalking，默认H2存储，经过一段时间，已经获取到PHP节点监控信息，但是没有别的性能信息：
![image](https://user-images.githubusercontent.com/32698088/99864494-9eaffd80-2bde-11eb-8987-3c1eadfe92d2.png)

还需要做什么，才能获取到大佬们展示的那样的数据呢

**Comment by lesecho** [comment]
只有仪表盘中的APM->instance有数据
而且如上图所示，今天是11.21数据显示的还是昨天的，
拓扑图 追踪 和性能分析都没有数据，
我还要完善什么呢

**Comment by lesecho** [comment]
php版本 7.2
[root@  SkyAPM-php-sdk-4.1.1]# php -v
PHP 7.2.33 (cli) (built: Aug 31 2020 09:56:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by lesecho** [comment]
按说和elastic apm 的原理类似，都是server端接受web服务器的数据，我在同一个web服务器仅安装elastic php扩展，使用elastic apm server测试是可以获取到数据的：
![image](https://user-images.githubusercontent.com/32698088/99867408-2eac7200-2bf4-11eb-9fb7-17ccfd05446e.png)

**Comment by heyanlong** [comment]
后续会添加性能信息收集

**Comment by lesecho** [comment]
多谢大佬提醒，很感谢，我这样就不会再纠结这个点了
