### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ximply** [SkyAPM/SkyAPM-php-sdk#305]
Error Mesage:
In file included from /usr/local/php/include/php/Zend/zend_types.h:27:0,
                 from /usr/local/php/include/php/Zend/zend.h:31,
                 from /usr/local/php/include/php/main/php.h:35,
                 from ./php_skywalking.h:29,
                 from /home/www/src/SkyAPM-php-sdk-4.1.1/src/manager.cc:36:
/usr/local/php/include/php/Zend/zend_operators.h: In function ‘zend_long zend_dval_to_lval(double)’:
/usr/local/php/include/php/main/php_config.h:2543:34: error: ‘isfinite’ was not declared in this scope
 #define zend_finite(a) isfinite(a)
....

System Info:
Centos 6.4 Linux 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
gcc 5.5.0

**Comment by heyanlong** [comment]
php version?

**Comment by ximply** [comment]
PHP 7.1.10 (cli) (built: Oct 25 2017 22:57:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies

**Comment by ximply** [comment]
upgrade gcc to 6.1.0 fix it,but another error here:

In file included from /usr/local/php/include/php/Zend/zend.h:31:0,
                 from /usr/local/php/include/php/main/php.h:35,
                 from ./php_skywalking.h:29,
                 from /home/www/src/SkyAPM-php-sdk-4.1.1/src/sky_curl.h:18,
                 from /home/www/src/SkyAPM-php-sdk-4.1.1/src/sky_curl.cc:15:
/home/www/src/SkyAPM-php-sdk-4.1.1/src/sky_curl.cc: In function ‘void sky_curl_setopt_array_handler(zend_execute_data*, zval*)’:
/usr/local/php/include/php/Zend/zend_types.h:304:22: error: invalid conversion from ‘int’ to ‘zend_expected_type {aka _zend_expected_type}’ [-fpermissive]
 #define IS_UNDEF     0
                      ^
/usr/local/php/include/php/Zend/zend_API.h:723:39: note: in expansion of macro ‘IS_UNDEF’
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^~~~~~~~
/usr/local/php/include/php/Zend/zend_API.h:750:2: note: in expansion of macro ‘ZEND_PARSE_PARAMETERS_START_EX’
  ZEND_PARSE_PARAMETERS_START_EX(0, min_num_args, max_num_args)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/www/src/SkyAPM-php-sdk-4.1.1/src/sky_curl.cc:67:5: note: in expansion of macro ‘ZEND_PARSE_PARAMETERS_START’
     ZEND_PARSE_PARAMETERS_START(2, 2)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
make: *** [src/sky_curl.lo] Error 1

**Comment by ximply** [comment]
![image](https://user-images.githubusercontent.com/3693445/99882509-eb85e980-2c5b-11eb-8f46-2a75b40d5538.png)
![image](https://user-images.githubusercontent.com/3693445/99882513-fa6c9c00-2c5b-11eb-8469-a86fdca5fb88.png)

**Comment by ximply** [comment]
Now is ok， but I think this is a bad solution.

**Comment by heyanlong** [comment]
#298
