### ISSUE TITLE
Skywalking: gRPC: CANCELLED: cancelled before receiving half close

### ISSUE THREAD

**Issue by garysdevil** [SkyAPM/SkyAPM-php-sdk#307]
Expection:
The php extension can not connct to skywalking in this machine, and **no log**.  
I have set skywalking.log_enable=1 and restarted php. It did't output any errors.
**### I want to know how to debug and solve this question?**
我已经设置skywalking.log_enable=1了，php重启无异常，其它的服务器上的SkyAPM-php-sdk是可以连接得上Skywalking的，这台服务器上的SkyAPM-php-sdk一周前连接上过Skywalking，昨天我把日志删除然后重启然后什么都没了，主要是 没日志没法debug

How to know the version of skywalking.so

SkyAPM-php-sdk Version:
4.0 or 4.1

ldd skywalking.so ：
![image](https://user-images.githubusercontent.com/41293784/100041708-d7e9a700-2e44-11eb-85b3-14f62ac37cee.png)

php --ri skywalking
![image](https://user-images.githubusercontent.com/41293784/100042353-3bc09f80-2e46-11eb-8047-67b2ebb83321.png)

![image](https://user-images.githubusercontent.com/41293784/100042447-6dd20180-2e46-11eb-93dc-a31b7903fcea.png)

**Comment by heyanlong** [comment]
重启一下PHP也不会有日志吗？

**Comment by garysdevil** [comment]
> 重启一下PHP也不会有日志吗？

1. 同事改了一下硬编码后，现在有日志文件了，但数据发送到skywalking 7.8.2还是失败了 
2. 客户端
![image](https://user-images.githubusercontent.com/41293784/100065416-b9000a80-2e6e-11eb-8b79-765fe525b884.png)
3. 客户端抓包 Flag F：
![image](https://user-images.githubusercontent.com/41293784/100065104-5ad32780-2e6e-11eb-822b-b7244c31b088.png)
4. skyeakling服务端报错：
![image](https://user-images.githubusercontent.com/41293784/100065041-4131e000-2e6e-11eb-8099-4a73cbe93750.png)

**Comment by heyanlong** [comment]
改硬编码是什么意思？
只能往8.x上推送

**Comment by garysdevil** [comment]
> 改硬编码是什么意思？
> 只能往8.x上推送

1. 同事改了一些这些东西后编译的。（硬编码）
![image](https://user-images.githubusercontent.com/41293784/100198829-59b9fd00-2f37-11eb-8747-53bbf9dc2eb5.png)

2.  不是通过 skywalking.version= 设置skywalking的版本吗？我用的是skywalking8.2 所以设置为8 .

3.  我本地的ubuntu虚拟机是可以推送数据上去的，这台服务器是Centos6的，不知道是不是因为系统版本原因？

4. 这台Centos6启动skywalking扩展后，skywalking服务端会报这个错。
![image](https://user-images.githubusercontent.com/41293784/100200193-34c68980-2f39-11eb-90c3-8ddca95f6f91.png)

**Comment by heyanlong** [comment]
Centos6 看着是上报异常了，可以看看skywalking-php.log信息吗？

**Comment by garysdevil** [comment]
> Centos6 看着是上报异常了，可以看看skywalking-php.log信息吗？
1. 根据抓包，客户端和服务端不断的尝试建立连接然后又结束连接。。之后学习一下whireshark再好好分析一波。。
2.. v4版本  skywalking-php.log 日志如下，并没有产生发送数据的日志，只显示connect report service
![image](https://user-images.githubusercontent.com/41293784/100301933-36915b00-2fd4-11eb-8089-c17fce943357.png)
3. 改用SkyAPM-php-sdk v3.3.2的扩展，可以往skywalking服务端发送监控数据了，但居然有一个服务崩了（垃圾业务代码），报如下错误。php扩展会对业务代码有影响？
![image](https://user-images.githubusercontent.com/41293784/100302921-4c078480-2fd6-11eb-9661-96674b364802.png)

**Comment by heyanlong** [comment]
看着是配置错误，方便的话，微信发我邮箱

**Comment by garysdevil** [comment]
garysdevil的微信号 yelangzi2015

**Comment by garysdevil** [comment]
The root cause is that we start php-fpm by '--daemonize'. Php-fpm must start by '--daemonize no' because the mechanism of SkyAPM-php-sdk v4 version
