### ISSUE TITLE
拓扑图中不显示redis主机

### ISSUE THREAD

**Issue by arthron** [SkyAPM/SkyAPM-php-sdk#315]
拓扑图中存在es  机器  数据库，唯独缺失了redis，请问是没有这个功能吗

**Comment by heyanlong** [comment]
redis客户端是什么？

**Comment by arthron** [comment]
redis  使用的aws  elasticcache服务

**Comment by heyanlong** [comment]
有这个服务的git仓库吗？

**Comment by arthron** [comment]
这个不能提供呢只有内网能访问

**Comment by arthron** [comment]
[图片]
这里缺失了redis

**Comment by arthron** [comment]
![image](https://user-images.githubusercontent.com/48424420/101314253-15aded00-3893-11eb-9102-d567dea12386.png)
拓扑图里面没有redis，其他服务能检测到

**Comment by heyanlong** [comment]
所以你这个到底是elasticcache不显示呢？还是redis不显示呢？PHP这边用的客户端是什么？

**Comment by arthron** [comment]
是reids不显示，php项目这边是用的laravel

**Comment by heyanlong** [comment]
predis？还是 phpredis？

**Comment by arthron** [comment]
phpredis

**Comment by heyanlong** [comment]
方便提供一小段代码吗？redis连接阶段，和调用阶段

**Comment by arthron** [comment]
![image](https://user-images.githubusercontent.com/48424420/101870921-87e93f00-3bbd-11eb-8086-9895f38e659f.png)
我们这边封装了，调用就一个方法

**Comment by arthron** [comment]
我们这边封装了，调用就一个方法
<img width="713" alt="0dffc819e98bf9e5f104da7109bb45c" src="https://user-images.githubusercontent.com/48424420/101870991-b1a26600-3bbd-11eb-9754-36c347cfee76.png">

**Comment by heyanlong** [comment]
这是自己 php redis connection 里面写的什么？

**Comment by arthron** [comment]
用的laravel  封装的

**Comment by heyanlong** [comment]
`connect(array $config, array $options)`

输入参数是什么？我做个本地测试。

**Comment by cfman** [comment]
@heyanlong https://github.com/phpredis/phpredis/#connection

**Comment by heyanlong** [comment]
我测试没发现问题。
