### ISSUE TITLE
How can I use span log feature?

### ISSUE THREAD

**Issue by shallowman** [SkyAPM/SkyAPM-php-sdk#320]
**Is your feature request related to a problem? Please describe.**
Logs may be useful for documenting a specific moment or event within the span (in contrast to tags which should apply to the span regardless of time). In open traning span interface features should support a log event to span.
**Describe the solution you'd like**
Implement a PHP_FUNCTION that can support add a log event to span.
**Describe alternatives you've considered**
Implement a composer package wrote by php so that require by business logics.

**Additional context**
![open-tracing-span-log](https://i.loli.net/2020/12/15/1gpKDbEjIOoh8Qu.png)

**Comment by heyanlong** [comment]
Great idea, but this would be invasive to the code, and I'm considering how to implement it

**Comment by heyanlong** [comment]
#323

**Comment by heyanlong** [comment]
```php
function testAddLog(){
    $key = "info";
    $log = "test skywalking_log funciton, the third parameter [is_error] default is false.";
    skywalking_log(__METHOD__, $key, $log);
    skywalking_log(__METHOD__, $key, $log, 1);
}
```

**Comment by wu-sheng** [comment]
@heyanlong SkyWalking has a real log collecting feature now. Please consider taking a look at http://skywalking.apache.org/docs/main/v8.5.0/en/setup/service-agent/java-agent/application-toolkit-log4j-1.x/#grpc-reporter. We should ship the logs through the gRPC directly with trace context(trace_id, segment_id, span_id)
