### ISSUE TITLE
After configuration of SkyAPM-php sdk 4.1.1, how to start it and get data flow to collector

### ISSUE THREAD

**Issue by rohan2546** [SkyAPM/SkyAPM-php-sdk#327]
**Expected behavior**
Expect for creation of sky-php-agent bin file which can be used to send data to collector as it was the case in SkyAPM-php 3.1.1, there is no such creation of bin file so how to transfer data to collector

Using: Skywalking v8 as collector

**Comment by renhui801** [comment]
![image](https://user-images.githubusercontent.com/25736095/103389454-d39e6100-4b49-11eb-97fe-60a8926161d5.png)
