### ISSUE TITLE
mysqli,curl无法追踪

### ISSUE THREAD

**Issue by renhui801** [SkyAPM/SkyAPM-php-sdk#328]
**Describe the bug**
测试过mysqli,pdo_mysql,redis,curl。发现mysqli,curl无法追踪,pdo,redis可以追踪。

**PHP (please complete the following information):**
 - OS: [Centos7]
 - PHP 7.1.33
 - 

**SkyWalking (please complete the following information):**
 - OS: [Centos]
 - Version [docker(skywalking-oap-server:latest-es7)]
 - SkyAPM-php-sdk version-4.1.1

**Comment by heyanlong** [comment]
提供一个不可追踪的例子吧

**Comment by renhui801** [comment]
> 提供一个不可追踪的例子吧
仅仅是一个测试。
`$c = curl_init();
curl_setopt($c,CURLOPT_URL,'www.baidu.com');
curl_exec($c);
curl_close($c);`

skywalking-ui显示
![image](https://user-images.githubusercontent.com/25736095/103495139-b41e7580-4e74-11eb-809d-78b0d19f522a.png)

skywalking-php.log

{"traceId":"0b2bae01c57508ffec1be2dfdb848f24.24278.1104162638","traceSegmentId":"0b2bae01c57508ffec1be2dfdb848f24.24278.1104162638","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1609725643792","endTime":"1609725643883","refs":[],"operationName":"/test.php","peer":"crm-end.yb.com:80","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/test.php"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"yibai_crm","serviceInstance":"b9702c25-f879-770b-d931-6e15202f7484@192.168.14.238","isSizeLimited":false}

**Comment by heyanlong** [comment]
由于curl支持很多协议，所以必须有http或者https开头才可以追踪

**Comment by renhui801** [comment]
> 由于curl支持很多协议，所以必须有http或者https开头才可以追踪

添加http后确实可以追踪。4.1.1是否支持mysqli追踪，测试无法追踪
`$m = new mysqli('127.0.0.1','test','test','yibai_crm');
$res = $m->query('select * from yibai_user limit 10');`

![Uploading image.png…]()

skywalking-php.log

{"traceId":"159ddc575be356ae50b779f5bab54cfd.488.3925242651","traceSegmentId":"159ddc575be356ae50b779f5bab54cfd.488.3925242651","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1609838530168","endTime":"1609838530285","refs":[],"operationName":"/test.php","peer":"crm-end.yb.com:80","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/test.php"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"yibai_crm","serviceInstance":"adf6caef-a4d7-966f-a0fd-7fed8b1972fc@192.168.14.238","isSizeLimited":false}

**Comment by heyanlong** [comment]
https://github.com/SkyAPM/SkyAPM-php-sdk/pull/323
正在开发。
