### ISSUE TITLE
install php extension error

### ISSUE THREAD

**Issue by skindx** [SkyAPM/SkyAPM-php-sdk#329]
On Ubuntu18, I installed grpc and protobuf success already, but when I install php extension of skywalking, it's wrong... How can I fix it.
PHP version: PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )
I want install it from source and try pecl install skywalking,the same wrong.

Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
root@ubuntu:/home/SkyAPM-php-sdk# ./configure --with-php-config=/usr/bin/php-config7.2
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20170718
checking for PHP installed headers prefix... /usr/include/php/20170718
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether to enable skywalking support... yes, shared
checking whether C++ compiler accepts -std=c++0x... yes
checking for php_json.h... found in /usr/include/php/20170718
checking for grpc and protobuf files in default path... found in /usr/local
found in /usr/local
found in /usr
checking for gpr_now in -lgpr... no
configure: error: wrong gpr lib version or lib not found

**Comment by heyanlong** [comment]
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/install.md
