### ISSUE TITLE
4.1.1拓展安装成功后，skywalking服务接收不到追踪信息

### ISSUE THREAD

**Issue by liubin0730** [SkyAPM/SkyAPM-php-sdk#334]
grpc pro都安装成功，php拓展也已经安装成功，完全按照官方的文档来。在3.2版本需要启动report client上报服务，4.1.1官方文档没有写要启动report client，我切换到3.2版本启动上报服务是可以上报信息，说明我的grpc环境没有问题。切换到4.1.1版本，不启动上报服务，就收集不到信息，也没有报错，日志文件只显示 `the apache skywalking php plugin mounted
connect report service` ，除此之外没有其他信息。

**Comment by liubin0730** [comment]
因为我是swoole项目，所以必须用4.1的版本。

**Comment by heyanlong** [comment]
4.1不需要report client

**Comment by liubin0730** [comment]
@heyanlong 那能给我方向 我的问题可能出在哪吗

**Comment by liubin0730** [comment]
@heyanlong 日志里面只有这个
[root@xm-dev-php skywalking-4.1.1]# tail -f /tmp/skywalking-php.log
connect report service
the apache skywalking php plugin mounted
the apache skywalking php plugin mounted
connect report service

**Comment by liubin0730** [comment]
@heyanlong 日志里面只有这个
[root@kl skywalking-4.1.1]# tail -f /tmp/skywalking-php.log
connect report service
the apache skywalking php plugin mounted
the apache skywalking php plugin mounted
connect report service

**Comment by liubin0730** [comment]
@heyanlong 大佬帮解答下啊

**Comment by heyanlong** [comment]
php-fpm 需要前台运行。

**Comment by liubin0730** [comment]
@heyanlong  前台后台我都试过了
[root@sj etc]# /soft/php7.4.1/sbin/php-fpm -c /soft/php7.4.1/etc/php.ini -y /soft/php7.4.1/etc/php-fpm.conf -F
[26-Jan-2021 11:23:20] NOTICE: fpm is running, pid 13843
[26-Jan-2021 11:23:20] NOTICE: ready to handle connections

**Comment by liubin0730** [comment]
@heyanlong fpm的不行 swoole的也不行

**Comment by liubin0730** [comment]
@heyanlong php.ini信息
[root@sj skywalking-4.1.1]# /soft/php7.4.1/bin/php --ri skywalking

skywalking

Directive => Local Value => Master Value
skywalking.enable => On => On
skywalking.version => 8 => 8
skywalking.app_code => php-service-dev => php-service-dev
skywalking.authentication => no value => no value
skywalking.grpc => 192.168.58.186:11800 => 192.168.58.186:11800
skywalking.grpc_tls_enable => 0 => 0
skywalking.grpc_tls_pem_root_certs => no value => no value
skywalking.grpc_tls_pem_private_key => no value => no value
skywalking.grpc_tls_pem_cert_chain => no value => no value
skywalking.log_enable => 1 => 1
skywalking.log_path => /tmp/skywalking-php.log => /tmp/skywalking-php.log

**Comment by liubin0730** [comment]
@heyanlong grpc的测试 没问题
[root@sj helloworld]# ./greeter_server 
Server listening on 0.0.0.0:50051

**Comment by liubin0730** [comment]
@heyanlong 能再帮看看吗

**Comment by liubin0730** [comment]
@heyanlong 支持swoft吗 ？？我看文档单独写了Hyperf

**Comment by heyanlong** [comment]
swoft我还没测试过。

**Comment by heyanlong** [comment]
有需求的话可以单独开一个issue

**Comment by liubin0730** [comment]
@heyanlong 我试过不行，hyperf是可以的。能开一个最好了我们要接入swoft  感谢。再就是上面4.11版本不行，设为bug了，是不是有修改还是就是我环境的问题？切换到fix-swoole版本将manager.cc这个文件的
```
while (tempAddress != nullptr) {
  ...
}
```
改为：
```
while (tempAddress != nullptr && tempAddress->ifa_addr != nullptr) {
  ...
}
``` 
之后。原生swoole与hyperf可以用了，fpm还是不行的。4.11版本依然是fpm与swoole都不行

**Comment by heyanlong** [comment]
嗯，swoole是有点问题，正在fix-swoole分支修

**Comment by Arealm** [comment]
自己没搞定非要说这是bug

**Comment by heyanlong** [comment]
@Arealm 别激动，别激动

**Comment by liubin0730** [comment]
@heyanlong 修好了麻烦通知下哈

**Comment by hkui** [comment]
> 自己没搞定非要说这是bug

你试过吗，我遇到的问题和这一样的，作者都说是bug了，你那没问题吗

**Comment by zouwenjian** [comment]
> @heyanlong fpm的不行 swoole的也不行

楼主，我的也是一样的问题，4.1.1 版收集不到数据，目前用了3.2版
