### ISSUE TITLE
请求yaf，再中转请求yar，链路无法形成

### ISSUE THREAD

**Issue by ZHBlue5** [SkyAPM/SkyAPM-php-sdk#338]
请求yaf，再去请求yar服务，链路无法形成，这个还需要怎么配置？

**Comment by heyanlong** [comment]
再去请求的时候，代码发一下。

**Comment by ZHBlue5** [comment]
目前的使用场景是php是yar的server端，yaf是client端。
Php yar的配置：

使用了custom header功能
使用的是msgpack_pack编码格式
最新版的yar客户端
To Reproduce
yar请求yar，traceId放在yar的header中？

**Comment by heyanlong** [comment]
#341

**Comment by heyanlong** [comment]
#396
