### ISSUE TITLE
grpc 的微服务链路串不起来

### ISSUE THREAD

**Issue by klboke** [SkyAPM/SkyAPM-php-sdk#339]
目前测试 php 到 java 微服务，grpc 的微服务链路串不起来，是本身功能不完整么？

**Comment by zhaodp** [comment]
这个什么时候能解决啊

**Comment by zhaodp** [comment]
请问大神，这个问题什么时候能解决啊

**Comment by heyanlong** [comment]
预计在summer 2021中期评审完成后。

**Comment by zhaodp** [comment]
> 预计在summer 2021中期评审完成后。

大概在几月份？

**Comment by heyanlong** [comment]
本月

**Comment by heyanlong** [comment]
已经合并到master

**Comment by zhaodp** [comment]
已经用master代码重新编译了，之前我那个串不起来的问题，貌似是因为有个服务报错了，和这个问题没关系：
TracingContext : More than 300 spans required to create
是Java服务的的agent问题，我试试最新版的agent

**Comment by heyanlong** [comment]
@zhaodp 测试了吗？

**Comment by zhaodp** [comment]
之前可能是我配置问题，现在java + php  服务 互相调用，很完美得串起来了 ，哈哈
