### ISSUE TITLE
Yar的traceId是存放在什么位置？

### ISSUE THREAD

**Issue by yoster0520** [SkyAPM/SkyAPM-php-sdk#341]
**Describe the bug**
我们公司自己使用Java实现了yar的协议。目前的使用场景是php是yar的server端，java是client端。 
Php yar的配置：
* 使用了custom header功能
* 使用的是php编码格式
* 最新版的yar客户端 

**To Reproduce**
java请求php，traceId放在yar的header中？

**Comment by heyanlong** [comment]
目前新版本已移除了yar的支持，如果需要可以添加

**Comment by yoster0520** [comment]
@heyanlong 为什么要移除呢？出于性能考虑吗？不行就加上吧

**Comment by heyanlong** [comment]
是重构的时候工作量太大，就先去掉了。

**Comment by yoster0520** [comment]
好吧，暂时用不上了，我们打算把yar换成纯的http了

**Comment by ZHBlue5** [comment]
@heyanlong 是否可以添加上？

**Comment by heyanlong** [comment]
会添加，请各位放心。

**Comment by heyanlong** [comment]
#396

**Comment by heyanlong** [comment]
#396
