### ISSUE TITLE
只启动PHP Swoole不启动PHP FPM服务端收不到数据

### ISSUE THREAD

**Issue by Cuigeek** [SkyAPM/SkyAPM-php-sdk#342]
SkyAPM-php-sdk-4.1.0版本
PHP 7.3.23版本
CentOS Linux release 7.9.2009 (Core)

请问不启动PHP-FPM，只是用PHP Swoole是否可以使用这个SDK正常收集数据？
使用pm2管理的进程，配置文件如下：
cat swoole-worker.yml 
apps:
  - name: swoole-worker
    script: artisan
    exec_mode: fork
    interpreter: php
    max-memory-restart: 300M
    instances: 1
    args:
      - swoole:http
      - start

**Comment by heyanlong** [comment]
swoole的话，建议在4.1.2发布之前，先用master，修复了一些swoole模式下的错误，

**Comment by heyanlong** [comment]
4.1.3 or newer version
