### ISSUE TITLE
curl 无论get或post 502

### ISSUE THREAD

**Issue by srunze** [SkyAPM/SkyAPM-php-sdk#343]
WARNING: [pool www] child 4463 exited on signal 11 (SIGSEGV - core dumped) after 3.318083 seconds from start

- php7.4.14
- 扩展 SkyAPM-php-sdk-4.1.1

```
[skywalking]
extension=skywalking.so
skywalking.app_code = myDefaultSkyWalking-ubuntu-02
skywalking.enable = 1
skywalking.version = 8
skywalking.grpc = 172.16.143.2:11800
```

1. CLI模式下正常
2. fpm下502，--nodaemonize终端进程返回上述错误 (取消skywalking扩展可正常）
3. 这个fpm只能是--nodaemonize模式运行吗，这样的话启动无法退出生产环境不好管理呢

**Comment by srunze** [comment]
额 发现了问题原因
1. a.com
2. b.com

访问http://a.com
代码再次curl('http://b.com') 502,  因为域名后面必须有路径存在仅有参数也不行。
curl('http://b.com/xxx')  如此问题解决，不知道算是问题吗。

再者想问下php-fpm后台运行怎么启动呢？systemctl中php-fpm --nodaemonize进程无法中断。nohup倒是可以但不好管理

**Comment by hkui** [comment]
> 额 发现了问题原因
> 
> 1. a.com
> 2. b.com
> 
> 访问http://a.com
> 代码再次curl('http://b.com') 502, 因为域名后面必须有路径存在仅有参数也不行。
> curl('http://b.com/xxx') 如此问题解决，不知道算是问题吗。
> 
> 再者想问下php-fpm后台运行怎么启动呢？systemctl中php-fpm --nodaemonize进程无法中断。nohup倒是可以但不好管理

可以使用system管理
vim /usr/lib/systemd/system/php-fpm.service

```
[Unit]
Description=The PHP FastCGI Process Manager
After=syslog.target network.target

[Service]
Type=simple
PIDFile=/usr/server/php7/log/php-fpm.pid
ExecStart=/usr/server/php7/sbin/php-fpm  --nodaemonize -y /usr/server/php7/etc/php-fpm.conf
ExecReload=/bin/kill -USR2 $MAINPID
ExecStop=/bin/kill -INT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

**Comment by heyanlong** [comment]
@hkui 和systemd没关系。

**Comment by heyanlong** [comment]
#310 已修复此bug

**Comment by bain2018** [comment]
貌似用最新版，没有解决这个问题啊
php:7.4
macos 11.4
已安装扩展
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zlib

**Comment by heyanlong** [comment]
@bain2018 发一下相关配置和测试demo
