### ISSUE TITLE
Segmentation fault when loading php-fpm with skywalking.so

### ISSUE THREAD

**Issue by dv-morais** [SkyAPM/SkyAPM-php-sdk#345]
**Describe the bug**
I'm faced with the error "Segmentation fault (core dumped)" when I try to execute the php-fpm with the extension "skywalking.so" activated

**To Reproduce**

Run php-fpm while the extension skywalking.so is activated

CentOS: 8.1
PHP: 7.4.15
Apache: 2.4.46
Skywalking: 8.2

**Comment by heyanlong** [comment]
A very good question, but I have to remind you that this is skywalking

**Comment by dv-morais** [comment]
OOps... I just wrote it wrong... but it is really skywalking.so... sorry for the typo, edited my initial comment too

![image](https://user-images.githubusercontent.com/57958197/109813550-47252300-7c0c-11eb-83f1-4735c421ea03.png)

![image](https://user-images.githubusercontent.com/57958197/109814037-d2061d80-7c0c-11eb-8a74-01158c1c80dc.png)

**Comment by heyanlong** [comment]
retry 4.1.2
