### ISSUE TITLE
Compile Fatal Error: absl/synchronization/mutex.h: No such file or directory

### ISSUE THREAD

**Issue by duangg** [SkyAPM/SkyAPM-php-sdk#348]
**Describe the bug**
Fatal error while compiling

**To Reproduce**

docker run --name php_sw_3 -it centos:7 bash

 **install build tools**
yum install -y build-essential autoconf automake libtool curl make  unzip pkg-config openssl-devel libcurl-dev

**yum install gcc 8**
yum install -y centos-release-scl
yum install -y  scl-utils devtoolset-8-gcc devtoolset-8-gcc-c++ scl-utils
scl enable devtoolset-8 -- bash

 **install openssl**

 **install cmake, https://cmake.org/install/, version 3.19.6**
 ./bootstrap
  make
  make install

**install PHP**

yum install -y epel-release yum-utils
yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm

yum-config-manager --enable remi-php71
yum install -y php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql php-fpm php-devel
yum install -y zip unzip git nginx 

**install Protobuf**

git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git submodule update --init --recursive
./autogen.sh

./configure
make -j$(nproc)
make check
sudo make install
sudo ldconfig # refresh shared library cache.

**install gRPC**
git clone https://github.com/grpc/grpc.git
cd grpc
git submodule update --init --recursive

mkdir -p cmake/build
cd cmake/build
cmake ../.. -DBUILD_SHARED_LIBS=ON -DgRPC_INSTALL=ON
make -j$(nproc)
sudo make install
make clean
sudo ldconfig

 **install skywalking**
curl -Lo v4.1.1.tar.gz https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v4.1.1.tar.gz
tar zxvf v4.1.1.tar.gz
cd SkyAPM-php-sdk-4.1.1
phpize && ./configure && make && make install

**Expected behavior**
Compile complete
**Screenshots**
![image](https://user-images.githubusercontent.com/12563218/111412811-179c0d80-8718-11eb-8b54-65c06204ce9d.png)

**PHP (please complete the following information):**
 - OS: Centos 7
 - Browser Edge
 - Version 7.1.31
 - php-fpm -i

[php.ini.txt](https://github.com/SkyAPM/SkyAPM-php-sdk/files/6153671/php.ini.txt)

**SkyWalking (please complete the following information):**
 - OS: Centos 7
 - Browser Edge
 - Version  4.1.1

**Additional context**

**Comment by heyanlong** [comment]
https://github.com/grpc/grpc/issues/24143

**Comment by heyanlong** [comment]
What is the abseil version?

**Comment by duangg** [comment]
> What is the abseil version?

I have fixed this problem by modify some Enviroment Variables. Please close this issue

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib64
> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
