### ISSUE TITLE
请问是少依赖包么？具体是哪个 请指教

### ISSUE THREAD

**Issue by vallbuy** [SkyAPM/SkyAPM-php-sdk#352]
pecl install skywalking 

In file included from /tmp/pear/temp/skywalking/skywalking.cc:23:
/tmp/pear/temp/skywalking/src/segment.h:23:10: fatal error: src/network/v3/language-agent/Tracing.pb.h: No such file or directory
   23 | #include <src/network/v3/language-agent/Tracing.pb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1
ERROR: `make' failed

**Comment by bostin** [comment]
参考 https://github.com/SkyAPM/SkyAPM-php-sdk/tree/master/docker 对应的php版本，检查下依赖库

我怀疑是protobuf/grpc缺失

**Comment by vallbuy** [comment]
您好：
RUN set -ex \
	&amp;&amp; apk add --update --no-cache autoconf make g++ pkgconfig git openssl curl-dev protobuf-dev protobuf grpc-dev grpc re2c\


&nbsp; &nbsp; # installing skywalking
	&amp;&amp; pecl install skywalking \
	&amp;&amp; docker-php-ext-enable skywalking \

里面已经安装了protobuf/grpc


config.status: creating config.h
running: make
/bin/sh /tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/include -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/src -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/src/network/v3&nbsp; -DHAVE_CONFIG_H&nbsp; -g -O2 -Wall -std=c++11 -Wno-deprecated-register&nbsp; &nbsp;-c /tmp/pear/temp/skywalking/skywalking.cc -o skywalking.lo
mkdir .libs
&nbsp;g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/include -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/src -I/tmp/pear/temp/pear-build-defaultuserNclBFd/skywalking-4.1.1/src/network/v3 -DHAVE_CONFIG_H -g -O2 -Wall -std=c++11 -Wno-deprecated-register -c /tmp/pear/temp/skywalking/skywalking.cc&nbsp; -fPIC -DPIC -o .libs/skywalking.o
In file included from /tmp/pear/temp/skywalking/skywalking.cc:23:
/tmp/pear/temp/skywalking/src/segment.h:23:10: fatal error: src/network/v3/language-agent/Tracing.pb.h: No such file or directory
&nbsp; &nbsp;23 | #include <src/network/v3/language-agent/Tracing.pb.h&gt;
&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1
ERROR: `make' failed







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
参考 https://github.com/SkyAPM/SkyAPM-php-sdk/tree/master/docker 对应的php版本，检查下依赖库
 
我怀疑是protobuf/grpc缺失

**Comment by heyanlong** [comment]
是否存在protoc 命令？

**Comment by vallbuy** [comment]
有这个命令
/var/www/html # protoc
Usage: protoc [OPTION] PROTO_FILES
Parse PROTO_FILES and generate output based on the options given:
&nbsp; -IPATH, --proto_path=PATH&nbsp; &nbsp;Specify the directory in which to search for
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; imports.&nbsp; May be specified multiple times;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; directories will be searched in order.&nbsp; If not
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; given, the current working directory is used.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; If not found in any of the these directories,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; the --descriptor_set_in descriptors will be
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; checked for required proto file.
&nbsp; --version&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Show version info and exit.
&nbsp; -h, --help&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Show this text and exit.
&nbsp; --encode=MESSAGE_TYPE&nbsp; &nbsp; &nbsp; &nbsp;Read a text-format message of the given type







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
是否存在protoc 命令？

**Comment by vallbuy** [comment]
&nbsp;/etc/apk/repositories
https://mirrors.ustc.edu.cn/alpine/edge/main
https://mirrors.ustc.edu.cn/alpine/edge/community
https://mirrors.ustc.edu.cn/alpine/edge/testing

时
checking for php_json.h... found in /usr/local/include/php
checking for grpc and protobuf files in default path... found in /usr
found in /usr
checking for gpr_now in -lgpr... no
configure: error: wrong gpr lib version or lib not found
ERROR: `/tmp/pear/temp/skywalking/configure --with-php-config=/usr/local/bin/php-config' failed



&nbsp;/etc/apk/repositories
https://mirrors.ustc.edu.cn/alpine/v3.12/main
https://mirrors.ustc.edu.cn/alpine/v3.12/community
https://mirrors.ustc.edu.cn/alpine/v3.12/testing


时

running: make
/bin/sh /tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/include -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/src -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/src/network/v3&nbsp; -DHAVE_CONFIG_H&nbsp; -g -O2 -Wall -std=c++11 -Wno-deprecated-register&nbsp; &nbsp;-c /tmp/pear/temp/skywalking/skywalking.cc -o skywalking.lo
mkdir .libs
&nbsp;g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/include -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/src -I/tmp/pear/temp/pear-build-defaultuserMNDJjJ/skywalking-4.1.1/src/network/v3 -DHAVE_CONFIG_H -g -O2 -Wall -std=c++11 -Wno-deprecated-register -c /tmp/pear/temp/skywalking/skywalking.cc&nbsp; -fPIC -DPIC -o .libs/skywalking.o
In file included from /tmp/pear/temp/skywalking/skywalking.cc:23:
/tmp/pear/temp/skywalking/src/segment.h:23:10: fatal error: src/network/v3/language-agent/Tracing.pb.h: No such file or directory
&nbsp; &nbsp;23 | #include <src/network/v3/language-agent/Tracing.pb.h&gt;
&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1
ERROR: `make' failed

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
是否存在protoc 命令？

**Comment by vallbuy** [comment]
又加了一个包gprbuild后&nbsp;显示这个的错误
+ apk add --update --no-cache autoconf make g++ pkgconfig git openssl curl-dev protobuf-dev protobuf grpc-dev grpc re2c gprbuild
fetch https://mirrors.ustc.edu.cn/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
&nbsp; so:libgnarl-9.so (no such package):
&nbsp; &nbsp; required by: gprbuild-2019-r0[so:libgnarl-9.so]
&nbsp; so:libgnat-9.so (no such package):
&nbsp; &nbsp; required by: gprbuild-2019-r0[so:libgnat-9.so]



通过以上命令得到的是:
/var/www/html # apk search libgnarl
libgnat-10.2.1_git20210328-r0

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
是否存在protoc 命令？

**Comment by vallbuy** [comment]
您好：
请问，这个gpr是需要引入哪个类包？
checking for gpr_now in -lgpr... no
configure: error: wrong gpr lib version or lib not found
ERROR: `/tmp/pear/temp/skywalking/configure --with-php-config=/usr/local/bin/php-config' failed




https://github.com/SkyAPM/SkyAPM-php-sdk/blob/d8e044d972f64700bd2d23285a746b35fa8b5213/config.m4




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
是否存在protoc 命令？

**Comment by heyanlong** [comment]
configure没有通过的情况下，不要make

**Comment by heyanlong** [comment]
gpr 来自gRPC

**Comment by vallbuy** [comment]
您好：
pecl install skywalking


running: make
/bin/sh /tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/include -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/src -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/src/network/v3&nbsp; -DHAVE_CONFIG_H&nbsp; -g -O2 -Wall -std=c++11 -Wno-deprecated-register&nbsp; &nbsp;-c /tmp/pear/temp/skywalking/skywalking.cc -o skywalking.lo
mkdir .libs
&nbsp;g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/include -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/src -I/tmp/pear/temp/pear-build-defaultusernIjiND/skywalking-4.1.1/src/network/v3 -DHAVE_CONFIG_H -g -O2 -Wall -std=c++11 -Wno-deprecated-register -c /tmp/pear/temp/skywalking/skywalking.cc&nbsp; -fPIC -DPIC -o .libs/skywalking.o
In file included from /tmp/pear/temp/skywalking/skywalking.cc:23:
/tmp/pear/temp/skywalking/src/segment.h:23:10: fatal error: src/network/v3/language-agent/Tracing.pb.h: No such file or directory
&nbsp; &nbsp;23 | #include <src/network/v3/language-agent/Tracing.pb.h&gt;
&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1
ERROR: `make' failed



请问一下，这个错误是什么问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
gpr 来自gRPC

**Comment by bostin** [comment]
@vallbuy 你是机器人么
😲

**Comment by vallbuy** [comment]
不是，我这有错误



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月8日(周四) 下午4:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)




 
@vallbuy 你是机器人么
 😲

**Comment by bostin** [comment]
有完整的dockerfile吗？

**Comment by vallbuy** [comment]
您好：这是dockerfile




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
有完整的dockerfile吗？

**Comment by heyanlong** [comment]
哪Dockerfile呢？

**Comment by vallbuy** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
哪Dockerfile呢？

**Comment by vallbuy** [comment]
您好&nbsp;在附件里面




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
哪Dockerfile呢？

**Comment by heyanlong** [comment]
请来这里讨论
https://github.com/SkyAPM/SkyAPM-php-sdk/issues/352

**Comment by heyanlong** [comment]
你用邮件回复不会自带附件。

**Comment by vallbuy** [comment]
FROM php:7.3-fpm-alpine

#复制源
COPY ./repositories /etc/apk/repositories

RUN set -ex \
	&& apk add --update --no-cache autoconf g++ protobuf-dev grpc-dev curl-dev make re2c\

    # installing skywalking
	&& pecl install skywalking \
	&& docker-php-ext-enable skywalking

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

EXPOSE 9000

CMD ["php-fpm"]

repositories的内容
https://mirrors.ustc.edu.cn/alpine/v3.11/main
https://mirrors.ustc.edu.cn/alpine/v3.11/community

**Comment by heyanlong** [comment]
请参考这个
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docker/Dockerfile.7.3

**Comment by vallbuy** [comment]
好的，主要是github慢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
请参考这个
 https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docker/Dockerfile.7.3

**Comment by heyanlong** [comment]
docker pull skyapm/skywalking-php-7.3-fpm-alpine:latest

**Comment by vallbuy** [comment]
好的&nbsp;谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 请问是少依赖包么？具体是哪个 请指教 (#352)





 
docker pull skyapm/skywalking-php-7.3-fpm-alpine:latest
