### ISSUE TITLE
\GuzzleHttp\Client() 502

### ISSUE THREAD

**Issue by vallbuy** [SkyAPM/SkyAPM-php-sdk#357]
在未开启skywalking-oap-server时，
(new \GuzzleHttp\Client())->request('post', 'http://www.baidu.com')
是可以正常返回
开启后，nginx502错误，
recv() failed (104: Connection reset by peer) while reading response header from upstream，
在查看GuzzleHttp\Client->request 代码时
/**
     * Create and send an HTTP request.
     *
     * Use an absolute path to override the base path of the client, or a
     * relative path to append to the base path of the client. The URL can
     * contain the query string as well.
     *
     * @param string              $method  HTTP method.
     * @param string|UriInterface $uri     URI object or string.
     * @param array               $options Request options to apply. See \GuzzleHttp\RequestOptions.
     *
     * @return ResponseInterface
     * @throws GuzzleException
     */
    public function request($method, $uri = '', array $options = [])
    {
        $options[RequestOptions::SYNCHRONOUS] = true;
        return $this->requestAsync($method, $uri, $options)->wait();
    }

注释
//$options[RequestOptions::SYNCHRONOUS] = true;
即可以有正常返回内容！
请问如何处理。

**Comment by vallbuy** [comment]
php --ri skywalking
Directive => Local Value => Master Value
skywalking.enable => On => On
skywalking.version => 8 => 8
skywalking.app_code => live => live
skywalking.authentication => no value => no value
skywalking.grpc => 172.16.64.95:11800 => 172.16.64.95:11800
skywalking.grpc_tls_enable => 0 => 0
skywalking.grpc_tls_pem_root_certs => no value => no value
skywalking.grpc_tls_pem_private_key => no value => no value
skywalking.grpc_tls_pem_cert_chain => no value => no value
skywalking.log_enable => 1 => 1
skywalking.log_path => /phplogs/skywalking-php.log => /phplogs/skywalking-php.log

/var/www/html # php -v
PHP 7.3.27 (cli) (built: Mar 26 2021 00:19:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies

**Comment by heyanlong** [comment]
使用的版本是什么？

**Comment by vallbuy** [comment]
skywalking v4.1.1

**Comment by vallbuy** [comment]
我查到问题了，在不开启skywalking时，curl_getinfo()里面的url会自动给域名说加一个 “/”,http://www.baidu.com成为 http://www.baidu.com/，但在开启了skywalking时，就502，如果这时我给请求的http://www.baidu.com加上”/“后再请求就可以了，应该是在curl拦截处理时，要默认把"/"做处理就可以了

**Comment by vallbuy** [comment]
这个"/"的处理应该和curl的扩展用法保持一致！

**Comment by heyanlong** [comment]
master已修复此问题
