### ISSUE TITLE
开启workerman后，无追踪日志

### ISSUE THREAD

**Issue by hyper-self** [SkyAPM/SkyAPM-php-sdk#358]
在启动workderman php start.php start -d后无追踪日志
如果是调试模式是有追踪日志

/www/live/src/lv-socket # php -v
PHP 7.3.27 (cli) (built: Mar 26 2021 00:19:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies

skywalking版本 master
/www/live/src/lv-socket # php --ri skywalking

skywalking

Directive => Local Value => Master Value
skywalking.enable => On => On
skywalking.version => 8 => 8
skywalking.app_code => live => live
skywalking.authentication => no value => no value
skywalking.grpc => 172.16.64.95:11800 => 172.16.64.95:11800
skywalking.grpc_tls_enable => Off => Off
skywalking.grpc_tls_pem_root_certs => no value => no value
skywalking.grpc_tls_pem_private_key => no value => no value
skywalking.grpc_tls_pem_cert_chain => no value => no value
skywalking.log_enable => On => On
skywalking.log_path => /phplogs/skywalking-php.log => /phplogs/skywalking-php.log
skywalking.error_handler_enable => Off => Off
skywalking.mq_max_message_length => 20480 => 20480

**Comment by heyanlong** [comment]
调试模式是什么workerman？

**Comment by vallbuy** [comment]
workwrman 是提供socket 服务的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月22日(周四) 上午10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SkyAPM/SkyAPM-php-sdk] 开启workerman后，无追踪日志 (#358)




 
调试模式是什么workerman？

**Comment by heyanlong** [comment]
求一个例子

**Comment by vallbuy** [comment]
链接：https://pan.baidu.com/s/1eynAWno2f8orIUPxiug1yQ 
提取码：ztsi 
详细见readme
