### ISSUE TITLE
安装php extenstion失败  possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by zt3862266** [SkyAPM/SkyAPM-php-sdk#364]
**Describe the bug**
安装SK php 扩展的过程中，有如下报错 .在网上找了各种解决方案，均无法解决问题，以下是我环境中各类版本信息

[rong@dx-dev-test1051 SkyAPM-php-sdk-4.1.1]$ cat  /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[rong@dx-dev-test1051 SkyAPM-php-sdk-4.1.1]$ php -v
PHP 7.0.11 (cli) (built: Oct 17 2016 20:55:39) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11, Copyright (c) 1999-2016, by Zend Technologies
[rong@dx-dev-test1051 SkyAPM-php-sdk-4.1.1]$ gcc --version
gcc (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[rong@dx-dev-test1051 SkyAPM-php-sdk-4.1.1]$ cmake --version
cmake version 3.20.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[rong@dx-dev-test1051 SkyAPM-php-sdk-4.1.1]$ phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
configure.in:50: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Expected behavior**
可以顺利安装 php 扩展

**PHP (please complete the following information):**
 - OS: Centos 7.4
 - Version PHP 7.0.11

**Comment by heyanlong** [comment]
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.

**Comment by zt3862266** [comment]
> If this token and others are legitimate, please use m4_pattern_allow.
> See the Autoconf documentation.

这个是输出的错误日志。
具体应该怎么操作呢？我google了很多文章，都没有解决这个问题。是不是还有一些别的环境或者依赖？

**Comment by heyanlong** [comment]
应该是autoconf坏了，需要修一下

**Comment by zt3862266** [comment]
> 应该是autoconf坏了，需要修一下

我尝试了各种方法，均没有效果
最后的解决方案是，修改了 php 扩展中的 config.m4 文件,把下面这一行删掉，就可以顺利编译安装了
AX_CHECK_COMPILE_FLAG([-std=c++0x], , [AC_MSG_ERROR([compiler not accept c++11])])


不过安装成功之后还是有以下问题：
1.SW ui 没有 trace日志
2.php-fpm有 内核报错

Apr 28 10:37:30 dx-dev-test1051 kernel: traps: php-fpm[32647] general protection ip:6ebcc3 sp:7ffeeb73fa88 error:0 in php-fpm[400000+665000]
Apr 28 10:38:10 dx-dev-test1051 kernel: traps: php-fpm[32696] general protection ip:6ebcc3 sp:7ffeeb73fa88 error:0 in php-fpm[400000+665000]
Apr 28 10:49:32 dx-dev-test1051 kernel: traps: php-fpm[856] general protection ip:6ebcc3 sp:7ffdcb2c8228 error:0 in php-fpm[400000+665000]
Apr 28 10:54:24 dx-dev-test1051 kernel: traps: php-fpm[918] general protection ip:6ebcc3 sp:7ffdcb2c7e58 error:0 in php-fpm[400000+665000]
Apr 28 10:55:00 dx-dev-test1051 kernel: traps: php-fpm[1170] general protection ip:6ebcc3 sp:7ffdcb2c7e58 error:0 in php-fpm[400000+665000]
Apr 28 10:56:46 dx-dev-test1051 kernel: traps: php-fpm[1297] general protection ip:6ebcc3 sp:7ffdcb2c8228 error:0 in php-fpm[400000+665000]


不知道有没有解决思路？

**Comment by heyanlong** [comment]
把那一行加回去。。
