### ISSUE TITLE
Working  together with java agent?

### ISSUE THREAD

**Issue by mbao** [SkyAPM/SkyAPM-php-sdk#37]
Say I have project A writing in PHP, and project B writing in JAVA, A call B via curl, both A AND B use skywalking,  but in Topology they are not connected  and  in Traces they are not work together.

**Comment by wu-sheng** [comment]
One possible issue, which version of header is uesed? Java agent has already moved to v2 header by default, you could find how to active v1 header.  @heyanlong which version of PHP SDK is using?

**Comment by mbao** [comment]
> One possible issue, which version of header is uesed? Java agent has already moved to v2 header by default, you could find how to active v1 header. @heyanlong which version of PHP SDK is using?

See some sw3 in php agent source code, but I am not familiar with php extension, will try  v1 header. Thanks.

**Comment by wu-sheng** [comment]
sw3 is v1 header.

**Comment by mbao** [comment]
> One possible issue, which version of header is uesed? Java agent has already moved to v2 header by default, you could find how to active v1 header. @heyanlong which version of PHP SDK is using?

Using v1 header works. Thanks.
