### ISSUE TITLE
how to use the log module by php ?

### ISSUE THREAD

**Issue by twbest1** [SkyAPM/SkyAPM-php-sdk#370]
Is the log module available for php and how to use it ?
I wonder how could i report my log so that i could see it on "Log".
Thx so much

**Comment by twbest1** [comment]
用skyapm/skywalking-php-7.0-fpm-alpine:latest
自己构建镜像在RSHUT时 skywalking log总是提示sky_request_flush message_queue exNo such file or directory

**Comment by heyanlong** [comment]
可以提供一下dockerfile吗？

**Comment by twbest1** [comment]
之前一直以为是boost的轻量级消息队列的问题 
结果 fpm启动的时候  需要前台启动才行 -R -F

**Comment by SZMOFEI** [comment]
我也出现了这个问题。
