### ISSUE TITLE
当curl http:/xxx/这种不标准的url的时候，request header丢失。

### ISSUE THREAD

**Issue by jmjoy** [SkyAPM/SkyAPM-php-sdk#376]
**Describe the bug**
当curl http:/xxx/这种不标准的url的时候，request header丢失。

**To Reproduce**
1. 业务方将curl的url从 'http://xxx/' ，错写成 'http:/xxx' ，在未接入sdk的情况下，是可以正常使用的。
2. 接入sdk之后，由于 https://github.com/SkyAPM/SkyAPM-php-sdk/blob/ecbb2f16fe90f0e90d236e303f2e4381aa1f7431/src/sky_plugin_curl.cc#L139 这个判断不通过，`is_record = 1`，从而导致往下跑没有调用curl_setopt，request header丢失。

看看这种情况需不需要兼容咯。

**Comment by heyanlong** [comment]
这种情况不处理sw header

**Comment by jmjoy** [comment]
不是sw header，是所有header都丢了。

**Comment by heyanlong** [comment]
这个不会吧。

**Comment by heyanlong** [comment]
remove else?
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/ecbb2f16fe90f0e90d236e303f2e4381aa1f7431/src/sky_plugin_curl.cc#L63

**Comment by jmjoy** [comment]
> remove else?
> https://github.com/SkyAPM/SkyAPM-php-sdk/blob/ecbb2f16fe90f0e90d236e303f2e4381aa1f7431/src/sky_plugin_curl.cc#L63

嗯，可以解决，只是不会上报。
