### ISSUE TITLE
php-skywalking扩展启动出错

### ISSUE THREAD

**Issue by songning4** [SkyAPM/SkyAPM-php-sdk#377]
centos: 7.9.2009
php: 7.2.34
skywalking: SkyAPM-php-sdk-4.1.2
gcc version 8.3.1 20190311
cmake version 3.20.2
protobuf: protobuf-3.17.1

1、systemctl start php-fpm启动后，systemctl status php-fpm -l出现以下：

`
May 26 09:41:43 ad-napi01-php.bt systemd[1]: Stopped The PHP FastCGI Process Manager.
May 26 09:41:43 ad-napi01-php.bt systemd[1]: Starting The PHP FastCGI Process Manager...
May 26 09:41:43 ad-napi01-php.bt php-fpm[12971]: [26-May-2021 09:41:43] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/lib64/php/modules/skywalking.so (libprotobuf.so.3.15.8.0: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/skywalking.so.so (/usr/lib64/php/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
May 26 09:41:43 ad-napi01-php.bt systemd[1]: Started The PHP FastCGI Process Manager.
`

2、ldd /usr/lib64/php/modules/skywalking.so

`
	linux-vdso.so.1 =>  (0x00007ffeb91ed000)
	libprotobuf.so.28 => /usr/local/lib/libprotobuf.so.28 (0x00007f59fc7c3000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f59fc5a5000)
	libgrpc++.so.1.38 => /usr/local/lib/libgrpc++.so.1.38 (0x00007f59fc1e8000)
	libgrpc.so.16 => /usr/local/lib/libgrpc.so.16 (0x00007f59fb59a000)
	libgpr.so.16 => /usr/local/lib/libgpr.so.16 (0x00007f59fb351000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f59fb149000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f59faf45000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f59fad29000)
	libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007f59faa1f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f59fa71d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f59fa34f000)
	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f59fa138000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f59fcf46000)
	libprotobuf.so.3.15.8.0 => /usr/local/lib64/libprotobuf.so.3.15.8.0 (0x00007f59f9810000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f59f95f6000)
	libaddress_sorting.so.16 => /usr/local/lib/libaddress_sorting.so.16 (0x00007f59f93f2000)
	libre2.so => /usr/local/lib/libre2.so (0x00007f59f909c000)
	libabsl_hash.so => /usr/local/lib/libabsl_hash.so (0x00007f59f8e98000)
	libabsl_city.so => /usr/local/lib/libabsl_city.so (0x00007f59f8c94000)
	libabsl_wyhash.so => /usr/local/lib/libabsl_wyhash.so (0x00007f59f8a91000)
	libabsl_raw_hash_set.so => /usr/local/lib/libabsl_raw_hash_set.so (0x00007f59f888d000)
	libabsl_hashtablez_sampler.so => /usr/local/lib/libabsl_hashtablez_sampler.so (0x00007f59f8687000)
	libabsl_exponential_biased.so => /usr/local/lib/libabsl_exponential_biased.so (0x00007f59f8485000)
	libabsl_statusor.so => /usr/local/lib/libabsl_statusor.so (0x00007f59f827f000)
	libabsl_bad_variant_access.so => /usr/local/lib/libabsl_bad_variant_access.so (0x00007f59f807c000)
	libupb.so.16 => /usr/local/lib/libupb.so.16 (0x00007f59f7e57000)
	libabsl_status.so => /usr/local/lib/libabsl_status.so (0x00007f59f7c37000)
	libabsl_cord.so => /usr/local/lib/libabsl_cord.so (0x00007f59f79d0000)
	libabsl_str_format_internal.so => /usr/local/lib/libabsl_str_format_internal.so (0x00007f59f778c000)
	libabsl_synchronization.so => /usr/local/lib/libabsl_synchronization.so (0x00007f59f7571000)
	libabsl_stacktrace.so => /usr/local/lib/libabsl_stacktrace.so (0x00007f59f736e000)
	libabsl_symbolize.so => /usr/local/lib/libabsl_symbolize.so (0x00007f59f7165000)
	libabsl_debugging_internal.so => /usr/local/lib/libabsl_debugging_internal.so (0x00007f59f6f5f000)
	libabsl_demangle_internal.so => /usr/local/lib/libabsl_demangle_internal.so (0x00007f59f6d55000)
	libabsl_graphcycles_internal.so => /usr/local/lib/libabsl_graphcycles_internal.so (0x00007f59f6b4c000)
	libabsl_malloc_internal.so => /usr/local/lib/libabsl_malloc_internal.so (0x00007f59f6946000)
	libabsl_time.so => /usr/local/lib/libabsl_time.so (0x00007f59f671c000)
	libabsl_strings.so => /usr/local/lib/libabsl_strings.so (0x00007f59f64e9000)
	libabsl_throw_delegate.so => /usr/local/lib/libabsl_throw_delegate.so (0x00007f59f62d4000)
	libabsl_strings_internal.so => /usr/local/lib/libabsl_strings_internal.so (0x00007f59f60d0000)
	libabsl_base.so => /usr/local/lib/libabsl_base.so (0x00007f59f5ec8000)
	libabsl_spinlock_wait.so => /usr/local/lib/libabsl_spinlock_wait.so (0x00007f59f5cc5000)
	libabsl_int128.so => /usr/local/lib/libabsl_int128.so (0x00007f59f5abc000)
	libabsl_civil_time.so => /usr/local/lib/libabsl_civil_time.so (0x00007f59f58b7000)
	libabsl_time_zone.so => /usr/local/lib/libabsl_time_zone.so (0x00007f59f5665000)
	libabsl_bad_optional_access.so => /usr/local/lib/libabsl_bad_optional_access.so (0x00007f59f5462000)
	libabsl_raw_logging_internal.so => /usr/local/lib/libabsl_raw_logging_internal.so (0x00007f59f525d000)
	libabsl_log_severity.so => /usr/local/lib/libabsl_log_severity.so (0x00007f59f505b000)
	libssl.so => /usr/local/lib/libssl.so (0x00007f59f4dae000)
	libcrypto.so => /usr/local/lib/libcrypto.so (0x00007f59f49ae000)
`

3、echo $LD_LIBRARY_PATH

`
/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/usr/local/boost/lib:/usr/local/lib:/usr/local/lib64:/usr/local/boost/lib:/usr/local/lib:/usr/local/lib64
`

4、ls -al /usr/local/lib64/libprotobuf.so.3.15.8.0

`
-rwxr-xr-x 1 root root 10563720 May 25 18:47 /usr/local/lib64/libprotobuf.so.3.15.8.0
`

启动php-fpm后，skywalking无法收到数据。文件都有，可为什么会报上面cannot open shared object file: No such file or directory错误呢

谢谢

**Comment by heyanlong** [comment]
可以尝试master，是用了静态编译。
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/BUILDING.md

**Comment by songning4** [comment]
> 可以尝试master，是用了静态编译。
> https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/BUILDING.md

@heyanlong  按照您给的方法重新下载grpc编译，重新编译skywalking，启动显示：
`
May 26 14:29:35 ad-napi01-php.bt php-fpm[1663]: [26-May-2021 14:29:35] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/lib64/php/modules/skywalking.so (/usr/lib64/php/modules/skywalking.so: undefined symbol: OPENSSL_free), /usr/lib64/php/modules/skywalking.so.so (/usr/lib64/php/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

**Comment by songning4** [comment]
@heyanlong make test执行后：

`

Build complete.
Don't forget to run 'make test'.

PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so (/home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so: undefined symbol: OPENSSL_free), /home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so.so (/home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so (/home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so: undefined symbol: OPENSSL_free), /home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so.so (/home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

=====================================================================
PHP         : /usr/bin/php
Warning: PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so (/home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so: undefined symbol: OPENSSL_free), /home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so.so (/home/geping/grpc/SkyAPM-php-sdk/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 7.2.34
ZEND_VERSION: 3.2.0
PHP_OS      : Linux - Linux ad-napi01-php.bt 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64
INI actual  : /home/geping/grpc/SkyAPM-php-sdk/tmp-php.ini
More .INIs  :
CWD         : /home/geping/grpc/SkyAPM-php-sdk
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2021-05-26 06:39:03
=====================================================================
No tests were run.

`

**Comment by songning4** [comment]
使用master编译后启动无法载入

[root@ad-napi01-php SkyAPM-php-sdk]# systemctl stop php-fpm
[root@ad-napi01-php SkyAPM-php-sdk]# /usr/sbin/php-fpm --nodaemonize
[26-May-2021 15:45:35] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/lib64/php/modules/skywalking.so (/usr/lib64/php/modules/skywalking.so: undefined symbol: OPENSSL_free), /usr/lib64/php/modules/skywalking.so.so (/usr/lib64/php/modules/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[26-May-2021 15:45:35] NOTICE: fpm is running, pid 18904
[26-May-2021 15:45:35] NOTICE: ready to handle connections
[26-May-2021 15:45:35] NOTICE: systemd monitor interval set to 10000ms

**Comment by heyanlong** [comment]
机器上没安装openssl？

**Comment by songning4** [comment]
> 机器上没安装openssl？

 @heyanlong  有装：
# openssl version
OpenSSL 1.1.1k  25 Mar 2021

**Comment by heyanlong** [comment]
编译过程每一步的命令和输出发出来看看。

**Comment by songning4** [comment]
安装依赖
yum -y install gcc-c++ boost-devel git ca-certificates autoconf automake libtool make kernel-headers kernel-devel openssl openssl-devel libcurl-devel curl

安装pkg-config
wget http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
tar zxf pkg-config-0.29.2.tar.gz
./configure --with-internal-glib
make
make check
make install

安装re2c 
git clone https://github.com/skvadrik/re2c.git re2c 
cd re2c 
mkdir -p m4 
./autogen.sh && ./configure --prefix=/usr && make 
make install
re2c -v

安装cmake
wget https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2.tar.gz
tar zxf cmake-3.20.2.tar.gz
cd cmake-3.20.2
./bootstrap
gmake
gmake install
ln -s /usr/local/bin/cmake /usr/bin/cmake
cmake --version

安装gcc 8
yum install centos-release-scl
yum install devtoolset-8
scl enable devtoolset-8 bash

安装protobuf
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protobuf-all-3.15.8.tar.gz
tar zxf protobuf-all-3.15.8.tar.gz
cd protobuf-3.15.8/
./autogen.sh
./configure
make -j$(nproc)
make check
make install
ldconfig

GRPC
git clone --depth 1 -b v1.34.x https://github.com/grpc/grpc.git
cd grpc
git submodule update --init --recursive
cd ..
cp -r grpc /var/local/
cd /var/local/grpc
mkdir -p cmake/build
cd cmake/build
cmake ../..
make -j$(nproc)



编辑
vim /etc/profile
-----------
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib64
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
export LD_RUN_PATH=/usr/local/lib:/usr/local/lib64
-----------
source /etc/profile


下载安装sky扩展
git clone https://github.com/SkyAPM/SkyAPM-php-sdk.git
cd SkyAPM-php-sdk/
phpize
./configure --with-grpc="/var/local/grpc"
make
make install



make sky扩展是报错：
SkyAPM-php-sdk/php_skywalking.h:38:10: fatal error: curl/curl.h: No such file or directory
执行：yum -y install curl-devel

make sky扩展是报错：
fatal error: absl/synchronization/mutex.h: No such file or directory
cp -r ../grpc/third_party/abseil-cpp/absl /usr/local/include/



配置php.ini
extension=skywalking.so

skywalking.enable = 1

skywalking.version = 8

skywalking.app_code = php-sky-demo

skywalking.grpc = 127.0.0.1:11800

skywalking.log_enable=1



启动：
systemctl restart php-fpm
php -m 查看扩展，有skywalking
查看状态
systemctl status php-fpm -l
这一步就出现上面遇到的那些问题了

**Comment by heyanlong** [comment]
`安装protobuf` 这一步不需要执行。

**Comment by songning4** [comment]
> `安装protobuf` 这一步不需要执行。

谢谢，我再试试

**Comment by songning4** [comment]
还是报错，提示找不到protoc，3.x版本的编译几分钟就搞定了，4.x的缺失太麻烦了了，特别是墙内服务器

**Comment by heyanlong** [comment]
发一下日志。

**Comment by songning4** [comment]
![1](https://user-images.githubusercontent.com/65797035/119801106-f6be1880-bf0f-11eb-83b4-ded91e72b745.png)

**Comment by heyanlong** [comment]
https://github.com/SkyAPM/SkyAPM-php-sdk/issues/377#issuecomment-848453969

**Comment by songning4** [comment]
谢谢，4x的编译相比3x复杂了很多

**Comment by heyanlong** [comment]
现在还有问题吗？

**Comment by songning4** [comment]
> 现在还有问题吗？

谢谢，介于难以编译和不能后台运行，我已经放弃4.x选3.3.2，现在准备在3.3.2基础上做开发实现swoole

**Comment by luyang-yanglu** [comment]
Try this in php.ini
[skywalking]
extension=json.so
extension=skywalking.so
skywalking.app_code = apiv2-phoenix
skywalking.enable = 1
skywalking.version = 8
skywalking.sock_path = /tmp/sky-agent.sock

**Comment by heyanlong** [comment]
@luyang-yanglu 不要回复已经关闭的问题。

**Comment by haanyip** [comment]
4.x的编译一堆报错 真是闹腾
