### ISSUE TITLE
skywalking收不到swoole操作Redis和MySQL

### ISSUE THREAD

**Issue by songning4** [SkyAPM/SkyAPM-php-sdk#379]
您好，在测试过程中发现swoole操作Redis、MySQL、MQ等，skywalking都无法收到相应的数据，只能收到swoole的curl

请问会增加支持吗？

**Comment by heyanlong** [comment]
是支持的，或者你用了什么特殊的客户端？

**Comment by heyanlong** [comment]
是收到了吗？
