### ISSUE TITLE
symbol lookup error happened

### ISSUE THREAD

**Issue by chen0401** [SkyAPM/SkyAPM-php-sdk#38]
after install the skywalking,so in /php/ext/ directory，I run: php -m, the " symbol lookup error: /usr/local/whistle/php/ext/skywalking.so: undefined symbol: uuid_generate_random" happened.

I have tried my best to resolve this problem，but failed.
I need ur help,please.

**Comment by heyanlong** [comment]
please install uuid-dev and remake

**Comment by chen0401** [comment]
os:centos 7
the uuid-devel and libuuid-devel had be installed both.
lrwxrwxrwx   1 root root       16 Mar 14 19:41 libuuid.so -> libuuid.so.1.3.0
lrwxrwxrwx   1 root root       16 Mar 14 19:57 libuuid.so.1 -> libuuid.so.1.3.0
-rwxr-x---   1 root root    18936 Mar 14 19:58 libuuid.so.1.3.0

**Comment by heyanlong** [comment]
What is the output of running ?
```
pkg-config --cflags --libs uuid protobuf grpc++ grpc
```

**Comment by chen0401** [comment]
like this:
```
pkg-config --cflags --libs uuid protobuf

-pthread -I/usr/include/uuid -I/usr/local/include  -pthread -L/usr/local/lib -luuid -lprotobuf
```
when i run this:
```
pkg-config --cflags --libs grpc++ grpc

Package gpr was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpr.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gpr', required by 'gRPC', not found
```

**Comment by chen0401** [comment]
php version is 7.2.1
g++ 4.8.5

**Comment by chen0401** [comment]
so?   g++ version < 4.9 caused the problem?

**Comment by heyanlong** [comment]
Version less than 4.9 does not have full cpp11 support

**Comment by chen0401** [comment]
First, thanks for your solution and it works. But there is a new and same problem happened.

where i run : php -m , the output is:
PHP Warning:  PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/local/whistle/php/ext/skywalking.so (/usr/local/whistle/php/ext/skywalking.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev), /usr/local/whistle/php/ext/skywalking.so.so (/usr/local/whistle/php/ext/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

that means there is no symbol _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev in skywalking.so. 
Then i execute :nm  -D protoc | grep google:
0000000000950d60 B _ZN6google8protobuf34_DescriptorProto_default_instance_E
0000000000950bc0 B _ZN6google8protobuf38_EnumDescriptorProto_default_instance_E
0000000000950ec0 B _ZN6google8protobuf38_FileDescriptorProto_default_instance_E
0000000000950ca0 B _ZN6google8protobuf39_FieldDescriptorProto_default_instance_E
0000000000950c60 B _ZN6google8protobuf39_OneofDescriptorProto_default_instance_E
0000000000950b00 B _ZN6google8protobuf40_MethodDescriptorProto_default_instance_E
0000000000950b40 B _ZN6google8protobuf41_ServiceDescriptorProto_default_instance_E
0000000000950b80 B _ZN6google8protobuf43_EnumValueDescriptorProto_default_instance_E
0000000000950e80 B _ZN6google8protobuf49_DescriptorProto_ExtensionRange_default_instance_E
000000000094fee0 B _ZN6google8protobuf8compiler39_CodeGeneratorRequest_default_instance_E
00000000009502e0 B _ZN6google8protobuf8internal26fixed_address_empty_stringE

There is no symbol like '_ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev' obviously.

The protoc version is 3.7.0
So ... 3.7.0 has no this method? And which one is supported?

**Comment by chen0401** [comment]
First, thanks for your solution and it works. But there is a new and same problem happened.

when I run : php -m , the output is:
PHP Warning: PHP Startup: Unable to load dynamic library 'skywalking.so' (tried: /usr/local/whistle/php/ext/skywalking.so (/usr/local/whistle/php/ext/skywalking.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev), /usr/local/whistle/php/ext/skywalking.so.so (/usr/local/whistle/php/ext/skywalking.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

The protoc version is 3.7.0 and g++ 6.1

**Comment by chen0401** [comment]
Thanks for your help and it works. But there is a new problem.
### run : ldd skywalking.so
### output:
 [root@localhost ext]# ldd skywalking.so 
	linux-vdso.so.1 =>  (0x00007fff6677e000)
	libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x00007f68ba839000)
	libprotobuf.so.18 => /usr/local/lib/libprotobuf.so.18 (0x00007f68ba397000)
	libgrpc++.so.1 => /usr/local/lib/libgrpc++.so.1 (0x00007f68ba0fd000)
	libgrpc.so.7 => /usr/local/lib/libgrpc.so.7 (0x00007f68b9d61000)
	libgrpc++_reflection.so.1 => /usr/local/lib/libgrpc++_reflection.so.1 (0x00007f68b9b11000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f68b990d000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f68b958c000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f68b9376000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f68b915a000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f68b8d8d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68badb2000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007f68b8b77000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f68b8875000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00007f68b866d000)
	libgpr.so.7 => /usr/local/lib/libgpr.so.7 (0x00007f68b8461000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f68b81ef000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f68b7d8e000)
	libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f68b7b41000)
	libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f68b7858000)
	libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f68b7654000)
	libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f68b7421000)
	libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f68b7211000)
	libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f68b700d000)
	libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f68b6df4000)
	libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f68b6bcd000)
	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f68b696b000)

**Comment by chen0401** [comment]
Thanks for your help and it works. But there is a new problem.
### run : ldd skywalking.so
### output:
 [root@localhost ext]# ldd skywalking.so 
	linux-vdso.so.1 =>  (0x00007fff6677e000)
	libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x00007f68ba839000)
	libprotobuf.so.18 => /usr/local/lib/libprotobuf.so.18 (0x00007f68ba397000)
	libgrpc++.so.1 => /usr/local/lib/libgrpc++.so.1 (0x00007f68ba0fd000)
	libgrpc.so.7 => /usr/local/lib/libgrpc.so.7 (0x00007f68b9d61000)
	libgrpc++_reflection.so.1 => /usr/local/lib/libgrpc++_reflection.so.1 (0x00007f68b9b11000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f68b990d000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f68b958c000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f68b9376000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f68b915a000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f68b8d8d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68badb2000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007f68b8b77000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f68b8875000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00007f68b866d000)
	libgpr.so.7 => /usr/local/lib/libgpr.so.7 (0x00007f68b8461000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f68b81ef000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f68b7d8e000)
	libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f68b7b41000)
	libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f68b7858000)
	libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f68b7654000)
	libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f68b7421000)
	libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f68b7211000)
	libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f68b700d000)
	libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f68b6df4000)
	libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f68b6bcd000)
	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f68b696b000)
but when  I run "php -m", the Segmentation fault happened. Why?

**Comment by chen0401** [comment]
Thanks for your help and it works. But there is a new problem.

run : ldd skywalking.so

output:

[root@localhost ext]# ldd skywalking.so
linux-vdso.so.1 => (0x00007fff6677e000)
libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x00007f68ba839000)
libprotobuf.so.18 => /usr/local/lib/libprotobuf.so.18 (0x00007f68ba397000)
libgrpc++.so.1 => /usr/local/lib/libgrpc++.so.1 (0x00007f68ba0fd000)
libgrpc.so.7 => /usr/local/lib/libgrpc.so.7 (0x00007f68b9d61000)
libgrpc++_reflection.so.1 => /usr/local/lib/libgrpc++_reflection.so.1 (0x00007f68b9b11000)
libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f68b990d000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f68b958c000)
libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f68b9376000)
libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f68b915a000)
libc.so.6 => /usr/lib64/libc.so.6 (0x00007f68b8d8d000)
/lib64/ld-linux-x86-64.so.2 (0x00007f68badb2000)
libz.so.1 => /usr/lib64/libz.so.1 (0x00007f68b8b77000)
libm.so.6 => /usr/lib64/libm.so.6 (0x00007f68b8875000)
librt.so.1 => /usr/lib64/librt.so.1 (0x00007f68b866d000)
libgpr.so.7 => /usr/local/lib/libgpr.so.7 (0x00007f68b8461000)
libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f68b81ef000)
libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f68b7d8e000)
libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f68b7b41000)
libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f68b7858000)
libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f68b7654000)
libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f68b7421000)
libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f68b7211000)
libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f68b700d000)
libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f68b6df4000)
libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f68b6bcd000)
libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f68b696b000)

Thanks for your help and it works. But there is a new problem.

run : ldd skywalking.so

output:

[root@localhost ext]# ldd skywalking.so
linux-vdso.so.1 => (0x00007fff6677e000)
libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x00007f68ba839000)
libprotobuf.so.18 => /usr/local/lib/libprotobuf.so.18 (0x00007f68ba397000)
libgrpc++.so.1 => /usr/local/lib/libgrpc++.so.1 (0x00007f68ba0fd000)
libgrpc.so.7 => /usr/local/lib/libgrpc.so.7 (0x00007f68b9d61000)
libgrpc++_reflection.so.1 => /usr/local/lib/libgrpc++_reflection.so.1 (0x00007f68b9b11000)
libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f68b990d000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f68b958c000)
libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f68b9376000)
libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f68b915a000)
libc.so.6 => /usr/lib64/libc.so.6 (0x00007f68b8d8d000)
/lib64/ld-linux-x86-64.so.2 (0x00007f68badb2000)
libz.so.1 => /usr/lib64/libz.so.1 (0x00007f68b8b77000)
libm.so.6 => /usr/lib64/libm.so.6 (0x00007f68b8875000)
librt.so.1 => /usr/lib64/librt.so.1 (0x00007f68b866d000)
libgpr.so.7 => /usr/local/lib/libgpr.so.7 (0x00007f68b8461000)
libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f68b81ef000)
libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f68b7d8e000)
libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f68b7b41000)
libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f68b7858000)
libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f68b7654000)
libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f68b7421000)
libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f68b7211000)
libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f68b700d000)
libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f68b6df4000)
libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f68b6bcd000)
libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f68b696b000)


but when I run "php -m", the Segmentation fault happened. Why?

**Comment by chen0401** [comment]
Thanks for your help and it works. But there is a new problem.

run : ldd skywalking.so

output:

[root@localhost ext]# ldd skywalking.so
linux-vdso.so.1 => (0x00007fff6677e000)
libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x00007f68ba839000)
libprotobuf.so.18 => /usr/local/lib/libprotobuf.so.18 (0x00007f68ba397000)
libgrpc++.so.1 => /usr/local/lib/libgrpc++.so.1 (0x00007f68ba0fd000)
libgrpc.so.7 => /usr/local/lib/libgrpc.so.7 (0x00007f68b9d61000)
libgrpc++_reflection.so.1 => /usr/local/lib/libgrpc++_reflection.so.1 (0x00007f68b9b11000)
libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f68b990d000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f68b958c000)
libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f68b9376000)
libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f68b915a000)
libc.so.6 => /usr/lib64/libc.so.6 (0x00007f68b8d8d000)
/lib64/ld-linux-x86-64.so.2 (0x00007f68badb2000)
libz.so.1 => /usr/lib64/libz.so.1 (0x00007f68b8b77000)
libm.so.6 => /usr/lib64/libm.so.6 (0x00007f68b8875000)
librt.so.1 => /usr/lib64/librt.so.1 (0x00007f68b866d000)
libgpr.so.7 => /usr/local/lib/libgpr.so.7 (0x00007f68b8461000)
libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f68b81ef000)
libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f68b7d8e000)
libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007f68b7b41000)
libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f68b7858000)
libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f68b7654000)
libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f68b7421000)
libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007f68b7211000)
libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f68b700d000)
libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f68b6df4000)
libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f68b6bcd000)
libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f68b696b000)


but when I run "php -m", the Segmentation fault happened. Why?

**Comment by heyanlong** [comment]
Upgrading, use boost-(uuid, regex) instead.
Please wait for new release

**Comment by chen0401** [comment]
Thanks for ur help.
