### ISSUE TITLE
请问下为什么skywalking扩展只能前台运行

### ISSUE THREAD

**Issue by songning4** [SkyAPM/SkyAPM-php-sdk#380]
请问下为什么skywalking4.1.2版本扩展只能--nodaemonize运行，使用裸机安装的扩展前台运行实在有点不方便，谢谢

**Comment by heyanlong** [comment]
可以用systemd托管

**Comment by songning4** [comment]
php一直是systemd托管，指令：

[Unit]
Description=The PHP FastCGI Process Manager
After=syslog.target network.target

[Service]
Type=notify
PIDFile=/run/php-fpm/php-fpm.pid
ExecStart=/usr/sbin/php-fpm --nodaemonize
ExecReload=/bin/kill -USR2 $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target

但实际上使用systemd托管后skywalking 服务端就无法收到任何数据，也没有报错，连agent的日志也没有任何数据被打印

**Comment by chengang99** [comment]
测试7.2 7.4 都无法守护进程托管

**Comment by heyanlong** [comment]
@chengang99 你也是一样的问题吗？

**Comment by zhjinliang** [comment]
> 请问下为什么skywalking4.1.2版本扩展只能--nodaemonize运行，使用裸机安装的扩展前台运行实在有点不方便，谢谢

@songning4 我也遇到相同的问题，你的问题已经解决了吗？

**Comment by songning4** [comment]
> > 请问下为什么skywalking4.1.2版本扩展只能--nodaemonize运行，使用裸机安装的扩展前台运行实在有点不方便，谢谢
> 
> @songning4 我也遇到相同的问题，你的问题已经解决了吗？

@zhjinliang 无奈切到3.3.2去了

**Comment by zhjinliang** [comment]
> > > 请问下为什么skywalking4.1.2版本扩展只能--nodaemonize运行，使用裸机安装的扩展前台运行实在有点不方便，谢谢
> > 
> > 
> > @songning4 我也遇到相同的问题，你的问题已经解决了吗？
> 
> @zhjinliang 无奈切到3.3.2去了

好吧，很无奈，我也试下3.3.2

**Comment by heyanlong** [comment]
你们的错误日志是什么？

**Comment by songning4** [comment]
> 你们的错误日志是什么？

您好，没有错误日志，不管怎么请求PHP代码，没有日志，服务端也没有收到任何请求

**Comment by heyanlong** [comment]
/tmp/skywalking-php.log 也不存在吗？

**Comment by heyanlong** [comment]
这样说明已经挂载了

发自我的iPhone

**Comment by calvin2021y** [comment]
为什么问题没人回答就关闭了？

**Comment by songning4** [comment]
@calvin2021y 因为4.X太难搞，换3.X版本了
