### ISSUE TITLE
Configure on AWS ECS + PHP 7.1 + Laravel 5.2

### ISSUE THREAD

**Issue by KelvinFerraz** [SkyAPM/SkyAPM-php-sdk#382]
Hi, everyone!

I'm starting to test some APM application, I configure on a server with Skywalking with Elasticsearch7 to the database, but I'm having a hard time understanding how I can configure the agent. In my case use on AWS ECS with PHP 7.1 + Laravel.

Is there anyone who already needed to configure the agent for an AWS ECS cluster with PHP?

I tried to search for some examples of how to configure an agent but I don`t find anything simple to understand.

Regards,

**Comment by heyanlong** [comment]
Send information about the current configuration. Thank you

**Comment by KelvinFerraz** [comment]
Sure,

Application:

PHP 7.1
Laravel 5.2
NodeJS 7

Infrastructure:

Cluster AWS ECS with EC2
Running Amazon Linux and Docker
AWS RDS - MySQL 7.24

Skywalking Server:

Ubuntu 20.04
Skywalking 8.5
+Elasticsearch 7

My big question is about how I configure an agent with PHP on Amazon's ECS Cluster.

Thank you.

**Comment by heyanlong** [comment]
Just like normal Linux.

**Comment by KelvinFerraz** [comment]
Ok

But I need an example practical because this way on documentation is very confusing, don't have an example of how to install PHP agent on Linux.

Do you have these examples?

Thank you

**Comment by heyanlong** [comment]
This contains the installation guide for Linux (ubuntu) and macOS
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/BUILDING.md
