### ISSUE TITLE
php7.3dockerfile run error

### ISSUE THREAD

**Issue by Arealm** [SkyAPM/SkyAPM-php-sdk#383]
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docker/Dockerfile.7.3

#7 1708.7 + echo '--- installing skywalking php ---'
#7 1708.7 + cd /var/local/git/skywalking
#7 1708.7 --- installing skywalking php ---
#7 1708.7 + phpize
#7 1708.7 Cannot find config.m4.
#7 1708.7 Make sure that you run '/usr/local/bin/phpize' in the top level source directory of the module
#7 1708.7
------
executor failed running [/bin/sh -c set -ex     && docker-php-ext-install mysqli     && apk --update add --no-cache boost-dev git ca-certificates autoconf automake libtool g++ make file linux-headers file re2c pkgconf openssl openssl-dev curl-dev nginx     && echo "--- clone grpc ---"     && git clone --depth 1 -b ${GRPC_RELEASE_TAG} https://github.com/grpc/grpc /var/local/git/grpc     && cd /var/local/git/grpc     && git submodule update --init --recursive     && echo "--- download cmake ---"     && cd /var/local/git     && curl -L -o cmake-3.19.1.tar.gz  https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1.tar.gz     && tar zxf cmake-3.19.1.tar.gz     && cd cmake-3.19.1 && ./bootstrap && make -j$(nproc) && make install     && echo "--- installing grpc ---"     && cd /var/local/git/grpc     && mkdir -p cmake/build && cd cmake/build && cmake ../..     && make -j$(nproc)     && echo "--- installing skywalking php ---"     && cd /var/local/git/skywalking     && phpize && ./configure --with-grpc=/var/local/git/grpc && make && make install     && cp php.ini $PHP_INI_DIR/conf.d/ext-skywalking.ini     && mkdir -p /opt     && cp docker/service.sh /opt/     && cp docker/nginx.conf /etc/nginx/nginx.conf     && cp docker/index.php /var/www/html/index.php     && cd /     && rm -rf /var/cache/apk/*     && rm -fr /var/local/git]: exit code: 1

**Comment by Arealm** [comment]
7.4也是一样的问题

**Comment by heyanlong** [comment]
maybe `ADD. /var/local/git/skywalking` does not execute
