### ISSUE TITLE
4.1.1不是支持tars了吗

### ISSUE THREAD

**Issue by Arealm** [SkyAPM/SkyAPM-php-sdk#384]
if (SKY_IS_SWOOLE(function_name) || SKY_IS_SWOOLE_FRAMEWORK(class_name, function_name)) {
        uint32_t arg_count = ZEND_CALL_NUM_ARGS(execute_data);
        if (arg_count == 2) {
            zval *sw_request = ZEND_CALL_ARG(execute_data, 1);
            sw_response = ZEND_CALL_ARG(execute_data, 2);
            if (Z_TYPE_P(sw_request) == IS_OBJECT && Z_TYPE_P(sw_response) == IS_OBJECT) {
                if (strcmp(ZSTR_VAL(Z_OBJ_P(sw_request)->ce->name), "Swoole\\Http\\Request") == 0) {
                    if (strcmp(ZSTR_VAL(Z_OBJ_P(sw_response)->ce->name), "Swoole\\Http\\Response") == 0) {
                        swoole = true;
                        zval *z_fd = sky_read_property(sw_request, "fd", 0);
                        SKYWALKING_G(is_swoole) = true;
                        request_id = Z_LVAL_P(z_fd);
                        sky_request_init(sw_request, request_id);
                    }
                }
            }
        }
    }
#define SKY_IS_TARS(class_name, func_name) (SKY_STRCMP(class_name, "Tars\\core\\Server") && SKY_STRCMP(func_name, "onRequest"))

从代码上看支持了，实际上今天试了还是不行，有没有办法debug呢？

**Comment by heyanlong** [comment]
提供一下tars的测试代码。

**Comment by Arealm** [comment]
https://github.com/TarsPHP/TarsPHP ，就是这个官方demo， 直接curl 请求helloword  不行的。  直接也写了curl_init手动也不行

**Comment by Arealm** [comment]
抱歉。#define SKY_IS_TARS(class_name, func_name) (SKY_STRCMP(class_name, "App\\Core\\Tars") && SKY_STRCMP(func_name, "onRequest"))
这个onRequest可以是静态方法吗？

**Comment by Arealm** [comment]
@heyanlong

**Comment by Arealm** [comment]
不是原生那个server文件了。。。自己改写了一个版本

public static function onRequest(\swoole_http_request $request, \swoole_http_response $response)
    {




        global $g_response;
        global $g_request;
        global $g_start_time;
        global $g_real_url;
        $g_real_url="";

        //是否关闭 thinkphp show colmon list
        global $g_without_table_info_flag;
        $g_without_table_info_flag=false;

        $g_start_time =microtime(true);
        //保存到全局
        $g_response= $response;
        // $response->header("Core-Server", \App\Core\Tars::$project_name);
        // $response->header("Core-Server-Worker-Host", static::$listen_host);
        // $response->header("Core-Server-Worker-Port", static::$listen_port);
        $g_request= $request;
        \App\Helper\Common::reset_cur_require_token();

        \App\Core\Middleware\ZipkinTrace::$traceid="traceid_null";



        //过滤无效请求
        if (in_array($request->server['request_uri'], ["/", "/favicon.ico"])) {
            $response->end("{ \"ret\"=> 0,  \"info\"=>\"succ\"  }");
            return;
        }

        //sidebar健康检查
        if ($request->server['request_uri']=="/health") {
            $response->header(
                'Content-Type',
                'application/json'
            );
            $response->end("{ \"status\" : \"UP\" }");
            return;
        }

        if (in_array($request->server['request_uri'], ["/eureka_version"])) {
            $response->end("{ \"version\"=> \"" . \App\Helper\Utils::env('EUREKA_VERSION' , '1.0') . "\" }");
            return;
        }


        //\App\Helper\Utils::logger ("SERVER:". json_encode($request->server));
        //\App\Helper\Utils::logger ("HEADER:". json_encode($request->header));
        //dd( $request->header );

        //request_method":"OPTIONS"
        //免得 之前报错,没有关闭数据库,
        //\App\Core\Db\NewDB::close_all_dbs();
        //\think\Db::clear();


        try {
            $uri=$request->server['request_uri'];

            $real_url="";
            $ctrl_name="";
            $action_name="";
            $version="";

            //从url 中得到 路由信息
            if (preg_match('/(\/([^\/]*))?(\/([^\/]*))?\/([^\/]*)$/', $uri, $matches)) {
                /*
                [0] => /test/v1
                    [1] => /test
                    [2] => test
                    [3] =>
                    [4] =>
                    [5] => v1
                */
                if ($matches[1]=="") {
                    $ctrl_name=$matches[5];
                    $action_name="index";
                    $real_url="/$ctrl_name/$action_name";
                } elseif ($matches[3]=="") {
                    $ctrl_name=$matches[2];
                    $action_name=$matches[5];
                    $real_url="/$ctrl_name/$action_name";
                } else { //有version
                    $version=$matches[2];
                    $ctrl_name=$matches[4];
                    $action_name=$matches[5];
                    $real_url="/$version/$ctrl_name/$action_name";
                    $cmd_info=@static::$http_cmd_config["$real_url"];
                    if (!$cmd_info) { //没有定义version 的协议, 回到2级
                        $real_url="/$ctrl_name/$action_name";
                    }
                }
            }

            \App\Helper\Utils::logger("uri->real_url", [
                "uri"=> $uri,
                "real_url"=> $real_url,
            ]);
            //\App\Helper\Utils::logger("header:".  json_encode($request->header )    );
            $g_real_url=$real_url;


            $cmd_info=@static::$http_cmd_config["$real_url"];


            $header=$request->header;
            $client_info=@$header["x-client-info"]??"";
            $client_ip=@$header["x-real-ip"]??"";

            # 设置ab 测试 版本信息
            global $g_api_version;
            $g_api_version=@$header["api-version"];
            if ($g_api_version!="b") {
                $g_api_version="a";
            }
            $response->header("Api-Version", $g_api_version);

            $get=[];
            if (is_array($request->get)) {
                $get= $request->get  ;
            }

            $post=[];
            if (is_array($request->post)) {
                $post= $request->post  ;
            } else {
                $post=@json_decode($request->rawContent(), true);
                if (!is_array($post)) {
                    $post=[];
                }
            }
            $request_data=array_merge($get, $post) ;

            global $g_jsonp_callback;
            global $g_request_data;
            $g_jsonp_callback=@$request_data["__callback"] ;
            $g_request_data= $request_data;




            $query_arr=[];
            foreach ($request_data as $key => &$value) {
                if (is_string($value) || is_numeric($value) || is_null($value)) {
                    if ($key!="var_session_id") {
                        $query_arr[]="$key=" . urlencode(substr($value, 0, 200));
                    }
                }
            }

            global $g_sessionid;

            //dd($request);
            $app_url=\App\Helper\Config::get_app_url();

            $query_str= join("&", $query_arr) ;

            $log_in_info="[$client_ip][$client_info]IN:$app_url$uri?". $query_str ;

            global $g_log_in_info;
            $g_log_in_info =$log_in_info;
            //\App\Helper\Utils::logger($log_in_info);



            $ctrl_class_name= @$cmd_info[0];
            if ($ctrl_class_name) {
                if (!class_exists($ctrl_class_name)) {
                    preg_match("/^(.*\\\\)([^\\\\]*)\$/", $ctrl_class_name, $matches);
                    $ctrl_class_name= $matches[1].  \App\Helper\Utils::str_to_camel_case($matches[2]);
                }
            }


            $pipe_input= new \App\Core\Middleware\HttpMiddlewareInput();


            $pipe_input->ctrl_class_name=$ctrl_class_name;
            $pipe_input->ctrl_name=$ctrl_name;
            $pipe_input->action_name=$action_name;
            $pipe_input->request =$request;
            $pipe_input->response =$response;
            $pipe_input->cmd_info =$cmd_info;
            $pipe_input->request_data =$request_data;


            //管道处理
            (new \App\Core\Utils\Pipeline())
                ->send($pipe_input)
                ->through(\App\Kernel::get_http_middleware())
                ->then(function (\App\Core\Middleware\HttpMiddlewareInput $input) use (
                    $query_str,
                    $client_ip,
                    $app_url,
                    $uri
                ) {

                    global $_SESSION;
                    $account=@$_SESSION["name"];
                    $login_adminid=@$_SESSION["login_adminid"];
                    global $g_sessionid;

                    $log_in_info="[$client_ip][$login_adminid][$account]"
                                . "IN_URL:$app_url$uri?var_session_id=$g_sessionid&" . $query_str ;
                    \App\Helper\Utils::logger("in_url", [
                        "client_ip"=>$client_ip,
                        "login_adminid"=>$login_adminid,
                        "account"=>$account,
                        "url"=>"$app_url$uri",
                        "in_url"=>"$app_url$uri?var_session_id=$g_sessionid&$query_str",
                    ]);




                    Tars::call_action($input);
                });
        } catch (\Exception $e) {
            $message=$e->getMessage();
            $trace_list=$e->getTrace();
            $ret_arr=["ret"=> 1002, "code" =>1002, "info"=>"系统出错4",
             'msg'=> $message,
             "file"=> $e->getFile(),
             "line"=> $e->getLine(),
             "trace"=>$trace_list  ];

            $ret_str=json_encode($ret_arr, JSON_UNESCAPED_UNICODE|  JSON_PARTIAL_OUTPUT_ON_ERROR);

            if (@$trace_list[0]["function"] != "dd") {
                \App\Helper\Utils::logger("MESSAGE:$message|". $ret_str);
                static::send_global_err($ret_str);
            }
        } catch (\Error $e) {
            $message=$e->getMessage();
            $trace_list=$e->getTrace();

            $ret_str=json_encode(["ret"=> 1002,   "info"=>"系统出错5",
                                  "code" => 1002,
                                  'msg'=> $message,
                                  "file"=> $e->getFile(),
                                  "line"=> $e->getLine(),
                                  "trace"=>$trace_list  ], JSON_UNESCAPED_UNICODE |  JSON_PARTIAL_OUTPUT_ON_ERROR);

            \App\Helper\Utils::logger("MESSAGE:$message|". $ret_str);

            static::send_global_err($ret_str);
        }
        //\think\Db::clear();

        $g_response= null;
        static::$cur_request_count++;
        // 每过 max_request_count  次垃圾收集一次
        if (static::$cur_request_count>= static::$max_request_count) {
            static::$cur_request_count=0;
            \App\Helper\Utils::logger("do  gc_collect_cycles ");
            gc_collect_cycles();
        }
    }

**Comment by heyanlong** [comment]
自己写的可以吗？

**Comment by Arealm** [comment]
目前不可以，显示已经挂载 但是没有上报

**Comment by heyanlong** [comment]
所以是官方的和你写这个都不可以，是吧？

**Comment by Arealm** [comment]
这里sky_log 
    if (SKY_IS_SWOOLE(function_name) || SKY_IS_SWOOLE_FRAMEWORK(class_name, function_name)) {
都没进去

**Comment by Arealm** [comment]
#define SKY_IS_TARS(class_name, func_name) (SKY_STRCMP(class_name, "App\\Core\\Tars") && SKY_STRCMP(func_name, "onRequest"))

**Comment by heyanlong** [comment]
ping

**Comment by heyanlong** [comment]
给我一份最小代码，可运行的。
