### ISSUE TITLE
kernel: [4417665.769934] php-fpm[2226658]: segfault at 0 ip 00007fb1ab8ace05 sp 00007ffecc84fa10 error 4 in skywalking.so[7fb1ab86b000+68000]

### ISSUE THREAD

**Issue by lwl-xyz** [SkyAPM/SkyAPM-php-sdk#385]
1、相关组件版本
php version: 7.2.34  或 7.1.24
skywalking version: 4.1.1

Linux version 4.15.0-143-generic (buildd@lcy01-amd64-001) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021
或
Linux version 5.4.0-67-generic (buildd@lcy01-amd64-025) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021

2、执行清理php opcache 相关命令操作
      如下为操作命令 ：
      # echo '<?php opcache_reset(); echo "ok\n";' > /tmp/php-fpm-opcache-reset.php
      # SCRIPT_FILENAME=/tmp/php-fpm-opcache-reset.php REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000
或者直接通过cgi-fcgi调用，都会出现标题系统读内存错误，导致执行失败
     # cgi-fcgi -bind -connect 127.0.0.1:9000
     
3、上面命令执行在/var/log/kern.log 和 /var/log/syslog 日志提示如下：
Jun 10 13:50:42 kernel: [4417665.769934] php-fpm[2226658]: segfault at 0 ip 00007fb1ab8ace05 sp 00007ffecc84fa10 error 4 in skywalking.so[7fb1ab86b000+68000]
Jun 10 13:50:42 kernel: [4417665.769942] Code: 00 00 00 48 8d 35 3c 82 02 00 48 8d b8 30 01 00 00 e8 2f 29 fc ff 48 8b 38 ba 0b 00 00 00 48 8d 35 49 8b 02 00 e8 1b 29 fc ff <4c> 8b 28 49 83 c5 18 4c 89 ef e8 2c 17 fc ff 49 8b 54 24 08 4c 89

另外php-fpm.log提示如下：
[10-Jun-2021 13:50:42] WARNING: [pool www] child 2226658 exited on signal 11 (SIGSEGV) after 13.285315 seconds from start

**Comment by heyanlong** [comment]
thanks for the feedback

**Comment by james9203** [comment]
hello,have you solve this problems

**Comment by heyanlong** [comment]
not yet
