### ISSUE TITLE
PHP Startup: skywalking: Unable to initialize module

### ISSUE THREAD

**Issue by zhjinliang** [SkyAPM/SkyAPM-php-sdk#386]
问题描述：

机器装有 PHP5.6、PHP7.2.34
报错是给PHP7.2.34安装扩展后启动报的错
编译安装时都有指定 PHP bin 和 PHP配置
安装的是 skywalking（3.3.2）扩展

`/data/soft/php/7.2.n/bin/phpize`
`./configure --with-php-config=/data/soft/php/7.2.n/bin/php-config`
`make && make install`
/data/soft/php/7.2.n/sbin/php-fpm --fpm-config /data/soft/php/7.2.n/etc/php-fpm.conf -c /data/soft/php/7.2.n/etc/php.ini

启动 php-fpm 报以下错误：

Unknown(0) : Warning - PHP Startup: skywalking: Unable to initialize module
Module compiled with build ID=API20170718,NTS
PHP    compiled with build ID=API20170718,NTS,debug
These options need to match

环境：
Linux version 3.10.0-957.12.2.el7.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) )

**Comment by heyanlong** [comment]
编译与运行环境不一致。

**Comment by zhjinliang** [comment]
> 编译与运行环境不一致。

编译和运行是在同一个终端执行的，应该不存在编译和运行环境不一致的情况吧！
这个问题我应该怎么区分出【编译与运行环境】是否一致。

**Comment by heyanlong** [comment]
Module compiled with build ID=API20170718,NTS
PHP compiled with build ID=API20170718,NTS,debug

**Comment by zhjinliang** [comment]
> Module compiled with build ID=API20170718,NTS
> PHP compiled with build ID=API20170718,NTS,debug

感谢，问题已经解决了，编译的时候加了debug
`./configure --with-php-config=/data/soft/php/7.2.n/bin/php-config --enable-debug`
