### ISSUE TITLE
Why specify the gpc path， still output error cannot find grpc?

### ISSUE THREAD

**Issue by becage** [SkyAPM/SkyAPM-php-sdk#387]
```
curl -Lo v4.1.2.tar.gz https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v4.1.2.tar.gz
tar zxvf v4.1.2.tar.gz
cd SkyAPM-php-sdk-4.1.2
phpize
./configure --with-grpc="/var/local/git/grpc"
```
output 
```
...
checking whether to enable skywalking support... yes, shared
checking whether C++ compiler accepts -std=c++0x... yes
checking for php_json.h... found in /usr/include/php/20170718
checking for grpc and protobuf files in default path... found in /usr/local
not found
configure: error: Please reinstall the grpc distribution
```

![image](https://user-images.githubusercontent.com/41765271/121707956-aea31680-cb09-11eb-8539-793787ec3c97.png)

why ```./configure --with-grpc="/var/local/git/grpc"``` doesn't work?  
how to install grpc and protobuf in ```/usr/local```?
thanks.

**Comment by becage** [comment]
```vim /root/SkyAPM-php-sdk-4.1.2/configure```
line 4537  change search_path doesn't work too.``` SEARCH_PATH="/var/local/git/grpc /usr"```

**Comment by heyanlong** [comment]
This parameter is valid for 4.1.3 or newer
