### ISSUE TITLE
Centos7 环境下编译一直失败

### ISSUE THREAD

**Issue by Cuigeek** [SkyAPM/SkyAPM-php-sdk#389]
curl -Lo v4.1.2.tar.gz https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v4.1.2.tar.gz
tar zxvf v4.1.2.tar.gz
cd SkyAPM-php-sdk-4.1.2
phpize
./configure --with-grpc="/var/local/git/grpc"
提示：
configure: WARNING: unrecognized options: --with-grpc

configure成功以后，make就会失败
In file included from /data/install/SkyAPM-php-sdk-4.1.2/php_skywalking.h:25,
                 from /data/install/SkyAPM-php-sdk-4.1.2/skywalking.cc:21:
/data/install/SkyAPM-php-sdk-4.1.2/src/common.h:18:10: fatal error: boost/interprocess/ipc/message_queue.hpp: No such file or directory
   18 | #include <boost/interprocess/ipc/message_queue.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1

环境信息：
 - OS: Centos 7.4
 - GRPC安装正常
 - PHP 7.3

protoc --version
libprotoc 3.13.0

**Comment by heyanlong** [comment]
configure应该是没成功，完整日志发出来

**Comment by Cuigeek** [comment]
[ SkyAPM-php-sdk-4.1.2]$ ./configure 
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /data/soft/php-7.2.15
checking for PHP includes... -I/data/soft/php-7.2.15/include/php -I/data/soft/php-7.2.15/include/php/main -I/data/soft/php-7.2.15/include/php/TSRM -I/data/soft/php-7.2.15/include/php/Zend -I/data/soft/php-7.2.15/include/php/ext -I/data/soft/php-7.2.15/include/php/ext/date/lib
checking for PHP extension directory... /data/soft/php-7.2.15/lib/php/extensions/no-debug-non-zts-20170718
checking for PHP installed headers prefix... /data/soft/php-7.2.15/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether to enable skywalking support... yes, shared
checking whether C++ compiler accepts -std=c++0x... yes
checking for php_json.h... found in /data/soft/php-7.2.15/include/php
checking for grpc and protobuf files in default path... found in /usr/local
found in /usr/local
checking for gpr_now in -lgpr... yes
checking for grpc_channel_destroy in -lgrpc... yes
checking for protoc... /usr/local/bin/protoc
checking for grpc_cpp_plugin... /usr/local/bin/grpc_cpp_plugin
checking for ld used by cc... /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld
checking if the linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld) is GNU ld... yes
checking for /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld option to reload object files... -r
checking for BSD-compatible nm... /opt/rh/devtoolset-10/root/usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 1572864
checking command to parse /opt/rh/devtoolset-10/root/usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld -m elf_x86_64
checking if the linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged

**Comment by heyanlong** [comment]
boost 安装了吗？

**Comment by Cuigeek** [comment]
没有，安装完需要重新编译GRPC吗？我刚刚尝试重新编译SkyAPM-php-sdk-4.1.2 make还是过不去
/bin/sh /data/install/SkyAPM-php-sdk-4.1.2/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/install/SkyAPM-php-sdk-4.1.2 -DPHP_ATOM_INC -I/data/install/SkyAPM-php-sdk-4.1.2/include -I/data/install/SkyAPM-php-sdk-4.1.2/main -I/data/install/SkyAPM-php-sdk-4.1.2 -I/data/soft/php-7.2.15/include/php -I/data/soft/php-7.2.15/include/php/main -I/data/soft/php-7.2.15/include/php/TSRM -I/data/soft/php-7.2.15/include/php/Zend -I/data/soft/php-7.2.15/include/php/ext -I/data/soft/php-7.2.15/include/php/ext/date/lib -I/usr/local/include -I/data/install/SkyAPM-php-sdk-4.1.2/src -I/data/install/SkyAPM-php-sdk-4.1.2/src/network/v3  -DHAVE_CONFIG_H  -g -O2 -Wall -std=c++11 -Wno-deprecated-register   -c /data/install/SkyAPM-php-sdk-4.1.2/skywalking.cc -o skywalking.lo 
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/data/install/SkyAPM-php-sdk-4.1.2 -DPHP_ATOM_INC -I/data/install/SkyAPM-php-sdk-4.1.2/include -I/data/install/SkyAPM-php-sdk-4.1.2/main -I/data/install/SkyAPM-php-sdk-4.1.2 -I/data/soft/php-7.2.15/include/php -I/data/soft/php-7.2.15/include/php/main -I/data/soft/php-7.2.15/include/php/TSRM -I/data/soft/php-7.2.15/include/php/Zend -I/data/soft/php-7.2.15/include/php/ext -I/data/soft/php-7.2.15/include/php/ext/date/lib -I/usr/local/include -I/data/install/SkyAPM-php-sdk-4.1.2/src -I/data/install/SkyAPM-php-sdk-4.1.2/src/network/v3 -DHAVE_CONFIG_H -g -O2 -Wall -std=c++11 -Wno-deprecated-register -c /data/install/SkyAPM-php-sdk-4.1.2/skywalking.cc  -fPIC -DPIC -o .libs/skywalking.o
In file included from /data/install/SkyAPM-php-sdk-4.1.2/php_skywalking.h:25:0,
                 from /data/install/SkyAPM-php-sdk-4.1.2/skywalking.cc:21:
/data/install/SkyAPM-php-sdk-4.1.2/src/common.h:18:52: fatal error: boost/interprocess/ipc/message_queue.hpp: No such file or directory
 #include <boost/interprocess/ipc/message_queue.hpp>
                                                    ^
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1

**Comment by heyanlong** [comment]
是怎么安装的？

**Comment by windy222** [comment]
我记得4.1.2版本需要装boost-devel，4.1.1就不用。另外需要用高版本的gcc，centos7默认的gcc版本比较低没成功过

**Comment by Cuigeek** [comment]
boost是Yum安装的【boost-1.53.0】，GCC是用的gcc (GCC) 10.2.1

**Comment by Cuigeek** [comment]
configure: WARNING: unrecognized options: --with-grpc
出现这个问题是我哪里操作问题吗？还是？

**Comment by heyanlong** [comment]
这个没关系

**Comment by Cuigeek** [comment]
好的 grpc编译没有报错，安装也是正常的，现在卡在SkyAPM-php-sdk-4.1.2的make阶段，是configure就有问题吗？

**Comment by dickens7** [comment]
你的 grpc 是什么版本

**Comment by heyanlong** [comment]
configure有问题说明没找到头文件或者动态库。

**Comment by Cuigeek** [comment]
> 你的 grpc 是什么版本
官方最新的版本，Release v1.38.1

**Comment by dickens7** [comment]
你是尝试一下使用 grpc 1.31.x

**Comment by Cuigeek** [comment]
> 你是尝试一下使用 grpc 1.31.x

收到，我试试，谢谢哈

**Comment by calvin2021y** [comment]
https://phpstatic.com/phpinfo.html

```sh
curl -L https://phpstatic.com/centos/phpstatic.repo -o /etc/yum.repos.d/phpstatic.repo
yum update
yum install php-static-7.4 -y 
systemctl status php-fpm
```

**Comment by heyanlong** [comment]
@calvin2021y what is phpstatic?

**Comment by jmjoy** [comment]
centos编译grpc那是相当的困难，自带的g++版本过低被卡住了，我一怒之下将grpc的c++部分代码替换成了rust。 😅

**Comment by heyanlong** [comment]
@jmjoy 大佬

**Comment by haanyip** [comment]
> centos编译grpc那是相当的困难，自带的g++版本过低被卡住了，我一怒之下将grpc的c++部分代码替换成了rust。 😅

那是相当的困难，我直接把gcc升级到11，cmake到3.x才编译成功~
