### ISSUE TITLE
get traceId and log it

### ISSUE THREAD

**Issue by mbao** [SkyAPM/SkyAPM-php-sdk#39]
I know I can get traceId and log it in Java.  But with php sdk, how can I do this?
We put all logs in es and get all the call chain logs by searching  traceId.
Thanks.

**Comment by heyanlong** [comment]
Use skyAPM WEB UI

**Comment by mbao** [comment]
> Use skyAPM WEB UI

...But I have something more detail  in my own log, WEB UI has less info.
