### ISSUE TITLE
How to configure SQL parameters

### ISSUE THREAD

**Issue by SZMOFEI** [SkyAPM/SkyAPM-php-sdk#390]
First of all, thank you for taking the time to look at this problem.
I want to know, how to configure the print SQL parameters in PHP, just like in Java agent, implement the following configuration in **agent.config** file can print out the SQL parameters.

`plugin.jdbc.trace_sql_parameters=${SW_JDBC_TRACE_SQL_PARAMETERS:true}
`

So how does PHP fit?

**Comment by heyanlong** [comment]
This is the exclusive function of java agent
