### ISSUE TITLE
Wrong gpr lib version or lib not found

### ISSUE THREAD

**Issue by Alrodemoa** [SkyAPM/SkyAPM-php-sdk#391]
**Describe the bug**

**To Reproduce**

I trying to build Skywalking agent for PHP via PEAR, but i have instantly  error.
Pecl install skywalking
Wrong gpr lib version or lib not found
I rebuilt cmake and grpc for 3 time but it make no difference.
![изображение](https://user-images.githubusercontent.com/40126319/124089947-112e6900-da5d-11eb-84ee-d690ec44e1a3.png)

**Expected behavior**
Skywalking PHP agent installation
**Screenshots**

**PHP (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 7.0.0]
 - PHP ini
PHP 7.4
My OSs Centos 7.9 and Oracle Linux 7.9
gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11) from devtoolset-10
cmake 3.20.0-rc1 built from sources i try with 3.6 but same error
grpc for c++ 1.37.0 stable built from sources, i try with 1.38 - but same error

**SkyWalking (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 6.4]
Skywalking 4.1.2 agent for PHP
**Additional context**

**Comment by heyanlong** [comment]
gRPC was not found in the installation directory

**Comment by Alrodemoa** [comment]
> 
> 
> gRPC was not found in the installation directory

Why is not found?

Installing script detected GRPC and Protobuf files in usr/local. At this path GRPC is present and its files are also presentе. 
![изображение](https://user-images.githubusercontent.com/40126319/124096280-1abacf80-da63-11eb-97a6-90de0cdf9116.png)
Which file need to be searched? What is the grp lib?

**Comment by heyanlong** [comment]
Can you provide me the location of grpc.{so,h}?

**Comment by Alrodemoa** [comment]
> 
> 
> Can you provide me the location of grpc.{so,h}?

/usr/local/include/grpc/grpc.h

Grpcs libs include into /usr/local/lib - what file name for grp lib?

**Comment by heyanlong** [comment]
Try grpc 1.31

**Comment by Alrodemoa** [comment]
> 
> 
> Try grpc 1.31

I finally  built it up. Need to add this line for cmake before compiling grpc -DBUILD_SHARED_LIBS=ON in my case. Thank you and close this task! Have a good day.

**Comment by haanyip** [comment]
> > Try grpc 1.31
> 
> I finally built it up. Need to add this line for cmake before compiling grpc -DBUILD_SHARED_LIBS=ON in my case. Thank you and close this task! Have a good day.

it works for me
