### ISSUE TITLE
 Error in `php': munmap_chunk(): invalid pointer: 0x00007f6fd467f310 ***

### ISSUE THREAD

**Issue by MengyangRen** [SkyAPM/SkyAPM-php-sdk#392]
环境信息：
  OS: centos 7.3
  GRPC安装正常
  PHP 7.3
  protoc --version
  libprotoc 3.13.0
  gcc --version
  gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
  cmake version 3.20.0

编译：
curl -Lo v4.1.1.tar.gz https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v4.1.1.tar.gz
tar zxvf v4.1.1.tar.gz
cd SkyAPM-php-sdk-4.1.1
phpize &&./configure &&make &&make install &&ldconfig /usr/local/lib64

---------------------------------------------------------------------------------------------------------------------------------------------
输入指令：php -m | grep  skywalking ，会有以下报错

*** Error in `php': munmap_chunk(): invalid pointer: 0x00007f6fd467f310 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f7c4)[0x7f6fedd367c4]
/usr/local/lib/libprotobuf.so.24(_ZNSt10_HashtableISsSt4pairIKSsN6google8protobuf25FieldDescriptorProto_TypeEESaIS5_ENSt8__detail10_Select1stESt8equal_toISsESt4hashISsENS7_18_Mod_range_hashingENS7_20_Default_ranged_hashENS7_20_Prime_rehash_policyENS7_17_Hashtable_traitsILb1ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS7_10_Hash_nodeIS5_Lb1EEE+0xc9)[0x7f6fd58d5809]
/usr/local/lib/libprotobuf.so.24(_ZNSt8__detail9_Map_baseISsSt4pairIKSsN6google8protobuf25FieldDescriptorProto_TypeEESaIS6_ENS_10_Select1stESt8equal_toISsESt4hashISsENS_18_Mod_range_hashingENS_20_Default_ranged_hashENS_20_Prime_rehash_policyENS_17_Hashtable_traitsILb1ELb0ELb1EEELb1EEixEOSs+0xad)[0x7f6fd58d600d]
/usr/local/lib64/libprotobuf.so.3.13.0.0(_ZNSt13unordered_mapISsN6google8protobuf25FieldDescriptorProto_TypeESt4hashISsESt8equal_toISsESaISt4pairIKSsS2_EEEixEOSs+0x2e)[0x7f6fd41731e0]
/usr/local/lib64/libprotobuf.so.3.13.0.0(+0x42061f)[0x7f6fd416461f]
/usr/local/lib64/libprotobuf.so.3.13.0.0(+0x42aed4)[0x7f6fd416eed4]
/usr/local/lib64/libprotobuf.so.3.13.0.0(+0x42af07)[0x7f6fd416ef07]
/lib64/ld-linux-x86-64.so.2(+0xf973)[0x7f6ff0f74973]
/lib64/ld-linux-x86-64.so.2(+0x1454e)[0x7f6ff0f7954e]
/lib64/ld-linux-x86-64.so.2(+0xf784)[0x7f6ff0f74784]
/lib64/ld-linux-x86-64.so.2(+0x13b3b)[0x7f6ff0f78b3b]
/lib64/libdl.so.2(+0xeeb)[0x7f6fef64beeb]
/lib64/ld-linux-x86-64.so.2(+0xf784)[0x7f6ff0f74784]
/lib64/libdl.so.2(+0x14ed)[0x7f6fef64c4ed]
/lib64/libdl.so.2(dlopen+0x31)[0x7f6fef64bf81]
php(php_load_shlib+0x13)[0x558f90fa0963]
php(php_load_extension+0x1c7)[0x558f90fa0b67]
php(zend_llist_apply+0x1e)[0x558f9105c3ee]
php(+0x295b5a)[0x558f9100eb5a]
php(php_module_startup+0x7ee)[0x558f9100714e]
php(+0x37f88d)[0x558f910f888d]
php(+0xee00e)[0x558f90e6700e]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f6fedcd9505]
php(+0xee2f5)[0x558f90e672f5]
======= Memory map: ========
558f90d79000-558f911dd000 r-xp 00000000 08:01 3624206                    /usr/bin/php
558f913dc000-558f91468000 r--p 00463000 08:01 3624206                    /usr/bin/php
558f91468000-558f9146a000 rw-p 004ef000 08:01 3624206                    /usr/bin/php
558f9146a000-558f91487000 rw-p 00000000 00:00 0
558f93305000-558f933ef000 rw-p 00000000 00:00 0                          [heap]
7f6fcf532000-7f6fcf533000 r-xp 00000000 08:01 7406420                    /usr/local/lib/libabsl_exponential_biased.so
7f6fcf533000-7f6fcf732000 ---p 00001000 08:01 7406420                    /usr/local/lib/libabsl_exponential_biased.so
7f6fcf732000-7f6fcf733000 r--p 00000000 08:01 7406420                    /usr/local/lib/libabsl_exponential_biased.so
7f6fcf733000-7f6fcf734000 rw-p 00001000 08:01 7406420                    /usr/local/lib/libabsl_exponential_biased.so
7f6fcf734000-7f6fcf736000 r-xp 00000000 08:01 7406430                    /usr/local/lib/libabsl_spinlock_wait.so
7f6fcf736000-7f6fcf935000 ---p 00002000 08:01 7406430                    /usr/local/lib/libabsl_spinlock_wait.so
7f6fcf935000-7f6fcf936000 r--p 00001000 08:01 7406430                    /usr/local/lib/libabsl_spinlock_wait.so
7f6fcf936000-7f6fcf937000 rw-p 00002000 08:01 7406430                    /usr/local/lib/libabsl_spinlock_wait.so
7f6fcf937000-7f6fcf938000 r-xp 00000000 08:01 7406426                    /usr/local/lib/libabsl_log_severity.so
7f6fcf938000-7f6fcfb37000 ---p 00001000 08:01 7406426                    /usr/local/lib/libabsl_log_severity.so
7f6fcfb37000-7f6fcfb38000 r--p 00000000 08:01 7406426                    /usr/local/lib/libabsl_log_severity.so
7f6fcfb38000-7f6fcfb39000 rw-p 00001000 08:01 7406426                    /usr/local/lib/libabsl_log_severity.so
7f6fcfb39000-7f6fcfb3c000 r-xp 00000000 08:01 7406429                    /usr/local/lib/libabsl_raw_logging_internal.so
7f6fcfb3c000-7f6fcfd3b000 ---p 00003000 08:01 7406429                    /usr/local/lib/libabsl_raw_logging_internal.so
7f6fcfd3b000-7f6fcfd3c000 r--p 00002000 08:01 7406429                    /usr/local/lib/libabsl_raw_logging_internal.so
7f6fcfd3c000-7f6fcfd3d000 rw-p 00003000 08:01 7406429                    /usr/local/lib/libabsl_raw_logging_internal.so
7f6fcfd3d000-7f6fcfd44000 r-xp 00000000 08:01 7406413                    /usr/local/lib/libabsl_base.so
7f6fcfd44000-7f6fcff43000 ---p 00007000 08:01 7406413                    /usr/local/lib/libabsl_base.so
7f6fcff43000-7f6fcff44000 r--p 00006000 08:01 7406413                    /usr/local/lib/libabsl_base.so
7f6fcff44000-7f6fcff45000 rw-p 00007000 08:01 7406413                    /usr/local/lib/libabsl_base.so
7f6fcff45000-7f6fcff4a000 r-xp 00000000 08:01 7406427                    /usr/local/lib/libabsl_malloc_internal.so
7f6fcff4a000-7f6fd0149000 ---p 00005000 08:01 7406427                    /usr/local/lib/libabsl_malloc_internal.so
7f6fd0149000-7f6fd014a000 r--p 00004000 08:01 7406427                    /usr/local/lib/libabsl_malloc_internal.so
7f6fd014a000-7f6fd014b000 rw-p 00005000 08:01 7406427                    /usr/local/lib/libabsl_malloc_internal.so
7f6fd014b000-7f6fd019c000 r-xp 00000000 08:01 7408712                    /usr/local/lib/libabsl_time_zone.so 7f6fd019c000-7f6fd039b000 ---p 00051000 08:01 7408712                    /usr/local/lib/libabsl_time_zone.so 7f6fd039b000-7f6fd039c000 r--p 00050000 08:01 7408712                    /usr/local/lib/libabsl_time_zone.so 7f6fd039c000-7f6fd039e000 rw-p 00051000 08:01 7408712                    /usr/local/lib/libabsl_time_zone.so 7f6fd039e000-7f6fd03a2000 r-xp 00000000 08:01 7406416                    /usr/local/lib/libabsl_civil_time.so7f6fd03a2000-7f6fd05a1000 ---p 00004000 08:01 7406416                    /usr/local/lib/libabsl_civil_time.so7f6fd05a1000-7f6fd05a2000 r--p 00003000 08:01 7406416                    /usr/local/lib/libabsl_civil_time.so7f6fd05a2000-7f6fd05a3000 rw-p 00004000 08:01 7406416                    /usr/local/lib/libabsl_civil_time.so7f6fd05a3000-7f6fd05aa000 r-xp 00000000 08:01 7406425                    /usr/local/lib/libabsl_int128.so
7f6fd05aa000-7f6fd07aa000 ---p 00007000 08:01 7406425                    /usr/local/lib/libabsl_int128.so
7f6fd07aa000-7f6fd07ab000 r--p 00007000 08:01 7406425                    /usr/local/lib/libabsl_int128.so
7f6fd07ab000-7f6fd07ac000 rw-p 00008000 08:01 7406425                    /usr/local/lib/libabsl_int128.so
7f6fd07ac000-7f6fd07c0000 r-xp 00000000 08:01 7408710                    /usr/local/lib/libabsl_throw_delegate.so
7f6fd07c0000-7f6fd09bf000 ---p 00014000 08:01 7408710                    /usr/local/lib/libabsl_throw_delegate.so
7f6fd09bf000-7f6fd09c0000 r--p 00013000 08:01 7408710                    /usr/local/lib/libabsl_throw_delegate.so
7f6fd09c0000-7f6fd09c1000 rw-p 00014000 08:01 7408710                    /usr/local/lib/libabsl_throw_delegate.so
7f6fd09c1000-7f6fd09c4000 r-xp 00000000 08:01 7408707                    /usr/local/lib/libabsl_strings_internal.soAborted

**Comment by heyanlong** [comment]
编译安装过程产生的日志发一下。

**Comment by MengyangRen** [comment]
谢谢，这个问题已经解决了,protobuf版本引起的。
目前出另外一个问题
![image](https://user-images.githubusercontent.com/7518545/124931807-23983c00-e035-11eb-9664-edf4da2b4414.png)

**Comment by heyanlong** [comment]
麻烦新开一个issues
