### ISSUE TITLE
现在支持swoole的swoft框架吗？

### ISSUE THREAD

**Issue by xybingbing** [SkyAPM/SkyAPM-php-sdk#393]

**Comment by heyanlong** [comment]
可以提供支持。

**Comment by xybingbing** [comment]
具体怎么支持。

我测试 swoole 原生写可以获取到数据，  使用 swoft框架 获取不到任何数据。

**Comment by heyanlong** [comment]
需要简单添加一点点代码，可以发我一个swoft脚手架吗？

**Comment by xybingbing** [comment]
git仓库：https://github.com/swoft-cloud/swoft

创建一个Swoft项目
composer create-project swoft/swoft Swoft

**Comment by xybingbing** [comment]
![EF86BCE2-3D40-437E-B5DF-9CCD6BD23802](https://user-images.githubusercontent.com/10228562/124718430-adaeaa80-df38-11eb-8e92-934b47a4c2e6.png)
releases中的代码 我改了 php_skywalking.h 文件增加了识别 Swoft 框架可以使用。  但是 我在 master 分支上 无法编译通过 
```
SkyAPM-php-sdk/src/sky_module.cc:140:27: error: use of undeclared identifier 'HOST_NAME_MAX'
            char hostname[HOST_NAME_MAX + 1];

```

**Comment by heyanlong** [comment]
提交一个merge request吧。
