### ISSUE TITLE
php: symbol lookup error: /data/soft/php-7.3.23/lib/php/extensions/no-debug-non-zts-20180731/skywalking.so: undefined symbol: _ZN4absl14lts_2020_09_2313base_internal12SpinLockWaitEPSt6atomicIjEiPKNS1_22SpinLockWaitTransitionENS1_14SchedulingModeE

### ISSUE THREAD

**Issue by Cuigeek** [SkyAPM/SkyAPM-php-sdk#401]
SkyWalking扩展启用后报如下错误：
php: symbol lookup error: /data/soft/php-7.3.23/lib/php/extensions/no-debug-non-zts-20180731/skywalking.so: undefined symbol: _ZN4absl14lts_2020_09_2313base_internal12SpinLockWaitEPSt6atomicIjEiPKNS1_22SpinLockWaitTransitionENS1_14SchedulingModeE

 - OS:  Centos 7.4
 - PHP : php-7.3.23
 - SkyAPM-php-sdk: 4.1.3

**Comment by windy222** [comment]
今天编译了4.1.3, 也遇到了错误:
PHP Warning:  PHP Startup: Unable to load dynamic library '/data/env/php/lib/php/extensions/no-debug-non-zts-20160303/skywalking.so' - /data/env/php/lib/php/extensions/no-debug-non-zts-20160303/skywalking.so: undefined symbol: _ZN4absl14lts_2020_09_2316strings_internal12kBase64CharsE in Unknown on line 0
OS: Centos 7.4
PHP : php-7.1.6
SkyAPM-php-sdk: 4.1.3

**Comment by Frank-JY** [comment]
> SkyWalking扩展启用后报如下错误：
> php: symbol lookup error: /data/soft/php-7.3.23/lib/php/extensions/no-debug-non-zts-20180731/skywalking.so: undefined symbol: _ZN4absl14lts_2020_09_2313base_internal12SpinLockWaitEPSt6atomicIjEiPKNS1_22SpinLockWaitTransitionENS1_14SchedulingModeE
> 
> * OS:  Centos 7.4
> * PHP : php-7.3.23
> * SkyAPM-php-sdk: 4.1.3

我也遇到了这个问题，请问你解决了吗？

**Comment by Frank-JY** [comment]
> 今天编译了4.1.3, 也遇到了错误:
> PHP Warning: PHP Startup: Unable to load dynamic library '/data/env/php/lib/php/extensions/no-debug-non-zts-20160303/skywalking.so' - /data/env/php/lib/php/extensions/no-debug-non-zts-20160303/skywalking.so: undefined symbol: _ZN4absl14lts_2020_09_2316strings_internal12kBase64CharsE in Unknown on line 0
> OS: Centos 7.4
> PHP : php-7.1.6
> SkyAPM-php-sdk: 4.1.3

我也遇到了这个问题，请问你解决了吗？

**Comment by frui85** [comment]
![image](https://user-images.githubusercontent.com/10277372/144592871-2ac11576-41c7-42ce-bc93-e37c1d5faacf.png)
