### ISSUE TITLE
php-fpm启动error

### ISSUE THREAD

**Issue by sunsunzhe** [SkyAPM/SkyAPM-php-sdk#408]
![image](https://user-images.githubusercontent.com/41135795/128143289-436683e1-b032-4b18-91a2-858094d17f5f.png)
php:7.1
skyapm:4.13

**Comment by sunsunzhe** [comment]
> retry master
Don't understand

**Comment by windy222** [comment]
目前release的4.1.3版本会出现类似的情况,用最新的master代码就可以了
