### ISSUE TITLE
成功安装了skywalking拓展，skywalking页面没展示数据

### ISSUE THREAD

**Issue by huange7** [SkyAPM/SkyAPM-php-sdk#412]
![image](https://user-images.githubusercontent.com/48885776/128475515-b063e411-e091-4482-8bec-89abb6423753.png)
一直显示这个，skywalking未接受到数据。

**Comment by heyanlong** [comment]
版本信息发一下

**Comment by huange7** [comment]
skywalking php探针版本为4.1.3。

**Comment by huange7** [comment]
采用自己部署的skywalking可以看到数据了，但是自己研发的去适配skywalking的协议接受不到数据。这里需要注意什么事情吗？

**Comment by heyanlong** [comment]
自己研发的是什么？

**Comment by huange7** [comment]
构建一个GRPC服务器去接收skywalking的上报数据。

**Comment by heyanlong** [comment]
自研的服务端？

**Comment by huange7** [comment]
是的。通过测试发现 ManagerService 的 login 请求一直在发送，但是没有成功。服务器端却没有任何反应，比较难定位

**Comment by heyanlong** [comment]
需要支持服务端协议才行。

**Comment by huange7** [comment]
目前定位到了是服务名的问题。自研的服务端只提供了类似 `/skywalking.v3.ManagementService/reportInstanceProperties`， 而 php 探针的请求地址为：`/ManagementService/reportInstanceProperties`。

**Comment by huange7** [comment]
大佬，手动改了地址。确实可以收到消息了。这里能不能做一个适配呢？
![image](https://user-images.githubusercontent.com/48885776/128858181-1d667daa-2fbf-4e4d-baad-e335a93bc4eb.png)
我自己在每个proto增加了package skywalking.v3; 但是在编译时报错了，应该是包的范围问题，不过较难改正，想向大佬请教下。
![image](https://user-images.githubusercontent.com/48885776/128858447-9dd3d5ff-d272-451f-a1f6-cb806b21d42a.png)

**Comment by heyanlong** [comment]
不要修改proto文件内容。

**Comment by huange7** [comment]
明白，那有没有办法去适配这种类型的请求地址呢？还是得服务器端来适配？服务器采用Go编写的，skywalking提供的go-api的URL都有这种前缀。

**Comment by heyanlong** [comment]
完全没必要自己实现服务端。如果想实现，就必须遵循现有协议
