### ISSUE TITLE
[libprotobuf ERROR /var/local/git/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'SegmentObject.traceId' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

### ISSUE THREAD

**Issue by newpurr** [SkyAPM/SkyAPM-php-sdk#413]
小并发压测swoft服务，间歇出现报错

报错信息如下:
[libprotobuf ERROR /var/local/git/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'SegmentObject.traceId' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[libprotobuf ERROR /var/local/git/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'SegmentObject.traceSegmentId' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[libprotobuf ERROR /var/local/git/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'SegmentObject.service' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[libprotobuf ERROR /var/local/git/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'SegmentObject.serviceInstance' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
2021/08/06-17:43:52 [ERROR] Epet\Http\Server\HttpServer:start(112) onWorkerError

**Comment by heyanlong** [comment]
测试程序发一下。

**Comment by xybingbing** [comment]
@heyanlong    并发时 多个的请求 就进入 sky_request_flush  造成 segment->marshal()  里的对象  SegmentObject.traceId 是空就会报 这个错误。

**Comment by xybingbing** [comment]
并发时可能出现这样的执行情况。 @heyanlong 
![image](https://user-images.githubusercontent.com/10228562/129328309-c75bd365-ac4a-4d56-9d9f-715b0743d976.png)

**Comment by heyanlong** [comment]
为什么会有两遍呢？

**Comment by xybingbing** [comment]
我是 模拟 这个错误的情况。 代码逻辑 可能 会执行  一个request请求  多次执行 sky_request_flush 的情况， 就会报这个错误。

**Comment by newpurr** [comment]
@heyanlong 

下载demo
```bash
git clone https://github.com/swoft-cloud/swoft
cd swoft 
vim swoft/app/Http/Controller/HomeController.php # 添加了一个外部请求
composer update -vvv
php bin/swoft http:start
```


HomeController修改的代码如下:
```php
    /**
     * @RequestMapping("/")
     * @throws Throwable
     */
    public function index(): Response
    {

    var_dump(skywalking_trace_id());

    skywalking_tag("test", "foo", "bar");
    skywalking_log("test", 'info', 'skywalking custom log function skywalking_log(string $key, string $msg[, bool $is_error])', false);

         $getUrl =       function ($url){
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                $output = curl_exec($ch);
                curl_close($ch);
                $output = json_decode($output,true);
                return $output;
        };
	$getUrl("http://www.baidu.com");

        /** @var Renderer $renderer */
        $renderer = Swoft::getBean('view');
        $content  = $renderer->render('home/index');

        return context()->getResponse()->withContentType(ContentType::HTML)->withContent($content);
    }
```


压测脚本:
```bash
wrk -t10 -c100 -d300s --timeout=1s --latency "http://deepin:18306/"
```

**Comment by newpurr** [comment]
![image](https://user-images.githubusercontent.com/19930163/131653002-8933ac9c-6801-4459-b69f-65615a735a5a.png)

**Comment by heyanlong** [comment]
测试一下 4.2.0
