### ISSUE TITLE
在一定请求量的情况下，部分请求出现VirtualNode [Broken] CROSS_PROCESS

### ISSUE THREAD

**Issue by 295black** [SkyAPM/SkyAPM-php-sdk#416]
**Describe the bug**
![image](https://user-images.githubusercontent.com/12394342/129332771-8bd9566d-df3b-4cc3-9f63-003ddd6089d2.png)
![image](https://user-images.githubusercontent.com/12394342/129332797-1dea28d5-22dc-4754-9da8-463c76c90bf1.png)

在几百压测情况下会出现这个问题，也会出现部分丢失现象，最下方的请求没有了。
![image](https://user-images.githubusercontent.com/12394342/129333336-2e9f4d1a-257a-45f9-bcdb-cf2da2301f64.png)

正常请求是这样：
![image](https://user-images.githubusercontent.com/12394342/129333213-09faa1b6-5e22-4da7-92d8-a1807fdf466b.png)

用的master分支

**To Reproduce**

**Expected behavior**

**Screenshots**

**PHP (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 7.0.0]
 - PHP ini

**SkyWalking (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. 6.4]

**Additional context**

**Comment by heyanlong** [comment]
VirtualNode [Broken] 是什么节点？

**Comment by newpurr** [comment]
我也有上述问题，不清楚是什么情况导致的
![image](https://user-images.githubusercontent.com/19930163/129863637-33fbb936-2dbf-42fe-946c-6ce7bdbdd4d0.png)

**Comment by heyanlong** [comment]
所以这个vnode是自动生成的？

**Comment by 295black** [comment]
> 所以这个vnode是自动生成的？

是的，应该是链路中某几个spanId丢失了，UI这边自动填充上去的

**Comment by newpurr** [comment]
> 我也有上述问题，不清楚是什么情况导致的
> ![image](https://user-images.githubusercontent.com/19930163/129863637-33fbb936-2dbf-42fe-946c-6ce7bdbdd4d0.png)

我这边问题已解决，部分数据上报失败导致的，可以考虑是网络或者server吞吐不够导致数据没写入es

**Comment by heyanlong** [comment]
skywalking.log_enable = 1
把trace数据写日志，并上传日志

**Comment by heyanlong** [comment]
是怎么解决的？分享一下

**Comment by newpurr** [comment]
> 是怎么解决的？分享一下

我这边的问题根本原因是网络，解决网络问题就行了。上面这哥们的我猜是OAP Server吞吐不够，压测时上报的数据没被Server成功处理，数据丢失
