### ISSUE TITLE
/opt/SkyAPM-php-sdk/skywalking.c:46:23: fatal error: uuid/uuid.h: No such file or directory

### ISSUE THREAD

**Issue by DavenAaron** [SkyAPM/SkyAPM-php-sdk#42]
tag: 2.0.1

 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/opt/SkyAPM-php-sdk -DPHP_ATOM_INC -I/opt/SkyAPM-php-sdk/include -I/opt/SkyAPM-php-sdk/main -I/opt/SkyAPM-php-sdk -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/opt/SkyAPM-php-sdk/src/grpc -DHAVE_CONFIG_H -std=c++11 -Isrc/report/deps/boost -c /opt/SkyAPM-php-sdk/src/greeter_client.cc  -fPIC -DPIC -o src/.libs/greeter_client.o
/opt/SkyAPM-php-sdk/src/greeter_client.cc:25:53: fatal error: grpc/ApplicationRegisterService.grpc.pb.h: No such file or directory
 #include "grpc/ApplicationRegisterService.grpc.pb.h"
                                                     ^
compilation terminated.
make: *** [src/greeter_client.lo] Error 1

**Comment by heyanlong** [comment]
Retry master version.

**Comment by heyanlong** [comment]
fix in master
