### ISSUE TITLE
开了php的扩展之后，cpu压力明显上升，差不多多用了20%

### ISSUE THREAD

**Issue by 295black** [SkyAPM/SkyAPM-php-sdk#420]
同样配置，同样代码，web4是开启了扩展的，cpu空闲明显下降了20%，是否有可以调优的文档。
![image](https://user-images.githubusercontent.com/12394342/129999360-1f8265ec-d824-4f93-b05c-094dc179d67f.png)

**Comment by kilingzhang** [comment]
有一个优化建议 😂 
看看 @heyanlong  大大有没有时间优化成替换internal_function.handler的方式。
对负载基本没有损耗。接口耗时增加主要在数据上报上面。和拦截execute相比效果明显、亲测有效。

**Comment by heyanlong** [comment]
是个好方法，但是internal_function.handler 工作量有点大啊。。要不要一块写一下。

**Comment by kilingzhang** [comment]
可以 大大先搭个架子  大家一起完善 😂
