### ISSUE TITLE
fatal error: src/network/v3/language-agent/Tracing.pb.h: No such file or directory

### ISSUE THREAD

**Issue by vallbuy** [SkyAPM/SkyAPM-php-sdk#422]
FROM php:7.3-fpm-alpine

#复制源
COPY ./repositories /etc/apk/repositories

RUN echo "https://mirrors.ustc.edu.cn/alpine/v.3.11/main" > /etc/apk/repositories
RUN echo "https://mirrors.ustc.edu.cn/alpine/v.3.11/community" >> /etc/apk/repositories

RUN set -ex \
	&& apk add --update --no-cache autoconf g++ protobuf-dev grpc-dev curl-dev make re2c boost-dev
	# installing skywalking
	&& pecl install skywalking \
	&& docker-php-ext-enable skywalking

running: make
/bin/sh /tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/include -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/src -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/src/network/v3  -DHAVE_CONFIG_H  -g -O2 -Wall -std=c++11 -Wno-deprecated-register   -c /tmp/pear/temp/skywalking/skywalking.cc -o skywalking.lo
mkdir .libs
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/pear/temp/skywalking -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/include -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/main -I/tmp/pear/temp/skywalking -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/src -I/tmp/pear/temp/pear-build-defaultuserCDhoam/skywalking-4.1.2/src/network/v3 -DHAVE_CONFIG_H -g -O2 -Wall -std=c++11 -Wno-deprecated-register -c /tmp/pear/temp/skywalking/skywalking.cc  -fPIC -DPIC -o .libs/skywalking.o
In file included from /tmp/pear/temp/skywalking/src/sky_utils.h:19,
                 from /tmp/pear/temp/skywalking/skywalking.cc:23:
/tmp/pear/temp/skywalking/src/segment.h:23:10: fatal error: src/network/v3/language-agent/Tracing.pb.h: No such file or directory
   23 | #include <src/network/v3/language-agent/Tracing.pb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:194: skywalking.lo] Error 1
ERROR: `make' failed

**Comment by heyanlong** [comment]
configure阶段出错了

**Comment by vallbuy** [comment]
pecl install skywalking 如何能正常完成

**Comment by xiewenbin29** [comment]
我也遇到了同样的问题，我的是php7.4
