### ISSUE TITLE
请问最新版本支持概率采集了吗

### ISSUE THREAD

**Issue by blue110** [SkyAPM/SkyAPM-php-sdk#425]
请问最新版本支持概率采集了吗

**Comment by blue110** [comment]
> > > #415
> > 
> > 
> > 支持rate_limit (共享内存方式性能太差，采用一个进程一个限速器的方式。举例：如果php-fpm进程数是100，那么限速 100QPS的设置为：skywalking.sample_n_per_3_secs=3， 小于1为不限速)
> > 限速是指全量排队发消息，还是说100限速，超过100的会不发送消息到采集端？
> 
> 是限制的采集，比如，限速100QPS，那么超过100QPS的数据就直接不采集了。

master的版本采集不到数据 换成旧版本就可以采集  这是我配置的问题还是？

**Comment by heyanlong** [comment]
设置是什么？

**Comment by heyanlong** [comment]
skywalking.sample_n_per_3_secs
