### ISSUE TITLE
swoole服务上报链路是断开的？

### ISSUE THREAD

**Issue by Frank-JY** [SkyAPM/SkyAPM-php-sdk#428]
一、调用关系curl包 -> 服务A -> 服务B
二、平台显示结果：
1、服务A一个链路
2、服务B一个链路

链路上的traceId不一样

**Comment by Frank-JY** [comment]
[swoole-easy.zip](https://github.com/SkyAPM/SkyAPM-php-sdk/files/7143006/swoole-easy.zip)
调用链：http_server 调用 http_server2
但是skywalking打印日志的traceId没有关联


日志：
`write success {"traceId":"669bce110ff345d3532e668e55773124.49404.2300871409","traceSegmentId":"669bce110ff345d3532e668e55773124.49404.2300871409","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1631267591376","endTime":"1631267591378","refs":[],"operationName":"/","peer":"9.223.35.165:29501","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"php-price","serviceInstance":"0d810dc5-e09f-2258-9c51-5568c88cb2a2@9.223.35.165","isSizeLimited":false}
write success {"traceId":"40c9201c8e96ca3d6393fe38dd308d97.54669.3172066519","traceSegmentId":"40c9201c8e96ca3d6393fe38dd308d97.54669.3172066519","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1631267591378","endTime":"1631267591378","refs":[],"operationName":"/","peer":"127.0.0.1:29502","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"php-price","serviceInstance":"48c0d641-7ab9-b935-bb65-83d3e5fc28bf@9.223.35.165","isSizeLimited":false}`

**Comment by Frank-JY** [comment]
> 提供一个PHP的例子吧，我本地运行一下

麻烦看下，预计是我编译的so有问题？

**Comment by Frank-JY** [comment]
new Swoole\Coroutine\Http\Client进行远程调用例子：

<?php

$http = new Swoole\Http\Server('0.0.0.0', 29504);

$http->on('Request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
 $url = 'http://baidu.com:80';
    $data = parse_url($url);
    $cli = new Swoole\Coroutine\Http\Client($data['host'], $data['port'], $data['scheme'] == 'https' ? true : false);
    $cli->setDefer(true);
    $ret = $cli->post("/", "testing");
    $cli->recv();
    $body = $cli->body;
    echo $body;
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->start();

**Comment by Frank-JY** [comment]
new Swoole\Coroutine\Http\Client进行远程调用例子：

`$http = new Swoole\Http\Server('0.0.0.0', 29504);

$http->on('Request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
 $url = 'http://baidu.com:80';
    $data = parse_url($url);
    $cli = new Swoole\Coroutine\Http\Client($data['host'], $data['port'], $data['scheme'] == 'https' ? true : false);
    $cli->setDefer(true);
    $ret = $cli->post("/", "testing");
    $cli->recv();
    $body = $cli->body;
    echo $body;
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->start();
~                    `

**Comment by Frank-JY** [comment]
new Swoole\Coroutine\Http\Client进行远程调用例子：

`<?php

$http = new Swoole\Http\Server('0.0.0.0', 29504);

$http->on('Request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
 $url = 'http://baidu.com:80';
    $data = parse_url($url);
    $cli = new Swoole\Coroutine\Http\Client($data['host'], $data['port'], $data['scheme'] == 'https' ? true : false);
    $cli->setDefer(true);
    $ret = $cli->post("/", "testing");
    $cli->recv();
    $body = $cli->body;
    echo $body;
    $response->end('Hello Swoole. #' . rand(1000, 9999));
});

$http->start();`

**Comment by Frank-JY** [comment]
write success {"traceId":"ccbfd8021903b009bda1bad76669ef0b.21961.1970405757","traceSegmentId":"ccbfd8021903b009bda1bad76669ef0b.21961.1970405757","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1631275481868","endTime":"1631275481964","refs":[],"operationName":"/","peer":"9.223.35.165:29504","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"php-price","serviceInstance":"43e6de02-7d13-564c-a9ef-78855cef03a3@9.223.35.165","isSizeLimited":false}

----------
没有调用baidu.com的信息

**Comment by heyanlong** [comment]
看样子是没收集到信息

**Comment by Frank-JY** [comment]
> 看样子是没收集到信息

上面的demo，你们运行后能正常收集到信息吗

**Comment by Frank-JY** [comment]
使用curl_init能收集到链路信息，但是swoole框架下的Swoole\Coroutine\Http\Client无法收集到调用链路信息。请问目前的skywalking版本支持Swoole\Coroutine\Http\Client吗

**Comment by heyanlong** [comment]
支持

**Comment by Frank-JY** [comment]
> 支持

请问您那边运行demo能收集到链路信息吗

**Comment by Frank-JY** [comment]
您好，我这边进行了验证，master代码编译出来的so，还是无法完整收集到Swoole\Coroutine\Http\Client的信息。请问有解决方法吗？

**Comment by blue110** [comment]
> 一、调用关系curl包 -> 服务A -> 服务B
> 二、平台显示结果：
> 1、服务A一个链路
> 2、服务B一个链路
> 
> 链路上的traceId不一样

你swoole接skywating skywating用的是哪个版本的 我用最新的版本采集不到数据 用旧版本可以 但是旧版本没有限流采集

**Comment by Frank-JY** [comment]
> > 一、调用关系curl包 -> 服务A -> 服务B
> > 二、平台显示结果：
> > 1、服务A一个链路
> > 2、服务B一个链路
> > 链路上的traceId不一样
> 
> 你swoole接skywating skywating用的是哪个版本的 我用最新的版本采集不到数据 用旧版本可以 但是旧版本没有限流采集

master版本
