### ISSUE TITLE
Impossible to build with shared grpc library

### ISSUE THREAD

**Issue by remicollet** [SkyAPM/SkyAPM-php-sdk#429]
> configure: error: skywalking extension requires gRPC extension, add --with-grpc=DIR

1st: message looks strange, this is not grpc "extension", but grpc "library" which is searched for (both exists)

> SEARCH_GRPC_FOR="libgrpc.a libgpr.a libgrpc++.a libupb.a libaddress_sorting.a third_party/protobuf/libprotobuf.a"

On package distribution none of this file are available
(only the shared libraries, so the .so files)

This was ok with previous version

This is related to ecbb2f16fe90f0e90d236e303f2e4381aa1f7431

Please allow building with shared libraries

**Comment by remicollet** [comment]
4.2.0 is still totally broken, unable to build

**Comment by remicollet** [comment]
A simple revert to config.m4 from 4.1.2 works

**Comment by heyanlong** [comment]
need 4.2.1
