### ISSUE TITLE
when GA-6.0 finish?

### ISSUE THREAD

**Issue by goerzh** [SkyAPM/SkyAPM-php-sdk#43]
I found that some things of GA-6.0 were not completed.
1. sw6 http head
2. Register instance
3. Tracesegment report

Is it usable?

**Comment by goerzh** [comment]
@heyanlong when support?

**Comment by heyanlong** [comment]
Summer of 2019

**Comment by goerzh** [comment]
@heyanlong I have already implemented it.  #49

**Comment by goerzh** [comment]
@heyanlong  You can test and merge :)

**Comment by heyanlong** [comment]
Today
