### ISSUE TITLE
能否增强下数据收集

### ISSUE THREAD

**Issue by zhaodp** [SkyAPM/SkyAPM-php-sdk#431]
1：sql 参数收集
2: post请求可以支持body收集

**Comment by heyanlong** [comment]
举个例子。

**Comment by Frank-JY** [comment]
> 举个例子。

我也有这样的需求，希望能上报请求包和返回包

**Comment by zhaodp** [comment]
@heyanlong 我给你QQ留言了，你看下~

**Comment by zhaodp** [comment]
Java的agent我已经搞定了，就差PHP的了~

**Comment by heyanlong** [comment]
请求和返回会导致trace太大。

**Comment by zhaodp** [comment]
> 

我们主要在测试环境用，我们的调用链太复杂

**Comment by zhaodp** [comment]
orig_curl_exec(INTERNAL_FUNCTION_PARAM_PASSTHRU);
加了段代码，可以收集到response内容了，请教下，怎么能收集到curl http post的 body内容

**Comment by heyanlong** [comment]
我加一个参数吧。是收集发送的还是返回的？

**Comment by zhaodp** [comment]
最好发送的和返回的都能收集，谢谢大神

**Comment by zhaodp** [comment]
这样的话我们在测试环境开启收集，在生成环境关闭就可以了

**Comment by zhaodp** [comment]
orig_curl_exec(INTERNAL_FUNCTION_PARAM_PASSTHRU);
    if(Z_TYPE_P(return_value) == IS_STRING && Z_STRLEN_P(return_value) > 0){
      zval tmp;
      ZVAL_COPY(&tmp, return_value);
      span->addTag("resp", Z_STRVAL_P(&tmp));
    }

**Comment by zhaodp** [comment]
orig_curl_exec(INTERNAL_FUNCTION_PARAM_PASSTHRU);
    if(Z_TYPE_P(return_value) == IS_STRING && Z_STRLEN_P(return_value) > 0){
      zval tmp;
      ZVAL_COPY(&tmp, return_value);
      span->addTag("resp", Z_STRVAL_P(&tmp));
    }
我自己加代码修改curl插件，用于收集返回的数据，但是有些接口会出错，不知道神马情况

**Comment by zhaodp** [comment]
真是神速啊

**Comment by zhaodp** [comment]
pull request什么时候merge到master啊

**Comment by AlpherJang** [comment]
等ci跑完
