### ISSUE TITLE
终于安装成功，但ui中却没有数据展示

### ISSUE THREAD

**Issue by chengok888** [SkyAPM/SkyAPM-php-sdk#453]
![image](https://user-images.githubusercontent.com/35942250/144403269-5dad125f-f6f7-4d27-8aa4-07a639534a50.png)
![image](https://user-images.githubusercontent.com/35942250/144403402-490b4016-5128-49cb-84f3-f55b166c2766.png)
前端ui中没有数据，php-fpm的log中有个截图中的报错信息:“skywalking.so: undefined symbol”

系统版本
centos:7.7
php:7.3.33
skywallking-server: apache-skywalking-apm-es7-8.7.0

**Comment by heyanlong** [comment]
Need to provide a complete compilation command and output

**Comment by frui85** [comment]
编译静态库方式php71 pecl 安装的 php-sdk-agent 4.2.0 可以正常安装，但是无上报数据，并且数据使用es时无法创建索引~java-agent 可以正常创建索引。h2库 不报数据库错误但是，还是无法显示上报数据。使用动态库方式，会报 缺少 libgrpc.a

**Comment by frui85** [comment]
![image](https://user-images.githubusercontent.com/10277372/144746582-cb03776e-2da9-4dcf-9ac8-f875a5681b68.png)

安装测试基本不同版本，对应编译了 protoc 对应了不同的版本。
测试 静态库方式，先按动态库方式安装 protocbuf， 以后编译过程显示引用了protoc ，最后编译安装php71 版本的 php-skywalking-agent , 修改了 php.ini 会显示shang'shu上述错误

**Comment by heyanlong** [comment]
参考一下dockerfile

**Comment by frui85** [comment]
好的，我试试，这个支持 skywalking 8.9.0 吗

**Comment by heyanlong** [comment]
支持
