### ISSUE TITLE
开启一下日志

### ISSUE THREAD

**Issue by donallin823** [SkyAPM/SkyAPM-php-sdk#459]
开启一下日志

_Originally posted by @heyanlong in https://github.com/SkyAPM/SkyAPM-php-sdk/issues/458#issuecomment-1002433922_

开启sky-php-agent吗，还是report-agent；容器内具体在哪个位置开启

**Comment by heyanlong** [comment]
```
; php.ini
skywalking.log_enable = 1
skywalking.log_path = /tmp/skywalking-php.log
```
