### ISSUE TITLE
能否支持追踪PHP CLI 模式的请求

### ISSUE THREAD

**Issue by Adrian200789** [SkyAPM/SkyAPM-php-sdk#463]
项目中一些场景用到了定时任务，该场景使用php cli方式触发请求，这个方式调用能否支持追踪和采集？

**Comment by heyanlong** [comment]
不支持

**Comment by Adrian200789** [comment]
不支持是出于哪方面的考虑呢
当前有定时任务和队列消费场景，会用到cli模式，能否给出一些建议和sdk源码改造的思路，以便评估和代码贡献




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkyAPM/SkyAPM-php-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SkyAPM/SkyAPM-php-sdk] 能否支持追踪PHP CLI 模式的请求 (Issue #463)





 
不支持
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heyanlong** [comment]
因为cli任务不好确定什么时候结束

**Comment by kilingzhang** [comment]
如果业务可以接受代码入侵的话，可以封装一下开始和结束部分的代码。然后暴露给php主动调用，不过这里需要注意处理好内存分配，否则会有内存泄漏的问题。
