### ISSUE TITLE
你好，想问下我是什么步骤错了，只有端点没有数据记录

### ISSUE THREAD

**Issue by silie666** [SkyAPM/SkyAPM-php-sdk#466]
![image](https://user-images.githubusercontent.com/38691833/151518662-40cb66de-e5af-4c28-8b3f-1b72f4ff5583.png)

sdk4.2.0和sdk3.3.2都试了，页面上还是什么数据都没有

### 环境：
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
PHP 7.0.33
skywalking8.9.1和skywalking8.5.0都试过
由于网络问题，grpc拉不下来，我是使用别的压缩包装的（这个原因未验证）

### php运行模式
![image](https://user-images.githubusercontent.com/38691833/151519629-c7ff456e-a7f2-41f6-ac72-b9733451fa77.png)

### 首先是使用sdk3.3.2，代码已经拉下来并且已经编译运行
![image](https://user-images.githubusercontent.com/38691833/151519011-46079a55-63de-4440-b33d-a775f44f8fc9.png)

### php配置文件
![image](https://user-images.githubusercontent.com/38691833/151519124-80969403-5af7-4510-8549-2d5837c654e9.png)

### 日志文件记录
write success {"traceId":"dad8f333605051504d74c0d17839ccef.5859.247146708","traceSegmentId":"dad8f333605051504d74c0d17839ccef.5859.247146708","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1643361464707","endTime":"1643361464708","refs":[],"operationName":"/favicon.ico","peer":"api.test.com:80","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/favicon.ico"},{"key":"http.method","value":"GET"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"php-sky","serviceInstance":"41a5a084-f0cc-f23d-d1e8-7b70a52df575@172.22.148.6","isSizeLimited":false}
write success {"traceId":"17bcbe14a8dbe6d367e522527022a5fa.5858.639309059","traceSegmentId":"17bcbe14a8dbe6d367e522527022a5fa.5858.639309059","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1643361535829","endTime":"1643361535829","refs":[],"operationName":"/","peer":"www.test.com:80","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/"},{"key":"http.method","value":"GET"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"php-sky","serviceInstance":"41a5a084-f0cc-f23d-d1e8-7b70a52df575@172.22.148.6","isSizeLimited":false}
![image](https://user-images.githubusercontent.com/38691833/151520449-92a6767f-857c-46a4-ae46-5a04264538ff.png)

### php配置
![image](https://user-images.githubusercontent.com/38691833/151520222-7cb7922d-5f40-4684-9e8b-c8201b04519a.png)

### skywalking也没有报错
![image](https://user-images.githubusercontent.com/38691833/151521035-c00dad44-f890-407c-8824-55e02c400473.png)

**Comment by heyanlong** [comment]
看样子4.2.2是安装成功的

**Comment by silie666** [comment]
> 看样子4.2.2是安装成功的

我通过docker安装也是一样的，没有数据
命令：
`docker run --name php-test --restart always -d -p 8081:8080 -e SW_OAP_ADDRESS=172.17.128.82:11800 skyapm/skywalking-php  `

浏览器访问8081
![image](https://user-images.githubusercontent.com/38691833/152304698-66ea0910-2de3-4b9a-b8bb-3b78385933b1.png)

docker日志输出也没有报错
![image](https://user-images.githubusercontent.com/38691833/152304411-2f32da56-6edf-4c53-ae35-cef9e11a902b.png)

仍然是什么都没有
![image](https://user-images.githubusercontent.com/38691833/152304965-ab982139-f6a5-48bb-8918-672d13e7fc8c.png)

**Comment by heyanlong** [comment]
看当前服务已经存在了，看看追踪里面有没有

**Comment by silie666** [comment]
> 看当前服务已经存在了，看看追踪里面有没有

emm....，过一会就有数据了，可能我急了点没刷新😢
