### ISSUE TITLE
pecl install skywaking failed

### ISSUE THREAD

**Issue by YazaiHu** [SkyAPM/SkyAPM-php-sdk#467]
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/5022856/152751723-57898731-1db3-4bb2-bb8e-78d175edfc05.png">
protobuf,grpc have installed,and then use pecl install skywalking extension failed,how to solve it? thanks

**Comment by heyanlong** [comment]
Need to install gRPC dynamic library

**Comment by YazaiHu** [comment]
> gRPC dynamic library

I have done this:  brew install grpc, pecl install grpc, then I use pecl install skywalking,it failed. how to do? thanks.

**Comment by YazaiHu** [comment]
> Need to install gRPC dynamic library
@heyanlong 
can you tell me how to solve this problem? let me make it success by the command: pecl install skywalking, thanks.

**Comment by YazaiHu** [comment]
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/5022856/152918661-27323fc4-8dd2-4e78-9cc0-857004704fa3.png">
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/5022856/152918712-725b8113-1217-4727-b950-a7368978f817.png">
This is my install command.

**Comment by YazaiHu** [comment]
> <img alt="image" width="1322" src="https://user-images.githubusercontent.com/5022856/152918661-27323fc4-8dd2-4e78-9cc0-857004704fa3.png">
> 
> <img alt="image" width="1306" src="https://user-images.githubusercontent.com/5022856/152918712-725b8113-1217-4727-b950-a7368978f817.png">
> 
> This is my install command.

@heyanlong

**Comment by YazaiHu** [comment]
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/5022856/152918804-2bf21423-04d1-458a-9ce6-86ad38619b75.png">
Final result.

**Comment by heyanlong** [comment]
Maybe you should link /usr/local/include/grpc -> /usr/local/opt/grpc/include

**Comment by YazaiHu** [comment]
>


> 



> Maybe you should link /usr/local/include/grpc -> /usr/local/opt/grpc/include

Nope!

**Comment by heyanlong** [comment]
See this document https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/BUILDING.md
