### ISSUE TITLE
大并发请求redis导致sky报错::sky_request_flush message_queue exNo such file or directory

### ISSUE THREAD

**Issue by lvxiao1** [SkyAPM/SkyAPM-php-sdk#468]
系统信息:
- 镜像: php:7.0.33-fpm-stretch
- SkyAPM-php-sdk版本: 4.2.0
- grpc: 1.34x

用ab压测开始时能正常上报数据, 一段时间sky无法接收到数据，查看sdk日志报错`sky_request_flush message_queue exNo such file or directory`，但是重启fpm后问题不会再重现， 重启命令`ps -ef|grep php-fpm|grep master|grep -v grep|awk '{print $2}'|xargs kill -USR2`
` ab -n 10000 -c 50 http://127.0.0.1:18880/redis.php`
- 启动命令: `/usr/local/sbin/php-fpm -R --nodaemonize`
- redis.php 文件
```php
<?php
  
   $redis = new Redis();
   $redis->connect('127.0.0.1', 6379);
   echo "Connection to server successfully";

   $redis->lpush("tutorial-list", "Redis");
   $redis->lpush("tutorial-list", "Mongodb");
   $redis->lpush("tutorial-list", "Mysql");
   $arList = $redis->lrange("tutorial-list", 0 ,5);
   echo "Stored string in redis";
   print_r($arList);
?>
```
- dockerfile
```dockerfile
FROM php:7.0.33-fpm-stretch

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib64
ENV LD_RUN_PATH=$LD_RUN_PATH:/usr/local/lib:/usr/local/lib64
ENV WORKDIR /webser/www
ENV GROUP_NAME test
ENV SERVICE_NAME skywalking
WORKDIR /webser/www

RUN  sed -i "s/deb.debian.org/mirrors.163.com/g" /etc/apt/sources.list \
    && sed -i "s/security.debian.org/mirrors.163.com/g" /etc/apt/sources.list \
    && apt-get clean \
    && apt-get update --fix-missing \
    && apt-get install -y build-essential autoconf automake libtool curl make g++ unzip pkg-config cmake libboost-all-dev libcurl4-openssl-dev zlib1g-dev nginx git \
    && docker-php-ext-install zip \
    && pecl channel-update pecl.php.net \
    && pecl install redis  \
    && docker-php-ext-enable  redis

RUN git clone --depth 1 -b v1.34.x https://github.com/grpc/grpc.git /var/local/git/grpc \
    && cd /var/local/git/grpc \
    && git submodule update --init --recursive \
    && mkdir -p cmake/build \
    && cd cmake/build \
    && cmake ../.. \
    && make -j$(nproc) \
    && echo "--- INSTALL skywalking php ---" \
    && cd /var/local/git  \
    && curl -Lo v4.2.0.tar.gz https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v4.2.0.tar.gz  \
    && tar zxvf v4.2.0.tar.gz \
    && cd SkyAPM-php-sdk-4.2.0 \
    && phpize && ./configure --with-grpc=/var/local/git/grpc && make && make install \
    && rm -fr /var/local/git \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && mkdir -pv /data/log /var/log/php /webser/www /var/tmp/nginx

COPY php.ini /usr/local/etc/php/conf.d/
COPY www.conf /usr/local/etc/php-fpm.d/
COPY nginx.conf /etc/nginx/
COPY app.conf /etc/nginx/conf.d/app.conf

COPY run.sh /tmp/
COPY reload-php-ini.sh /tmp/

RUN chmod +x /tmp/run.sh  \
    && chmod +x /tmp/reload-php-ini.sh

EXPOSE 18880
ENTRYPOINT ["/tmp/run.sh"]
```
- php.ini
```ini
extension=skywalking.so
skywalking.app_code = ${GROUP_NAME}::${SERVICE_NAME}
skywalking.enable = 1
skywalking.version = 8
skywalking.log_enable = 1
skywalking.grpc = ${SKYWALKING_SERVER_ADDR}
skywalking.error_handler_enable = 0
skywalking.log_path = /data/log/skywalking.log
skywalking.mq_max_message_length = 1048500
```
- www.conf 
```
[www]
user = root
group = root
listen = 0.0.0.0:9000
 
pm = static
pm.max_children = 5
slowlog = /data/php-slow.log
request_slowlog_timeout = 5s
request_terminate_timeout = 20s

clear_env = no
catch_workers_output = yes
php_admin_flag[expose_php] = off


[global]
error_log = /data/php-error.log
```

**Comment by heyanlong** [comment]
This happens when resources are insufficient.

**Comment by heyanlong** [comment]
What is the `ulimit`

**Comment by lvxiao1** [comment]
root@e125c400e345:/data/log# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 39834
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by lvxiao1** [comment]
@heyanlong 
我调试发现是`boost::interprocess::message_queue`被删除才会报`sky_request_flush message_queue exNo such file or directory`,  但是sky_module_cleanup方法没有被调用过，什么情况下这个队列会被删除呢？ 还有我reload fpm之后加几倍的压力进行压测也没出现这种情况

**Comment by heyanlong** [comment]
正常来说，queue不会莫名其妙被删除

**Comment by lvxiao1** [comment]
我在创建、删除和打开`message_queue`加了日志， 正常上报两次之后就会报错， 查看了下/dev/shm skywalking_queue_12 确实被删除了
![image](https://user-images.githubusercontent.com/13183021/153529015-a7086409-b54e-4103-96d0-c4f34980a0b5.png)

![image](https://user-images.githubusercontent.com/13183021/153528791-19540c3c-7a56-4d86-bec3-9ab627b6c213.png)

**Comment by heyanlong** [comment]
看来需要添加个重新创建机制。。要不要提交个pr？

**Comment by lvxiao1** [comment]
@heyanlong 可以，但莫名其妙被删除， 如果加上重新创建机制，会不会一直删除重建，不断申请和释放共享内存而影响性能

**Comment by lvxiao1** [comment]
目前问题已经排查出来了，由于nginx配置了`fastcgi_cache_path /dev/shm`，导致nginx回收时把 `/dev/shm`下的共享内存全清空了。最终配置成 `fastcgi_cache_path /dev/shm/cache` 解决问题
![image](https://user-images.githubusercontent.com/13183021/153746134-7b9d5453-9dc7-4fc3-82a9-30e56366f41a.png)
![image](https://user-images.githubusercontent.com/13183021/153794538-6a4bc115-d9b1-45f7-9cce-748e8e306319.png)

**Comment by lvxiao1** [comment]
> @heyanlong 看来需要添加个重新创建机制。。要不要提交个pr？

消费者的接收是阻塞的，但`message_queue`不会监听shm回收，并且`message_queue.remove`方法也不会`notify`，所以会导致无限期的等待下去。
是否可以换成`timed_receive`, 设置成一秒超时， 如果返回true就继续读取，返回`false`则重新打开`message_queue`， 捕获到`not_such_file_or_directory`异常重新创建队列
![image](https://user-images.githubusercontent.com/13183021/153795622-680ed843-8a44-455a-9bb4-d75dce51c38e.png)
![image](https://user-images.githubusercontent.com/13183021/153795818-41f7b0a3-61be-4a5e-809b-5a1b66386e58.png)

**Comment by heyanlong** [comment]
提交个pr吧
