### ISSUE TITLE
当skywalking的服务端挂掉后，整个php访问会中断，http反回状码是200但是没有回传数据

### ISSUE THREAD

**Issue by tzwken** [SkyAPM/SkyAPM-php-sdk#475]
skywalking拓展错误信息。
![image](https://user-images.githubusercontent.com/65268273/154430260-c9d4513f-deab-46eb-bfa0-e0ea8a1e2fdc.png)

curl 请求时的错信息。
![image](https://user-images.githubusercontent.com/65268273/154430553-cf1344d7-af53-4213-9dad-b51fb9a5af6a.png)

**Comment by heyanlong** [comment]
环境发一下

**Comment by heyanlong** [comment]
发一下coredump

**Comment by tzwken** [comment]
系统： Debian GNU/Linux 10

PHP 7.2.29 (cli) (built: Mar 20 2020 01:40:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.29, Copyright (c) 1999-2018, by Zend Technologies

index.php文件内容  
<?php
$ch = curl_init();
$timeout = 5;
curl_setopt($ch, CURLOPT_URL, 'http://www.baidu.com');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
$file_contents = curl_exec($ch);
curl_close($ch);
echo $file_contents;
?>

没有产生coredump文件

**Comment by tzwken** [comment]
core文件
[core.1014.gz](https://github.com/SkyAPM/SkyAPM-php-sdk/files/8087226/core.1014.gz)

**Comment by heyanlong** [comment]
你本地使用gdb coredump执行bt看看堆栈？

**Comment by tzwken** [comment]
![image](https://user-images.githubusercontent.com/65268273/154452158-eea43c02-442f-467e-b5c6-1eab66278605.png)
![image](https://user-images.githubusercontent.com/65268273/154452266-220d8c42-bd01-490b-83b6-2fa7824c4060.png)

**Comment by tzwken** [comment]
你可以自己测试一下。把skywalking的grpc地址配置一个不通的IP，发起请求，就会出现上边的问题。

**Comment by heyanlong** [comment]
好的

**Comment by heyanlong** [comment]
可以编译一个debug版本看看bt显示的行号

**Comment by tzwken** [comment]
core问题找到了，是和swoole有关。
下边这个传输问题还是没有找到，没有产生core文件，请求依然会出现下边错误。只显示头信息时是502状态码。
`* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining`

**Comment by tzwken** [comment]
当连接不到skywalking的server时，会导至php子进程退出
请求前进程
![image](https://user-images.githubusercontent.com/65268273/155114780-1b5b182f-4883-4235-a1fd-f9e487ce77ca.png)
多次请求后所有子进程全部退出重启
![image](https://user-images.githubusercontent.com/65268273/155114906-79e0ccec-cd36-4512-9c2a-39960611fe98.png)

**Comment by heyanlong** [comment]
coredump 显示什么问题？

**Comment by frui85** [comment]
我也是这问题。。。4.2.0

**Comment by frui85** [comment]
grpc 1.34.x 
protoc  1.13.0
