### ISSUE TITLE
【查看日志】按钮中的日志内容，怎么写入？

### ISSUE THREAD

**Issue by liamhao** [SkyAPM/SkyAPM-php-sdk#481]
SkyWalking中【查看日志】按钮，显示的日志内容，该怎么写入？需要以什么样的法式写入？需要针对这个扩展做二次开发吗？
![image](https://user-images.githubusercontent.com/31812811/161295814-269feac2-6467-4014-8239-c1478d4ca478.png)
默认安装完后，链路跟踪是可以用的，只是请求的日志都是空的。
![image](https://user-images.githubusercontent.com/31812811/161296142-3c1d5a68-5128-4a57-9179-6b954ade635f.png)
php扩展生成的json数据格式，其中的`logs`是空的
![image](https://user-images.githubusercontent.com/31812811/161297849-475792bb-ea2f-4d1f-a23b-6eee60c46897.png)

**Comment by heyanlong** [comment]
```php
skywalking_log(string key, string log [, bool is_error]) 
```

**Comment by liamhao** [comment]
> ```
> skywalking_log(string key, string log [, bool is_error]) 
> ```

感谢，哪里有文档能看到全部的扩展里有哪些函数方法吗？

**Comment by liamhao** [comment]
@heyanlong  还有个关于构建 Docker 镜像的问题，我通过此项目的 [Dockerfile](https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docker/Dockerfile) 文件的样纸，自己构建了一个镜像，但构建后的镜像有 3G 左右，请问，分段构建的话，该怎么写才能减小体积呢？

**Comment by heyanlong** [comment]
主要是grpc和protoc依赖太大

**Comment by liamhao** [comment]
> 主要是grpc和protoc依赖太大

那还请问下，grpc和protoc的依赖都在哪些文件夹？你们docker仓库的镜像是怎么压缩到100多兆的呢？还请多指点一些。
