### ISSUE TITLE
 configure: error: not found /var/local/git/grpc/cmake/build/libgrpc.a

### ISSUE THREAD

**Issue by wyfaq** [SkyAPM/SkyAPM-php-sdk#484]
按动态编译的方式grpc没有报错，但是在编译php agent的时候找不到libgrpc.a。对应目录下确实也没有该文件
ubuntu18，php7.1，cmake 3.19.1
```bash
root@xx-2:/var/local/git/SkyAPM-php-sdk-4.2.0# phpize 
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303

root@xx-2:/var/local/git/SkyAPM-php-sdk-4.2.0# ./configure --with-grpc="/var/local/git/grpc" 
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20160303
checking for PHP installed headers prefix... /usr/include/php/20160303
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether to enable skywalking support... yes, shared
checking whether C++ compiler accepts -std=c++0x... yes
checking for php_json.h... found in /usr/include/php/20160303
checking for grpc files in /var/local/git/grpc path... configure: error: not found /var/local/git/grpc/cmake/build/libgrpc.a
```

**Comment by wyfaq** [comment]
agent: SkyAPM-php-sdk-4.2.0

**Comment by sunny5156** [comment]
问题解决了吗 ？ @wyfaq

**Comment by heyanlong** [comment]
需要先静态编译grpc

**Comment by frui85** [comment]
----安装 grpc1.46.3 -----

系统环境：CentOS Linux release 7.9.2009 (Core)
gcc version 11.2.1 20210728 (Red Hat 11.2.1-1) (GCC)
cmake version 3.23.2

安装步骤：
1. 安装gcc
sudo yum install centos-release-scl
sudo yum install devtoolset-11
scl enable devtoolset-11 bash
gcc --version

2. 安装cmake
wget https://cmake.org/files/v3.23/cmake-3.23.2.tar.gz
tar -zxvf cmake-3.23.2.tar.gz
cd cmake-3.23.2
./bootstrap
make
make install
cmake -version

3. 开始安装grpc: https://grpc.io/docs/languages/cpp/quickstart/, github源以及submodule 必须翻墙更新
git clone --recurse-submodules -b v1.46.3 --depth 1 --shallow-submodules https://github.com/grpc/grp

说明：--recurse-submodules 递归子模块，--depth 1 递归深度1，--shallow-submodules(2016 年 8 月更新（3 年后）使用 Git 2.10（2016 年第三季度），可以使用此参数) 创建一个“浅”克隆，其历史记录被截断为指定的修订数。将--depth选项添加到“git submodule”的添加和更新命令中，然后将其传递给克隆命令。当子模块很大并且您对最新提交以外的任何内容都不感兴趣时，这很有用。
此处用梯子或者科学上网执行上述命令，获取代码包。

3.1 先安装protobuff （对应grpc版本v1.46.3，protoc版本v3.19.4）
当前目录在grpc根目录中执行以下
cd ./third_party/protobuf
./autogen.sh
./configure
make -j$(nproc)
sudo make install
sudo ldconfig
make clean
protoc --version

说明：ldconfig作用—— https://linux265.com/course/linux-command-ldconfig.html

3.2 安装grpc
cd grpc (到grpc 根目录)
mkdir -p cmake/build
pushd cmake/build
cmake -DgRPC_INSTALL=ON \
    -DgRPC_BUILD_TESTS=OFF \
    -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
    ../..
make -j$(nproc)
make install
popd

3.3 安装测试示例 examples/cpp/helloworld 验证grpc服务是否正常
当前路径在grpc 根目录
cd examples/cpp/helloworld
mkdir -p cmake/build
pushd cmake/build
cmake ../..
#cmake -DCMAKE_PREFIX_PATH=../../ ../..
make -j$(nproc)

当前目录多出一些二进制文件： 
执行 server 端 服务 
./greeter_server
出现 Server listening on 0.0.0.0:50051

然后另开一个终端
进入到当前目录 examples/cpp/helloworld/cmake/build
执行 client 
./greeter_client
如果输出 Greeter received: Hello world 则代表grpc protobuff3 安装成功





4. 安装 php-skywalking agent 

如果类似报错：fatal error: boost/interprocess/ipc/message_queue.hpp: 没有那个文件或目录， 说明缺少boost 包
yum install boost-devel

如果类似报错：fatal error: absl/synchronization/mutex.h
cp -r grpc/third_party/abseil-cpp/absl /usr/local/include/

**Comment by oyrm** [comment]
问题解决了吗？我也遇到了这个报错，RockyLinux8.6 @wyfaq

**Comment by heyanlong** [comment]
@oyrm 5.0.1已经移除C++ grpc依赖
