### ISSUE TITLE
/src/protocol/language-agent/Tracing.proto: No such file or directory

### ISSUE THREAD

**Issue by oyrm** [SkyAPM/SkyAPM-php-sdk#498]
docker编译安装5.0.1
os：centos:7.9.2009
php：8.1
gcc：11.2.1
cmake：3.23.2
protoc：3.17.3

16:48:36 [0m[91m   Compiling thiserror-impl v1.0.31
16:48:36 [0m[91m   Compiling async-stream-impl v0.3.3
16:48:36 [0m[91m   Compiling tokio v1.18.0
16:48:38 [0m[91m   Compiling async-stream v0.3.3
16:48:38 [0m[91m   Compiling pin-project v1.0.10
16:48:39 [0m[91m   Compiling thiserror v1.0.31
16:48:39 [0m[91m   Compiling prost v0.8.0
16:48:40 [0m[91m   Compiling tracing v0.1.34
16:48:40 [0m[91m   Compiling tracing-futures v0.2.5
16:48:40 [0m[91m   Compiling prost-types v0.8.0
16:48:40 [0m[91m   Compiling tonic-build v0.5.2
16:48:43 [0m[91m   Compiling tokio-util v0.7.1
16:48:46 [0m[91m   Compiling tokio-io-timeout v1.2.0
16:48:46 [0m[91m   Compiling tokio-stream v0.1.8
16:48:46 [0m[91m   Compiling tokio-util v0.6.9
16:48:46 [0m[91m   Compiling h2 v0.3.13
16:48:46 [0m[91m   Compiling tower v0.4.12
16:48:46 [0m[91m   Compiling bincode v1.3.3
16:48:50 [0m[91m   Compiling toml v0.5.9
16:48:50 [0m[91m   Compiling ipc-channel v0.16.0
16:48:51 [0m[91m   Compiling hyper v0.14.18
16:48:55 [0m[91m   Compiling SkyAPM-php-sdk v1.0.0 (/root/src/SkyAPM-php-sdk-5.0.1)
16:49:00 [0m[91merror: failed to run custom build command for `SkyAPM-php-sdk v1.0.0 (/root/src/SkyAPM-php-sdk-5.0.1)`
16:49:01 
16:49:01 Caused by:
16:49:01   process didn't exit successfully: `/root/src/SkyAPM-php-sdk-5.0.1/target/release/build/SkyAPM-php-sdk-a497a7b811f46c47/build-script-build` (exit status: 1)
16:49:01   --- stderr
16:49:01   Error: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: ./src/protocol/language-agent/Tracing.proto: No such file or directory\n" }
16:49:01 warning: build failed, waiting for other jobs to finish...
16:49:01 [0m[91mmake: *** [target/release/libsky_core_report.a] Error 101
16:49:09 [0mThe command '/bin/sh -c sh /root/scripts/init_phpext_skywalking.sh' returned a non-zero code: 2

**Comment by heyanlong** [comment]
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/BUILDING.md#build-from-source-php-extension

You need clone `git clone -b v9.1.0 https://github.com/apache/skywalking-data-collect-protocol.git src/protocol` into this project.
