### ISSUE TITLE
请问如何看到mysql，curl相关的调用

### ISSUE THREAD

**Issue by weiwei-9527** [SkyAPM/SkyAPM-php-sdk#503]
![image](https://user-images.githubusercontent.com/64568511/178953945-d3ed0ba8-1080-4989-a7c2-c458bca1149c.png)

请问如何看到mysql，curl相关的调用

**Comment by weiwei-9527** [comment]
版本：SkyAPM-php-sdk-4.2.0

**Comment by weiwei-9527** [comment]
write success {"traceId":"017922237ac1eda4cf102692f202c75f.22439.3633942920","traceSegmentId":"017922237ac1eda4cf102692f202c75f.22439.3633942920","spans":[{"spanId":0,"parentSpanId":-1,"startTime":"1657792299343","endTime":"1657792299444","refs":[],"operationName":"/Admin/getNotReadQuestion","peer":"www.ccc.com:80","spanType":"Entry","spanLayer":"Http","componentId":8001,"isError":false,"tags":[{"key":"url","value":"/Admin//getNotReadQuestion"},{"key":"http.method","value":"GET"},{"key":"status_code","value":"200"}],"logs":[],"skipAnalysis":false}],"service":"ccc","serviceInstance":"f2e0c032-761a-05a4-b7ef-a4533cc3ea61@10.8.40.2","isSizeLimited":false}

**Comment by heyanlong** [comment]
需要请求内包含对外的HTTP请求或者MySQL 查询

**Comment by heyanlong** [comment]
Merge #501
