### ISSUE TITLE
php-fpm采样率配置

### ISSUE THREAD

**Issue by qiqizjl** [SkyAPM/SkyAPM-php-sdk#507]
我们不希望所有请求都进行采样。看到在php.ini中一个``sample_n_per_3_secs``的配置。但是通过看代码得知好像只在swoole下生效

1: 目前支持FPM下配置采样率
2: 如果配置采样率后是否支持当请求的传递了trace_id/span_id的情况下。跳过采样率判断?不然会随着链路增长，后端服务采样率越来越低

**Comment by heyanlong** [comment]
FPM也支持，但是只能支持当前worker

**Comment by qiqizjl** [comment]
A->B->C->D 的调用链的场景下 如果都设置了30%的采样率 那么A触发采样后B,C,D的采样率还是按照30%配置来么？还是Header中会穿透类似trace_id/span_id情况下后面应用一定会采样

**Comment by heyanlong** [comment]
ABCD都会根据自己规则来判断是否采样，如果不需要，就生成一个空span

**Comment by qiqizjl** [comment]
如果ABCD里面 AC命中采样规则 在OAP中是一个链路么 还是多个链路

**Comment by qiqizjl** [comment]
看了眼会穿透sw8 理论上是一个链路。
