### ISSUE TITLE
编译正常，启动报错

### ISSUE THREAD

**Issue by maopaolinux** [SkyAPM/SkyAPM-php-sdk#52]
环境：
centos 7.2，php 7.2.16，protocol 3.6.1.3，grpc：1.19，gcc：4.8.5,SDK:2.0.2
![image](https://user-images.githubusercontent.com/15339401/55865701-7f9f5c00-5bb1-11e9-8b7e-c5601214d20f.png)
请求何兄以及各位帮看下

**Comment by artemus717** [comment]
启动报什么错？

**Comment by maopaolinux** [comment]
这个w问题解决了，修改，修改如下：
![image](https://user-images.githubusercontent.com/15339401/55939495-775a2600-5c70-11e9-9b4b-8eee77c904d0.png)
