### ISSUE TITLE
数据无法上报：sky_core_report_ipc_send err message queue is fulled

### ISSUE THREAD

**Issue by lrcstars** [SkyAPM/SkyAPM-php-sdk#522]
现场：
CentOS Linux release 7.9.2009 (Core)
OAP：9.1.0
SkyAPM-php-sdk：[v5.0.1](https://github.com/SkyAPM/SkyAPM-php-sdk/archive/v5.0.1.tar.gz)
php： 7.2.24 (cli)

项目是swoole+yaf
按照文档成功编译.so文件并配置
重启nging、php-fpm、swoole
UI上没有查询出此服务(其他java服务正常)
tcpdump抓包，能看到重启php-fpm后可能是连接的数据包，之后就抓不到数据了

/tmp/skywalking-php.log：
01:21:44 [TRACE] (1) mio::poll: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.2/src/poll.rs:499] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:73] poll_ready; idle
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:87] poll_ready; connecting
01:21:44 [TRACE] (2) hyper::client::connect::http: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/client/connect/http.rs:278] Http::connect; scheme=Some("http"), host=Some("10.10.10.117"), port=Some(Port(11800))
01:21:44 [DEBUG] (2) hyper::client::connect::http: connecting to 10.10.10.117:11800
01:21:44 [TRACE] (2) mio::poll: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.8.2/src/poll.rs:499] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:93] poll_ready; not ready
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:87] poll_ready; connecting
01:21:44 [DEBUG] (2) hyper::client::connect::http: connected to 10.10.10.117:11800
01:21:44 [TRACE] (2) hyper::client::conn: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/client/conn.rs:933] client handshake Http2
01:21:44 [DEBUG] (2) h2::client: binding client connection
01:21:44 [DEBUG] (2) h2::client: client connection bound
01:21:44 [TRACE] (2) h2::codec::framed_write: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] FramedWrite::buffer; frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] -> FramedWrite::buffer;
01:21:44 [DEBUG] (2) h2::codec::framed_write: send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
01:21:44 [TRACE] (2) h2::frame::settings: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/frame/settings.rs:220] encoding SETTINGS; len=18
01:21:44 [TRACE] (2) h2::frame::settings: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/frame/settings.rs:226] encoding setting; val=EnablePush(0)
01:21:44 [TRACE] (2) h2::frame::settings: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/frame/settings.rs:226] encoding setting; val=InitialWindowSize(2097152)
01:21:44 [TRACE] (2) h2::frame::settings: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/frame/settings.rs:226] encoding setting; val=MaxFrameSize(16384)
01:21:44 [TRACE] (2) h2::codec::framed_write: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:276] encoded settings rem=27
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] <- FramedWrite::buffer;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] -- FramedWrite::buffer;
01:21:44 [TRACE] (2) h2::proto::streams::flow_control: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/flow_control.rs:123] inc_window; sz=65535; old=0; new=65535
01:21:44 [TRACE] (2) h2::proto::streams::flow_control: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/flow_control.rs:123] inc_window; sz=65535; old=0; new=65535
01:21:44 [TRACE] (2) h2::proto::streams::prioritize: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:90] Prioritize::new; flow=FlowControl { window_size: Window(65535), available: Window(65535)}
01:21:44 [DEBUG] (2) h2::proto::connection: Connection; peer=Client
01:21:44 [TRACE] (2) h2::proto::streams::recv: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/recv.rs:430] set_target_connection_window; target=5242880; available=65535, reserved=0
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:113] poll_ready; connected
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:123] poll_ready; not ready
01:21:44 [TRACE] (2) want: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/want-0.3.0/src/lib.rs:341] signal: Want
01:21:44 [TRACE] (2) want: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/want-0.3.0/src/lib.rs:355] signal found waiting giver, notifying
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:113] poll_ready; connected
01:21:44 [TRACE] (2) want: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/want-0.3.0/src/lib.rs:200] poll_want: taker wants!
01:21:44 [TRACE] (2) tonic::transport::service::reconnect: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.5.2/src/transport/service/reconnect.rs:119] poll_ready; ready
01:21:44 [TRACE] (2) tower::buffer::worker: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.12/src/buffer/worker.rs:108] worker polling for next message
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:138] -> Connection;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:250] poll;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:250] -> poll;
01:21:44 [TRACE] (2) h2::proto::connection: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:254] connection.state=Open
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:138] -> Connection;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:181] poll_ready;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:181] -> poll_ready;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:181] <- poll_ready;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:181] -- poll_ready;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:138] <- Connection;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_read.rs:336] FramedRead::poll_next;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_read.rs:336] -> FramedRead::poll_next;
01:21:44 [TRACE] (2) h2::codec::framed_read: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_read.rs:339] poll
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_read.rs:336] <- FramedRead::poll_next;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_read.rs:336] -- FramedRead::poll_next;
01:21:44 [TRACE] (2) h2::codec::framed_write: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] FramedWrite::buffer; frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] -> FramedWrite::buffer;
01:21:44 [DEBUG] (2) h2::codec::framed_write: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
01:21:44 [TRACE] (2) h2::frame::window_update: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/frame/window_update.rs:51] encoding WINDOW_UPDATE; id=StreamId(0)
01:21:44 [TRACE] (2) h2::codec::framed_write: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:288] encoded window_update rem=40
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] <- FramedWrite::buffer;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:229] -- FramedWrite::buffer;
01:21:44 [TRACE] (2) h2::proto::streams::flow_control: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/flow_control.rs:123] inc_window; sz=5177345; old=65535; new=5242880
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] -> try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] <- try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] -- try_reclaim_frame;
01:21:44 [TRACE] (2) h2::proto::streams::prioritize: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:500] poll_complete
01:21:44 [TRACE] (2) h2::proto::streams::prioritize: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:856] schedule_pending_open
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:675] pop_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:675] -> pop_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:675] <- pop_frame;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:675] -- pop_frame;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:120] FramedWrite::flush;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:120] -> FramedWrite::flush;
01:21:44 [TRACE] (2) h2::codec::framed_write: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:137] queued_data_frame=false
01:21:44 [TRACE] (2) h2::codec::framed_write: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:154] flushing buffer
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:120] <- FramedWrite::flush;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/codec/framed_write.rs:120] -- FramedWrite::flush;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] -> try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] <- try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/streams/prioritize.rs:553] -- try_reclaim_frame;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:250] <- poll;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:250] -- poll;
01:21:44 [TRACE] (2) tracing::span::active: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:138] <- Connection;
01:21:44 [TRACE] (2) tracing::span: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.13/src/proto/connection.rs:138] -- Connection;
01:21:45 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:45 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:45 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:45 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:45 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:45 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:46 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:46 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:46 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:21:46 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
(相同的内容)
01:22:00 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:00 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:00 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:00 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:01 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:01 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:01 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:01 [DEBUG] (7) sky_core_report: sky_core_report_ipc_send ok
01:22:01 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:01 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:02 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:02 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:02 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:02 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:02 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:02 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:03 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:03 [ERROR] sky_core_report_ipc_send err message queue is fulled
01:22:03 [ERROR] sky_core_report_ipc_send err message queue is fulled
(一直重复该报错，没有其他报错)

**Comment by aodashuai001** [comment]
5.0.1版本暂时不支持swoole，要么等5.1.0版本或者回退到4.x版本

**Comment by lrcstars** [comment]
> 

回退4.X后，支持最新的9.1的OAP吧？

**Comment by lrcstars** [comment]
> 5.0.1版本暂时不支持swoole，要么等5.1.0版本或者回退到4.x版本

git clone -b v9.1.0 https://github.com/apache/skywalking-data-collect-protocol.git
需要用最新的protocol吗

**Comment by aodashuai001** [comment]
> 

我看了下代码，只支持到skywalking 8，推测不支持9

**Comment by lrcstars** [comment]
> > 
> 
> 我看了下代码，只支持到skywalking 8，推测不支持9

4.2的php agent对应skywalking 8的哪个版本，我用4.2的php agent，skywalking 8.9.1或9.1.0，能看到服务名，但实例个数再不断增加，每分钟新增100+实例

php用的swoole

**Comment by heyanlong** [comment]
4.2理论上也是支持9.1的

**Comment by aodashuai001** [comment]
> > > 
> > 
> > 
> > 我看了下代码，只支持到skywalking 8，推测不支持9
> 
> 4.2的php agent对应skywalking 8的哪个版本，我用4.2的php agent，skywalking 8.9.1或9.1.0，能看到服务名，但实例个数再不断增加，每分钟新增100+实例
> 
> php用的swoole

大佬说理论上支持9，你也可以试试。
4.2支持skywalking 8版本，小版本应该都是兼容支持的，因为协议一致，http头sw8。
实例个数不断增加这个没遇到过，看下截图是怎么回事。

**Comment by lrcstars** [comment]
> 

我基本上算是放弃了，skywalking 8、9和php agent 4.2、5.0.1都交叉使用了，没一个成功的
主要应该还是在php agent
4.2的必然会出现实例个数不断增加的问题，且endpoint始终为空
5.0.1在不同环境编译成功过几次，成功的.so文件会出现以下2中情况
    1. 本issues上描述的情况，这里还有一点补充下：环境中有多个php项目，有没用swoole的项目，但还是采集不到信息，甚至连服务实例都没上报，看起来建立连接后就不再发送请求了
    2. 日志如任何报错，服务实例无上报到OAP，建立连接后就不再发送请求

**Comment by aodashuai001** [comment]
> 我基本上算是放弃了，skywalking 8、9和php agent 4.2、5.0.1都交叉使用了，没一个成功的 主要应该还是在php agent 4.2的必然会出现实例个数不断增加的问题，且endpoint始终为空 5.0.1在不同环境编译成功过几次，成功的.so文件会出现以下2中情况 1. 本issues上描述的情况，这里还有一点补充下：环境中有多个php项目，有没用swoole的项目，但还是采集不到信息，甚至连服务实例都没上报，看起来建立连接后就不再发送请求了 2. 日志如任何报错，服务实例无上报到OAP，建立连接后就不再发送请求

不太明白为何实例个数会增加，理论上在php.ini中配置的service name就是固定的，不太可能会增加实例。

**Comment by lrcstars** [comment]
> > 我基本上算是放弃了，skywalking 8、9和php agent 4.2、5.0.1都交叉使用了，没一个成功的 主要应该还是在php agent 4.2的必然会出现实例个数不断增加的问题，且endpoint始终为空 5.0.1在不同环境编译成功过几次，成功的.so文件会出现以下2中情况 1. 本issues上描述的情况，这里还有一点补充下：环境中有多个php项目，有没用swoole的项目，但还是采集不到信息，甚至连服务实例都没上报，看起来建立连接后就不再发送请求了 2. 日志如任何报错，服务实例无上报到OAP，建立连接后就不再发送请求
> 
> 不太明白为何实例个数会增加，理论上在php.ini中配置的service name就是固定的，不太可能会增加实例。

service name就是固定的但是没有指定实例名，然后实例就在一直增加了

**Comment by heyanlong** [comment]
每次重启后，instance名字会变

**Comment by heyanlong** [comment]
重启后变化属于正常。

**Comment by aodashuai001** [comment]
> > > 我基本上算是放弃了，skywalking 8、9和php agent 4.2、5.0.1都交叉使用了，没一个成功的 主要应该还是在php agent 4.2的必然会出现实例个数不断增加的问题，且endpoint始终为空 5.0.1在不同环境编译成功过几次，成功的.so文件会出现以下2中情况 1. 本issues上描述的情况，这里还有一点补充下：环境中有多个php项目，有没用swoole的项目，但还是采集不到信息，甚至连服务实例都没上报，看起来建立连接后就不再发送请求了 2. 日志如任何报错，服务实例无上报到OAP，建立连接后就不再发送请求
> > 
> > 
> > 不太明白为何实例个数会增加，理论上在php.ini中配置的service name就是固定的，不太可能会增加实例。
> 
> service name就是固定的但是没有指定实例名，然后实例就在一直增加了

那你试试
`skywalking.app_code = hello_skywalking
skywalking.instance_name = ""`
这两个参数都配置上

**Comment by heyanlong** [comment]
我建议还是使用5.0.1进行调试

**Comment by lrcstars** [comment]
> 每次重启后，instance名字会变

 php-fpm没重启。并且我一分钟能增加上百个instance
 o(╥﹏╥)o

**Comment by heyanlong** [comment]
发一下你的配置和PHP配置。PHP用什么管理的？systemd?

**Comment by lrcstars** [comment]
通过systemd管理的php-fpm
`
[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = -1
disable_functions =
disable_classes =
zend.enable_gc = On
expose_php = Off
max_execution_time = 900
max_input_time = 600
memory_limit = 1024M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 2048
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
html_errors = On
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 48M
auto_prepend_file =
auto_append_file =
default_mimetype = "text/html"
default_charset = "UTF-8"
doc_root =
user_dir =
enable_dl = Off
file_uploads = On
upload_max_filesize = 32M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 120
[yaf]
extension=yaf
yaf.name_suffix = 1
yaf.use_namespace = 0
yaf.use_spl_autoload = 1
[beast]
extension = beast
beast.cache_size = 64M
beast.networkcard = "ens192"
beast.log_file = ""
beast.log_user = "nginx"
beast.log_level = "error"
beast.enable = On
[swoole]
# version: 4.4.16 - 20200219
extension=swoole.so
[phpredis]
extension=redis
[oci]
extension=oci8.so
[CLI Server]
cli_server.color = On
[Date]
date.timezone = Asia/Shanghai
[filter]
[iconv]
[imap]
[intl]
[sqlite3]
[Pcre]
[Pdo]
[Pdo_mysql]
pdo_mysql.cache_size = 2000
pdo_mysql.default_socket=
[Phar]
[mail function]
SMTP = localhost
smtp_port = 25
mail.add_x_header = Off
[ODBC]
odbc.allow_persistent = On
odbc.check_persistent = On
odbc.max_persistent = -1
odbc.max_links = -1
odbc.defaultlrl = 4096
odbc.defaultbinmode = 1
[Interbase]
ibase.allow_persistent = 1
ibase.max_persistent = -1
ibase.max_links = -1
ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
ibase.dateformat = "%Y-%m-%d"
ibase.timeformat = "%H:%M:%S"
[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.cache_size = 2000
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.default_host =
mysqli.default_user =
mysqli.default_pw =
mysqli.reconnect = Off
[mysqlnd]
mysqlnd.collect_statistics = On
mysqlnd.collect_memory_statistics = Off
[OCI8]
[PostgreSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0
[bcmath]
bcmath.scale = 0
[browscap]
[Session]
session.save_handler = files
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.sid_length = 26
session.trans_sid_tags = "a=href,area=href,frame=src,form="
session.sid_bits_per_character = 5
[Assertion]
zend.assertions = -1
[COM]
[mbstring]
[gd]
[exif]
[Tidy]
tidy.clean_output = Off
[soap]
soap.wsdl_cache_enabled=1
soap.wsdl_cache_dir="/tmp"
soap.wsdl_cache_ttl=86400
soap.wsdl_cache_limit = 5
[sysvshm]
[ldap]
ldap.max_links = -1
[dba]
[opcache]
[curl]
[openssl]
[scws]
extension=scws.so
scws.default.charset=utf-8
scws.default.fpath=/usr/local/scws/etc
extension=pdo_dblib.so
;;;;;;;;;;;;;skywalking;;;;;;;;;;;;;;
; Loading extensions in PHP
extension=skywalking.so

; enable skywalking
skywalking.enable = 1

; Set app code e.g. MyProjectName
skywalking.service = FMS

; skywalking oap version
skywalking.oap_version = 9.0.0

; Set grpc address
skywalking.grpc_address = 10.10.10.117:11800
; skywalking.grpc_tls_enable
; skywalking.grpc_tls_pem_root_certs
; skywalking.grpc_tls_pem_private_key
; skywalking.grpc_tls_pem_cert_chain

; Enable log, default disable
; Options trace, debug, info, warn, error
skywalking.log_level = trace
skywalking.log_path = /tmp/skywalking-php.log

; Enable with cURL response, default 0
; skywalking.curl_response_enable = 0
;;;;;;;;;;;;;skywalking;;;;;;;;;;;;;;
`

**Comment by heyanlong** [comment]
ID重复需要看systemd是否重启PHP了。
