### ISSUE TITLE
report_client make error 

### ISSUE THREAD

**Issue by huahuacaocao** [SkyAPM/SkyAPM-php-sdk#55]
Some errors occurred during compiling the report_client.

report_client.cpp:26:28: fatal error: boost/format.hpp: No such file or directory
 #include <boost/format.hpp>
                            ^
compilation terminated.
make: *** [report_client] Error 1

**Comment by goerzh** [comment]
install boost
`yum install boost boost-thread boost-devel`

**Comment by heyanlong** [comment]
Retry 3.1.0
