### ISSUE TITLE
编译无报错，加载skywalking扩展后php-fpm无法启动

### ISSUE THREAD

**Issue by levinzzp** [SkyAPM/SkyAPM-php-sdk#60]
你好:
我的生产环境是php7.2+gcc 4.7.4
编译时候的环境是gcc6.x，编译出来的.so扩展添加到php.ini，报出segementation fault错误，php-fpm无法启动，没有其他错误信息了，请问是否要求php本身的编译环境也要相同于agent？

**Comment by heyanlong** [comment]
Retry last release
