### ISSUE TITLE
Doubts regarding installation of SkyAPM-php agent 

### ISSUE THREAD

**Issue by indraneelbaronia** [SkyAPM/SkyAPM-php-sdk#64]
I am new to skywalking and am trying to install the **Skywalking php agent**. i am following the given document in the SkyAPM-php-sdk. However after cloning the repository when i try to execute the command - " **phpize && ./configure && make && make install** " it give the following error :-

/home/indraneel/SkyAPM-php-sdk/src/greeter_client.cc:25:10: fatal error: grpc/register/Register.grpc.pb.h: No such file or directory
 #include "grpc/register/Register.grpc.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I installed gRPC as per the instructions given in the installation documents. I can't seem to find the **Register.grpc.pb.h** file anywhere. Please can someone help me get a clearer idea of what exactly this file is and where can i find it?

**Comment by heyanlong** [comment]
@goerzh

**Comment by gguillory** [comment]
Hi,
Trying to create and install Skywalking PHP agent and I've got exactly the same problem as mentionned by indraneelbaronia. The file "Register.grpc.pb.h" can not be found ...
Searching for this file on the web returns no result and I can't find any way to continue the installation
(RHEL 7.5 / PHP 7.2.17)

**Comment by heyanlong** [comment]
Is there a `protoc` command?

**Comment by gguillory** [comment]
Indeed, there is no "protoc" command found :

configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing default-1 commands
./config.status: line 1057: protoc: command not found
./config.status: line 1058: protoc: command not found
./config.status: line 1059: protoc: command not found
which: no grpc_cpp_plugin in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
./config.status: line 1060: protoc: command not found
which: no grpc_cpp_plugin in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
./config.status: line 1061: protoc: command not found
which: no grpc_cpp_plugin in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
./config.status: line 1062: protoc: command not found
config.status: executing default-2 commands
mv: cannot stat 'src/grpc/common/common.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/register/Register.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/language-agent-v2/trace.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/register/InstancePing.grpc.pb.cc': No such file or directory
mv: cannot stat 'src/grpc/common/trace-common.grpc.pb.cc': No such file or directory
config.status: executing libtool commands
/bin/sh /tmp/SkyAPM-php-sdk/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/SkyAPM-php-sdk -DPHP_ATOM_INC -I/tmp/SkyAPM-php-sdk/include -I/tmp/SkyAPM-php-sdk/main -I/tmp/SkyAPM-php-sdk -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/tmp/SkyAPM-php-sdk/src/grpc -I/tmp/SkyAPM-php-sdk/src  -DHAVE_CONFIG_H  -std=c++11 -Isrc/report/deps/boost -DDEBUG   -c /tmp/SkyAPM-php-sdk/src/greeter_client.cc -o src/greeter_client.lo
libtool: compile:  g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/tmp/SkyAPM-php-sdk -DPHP_ATOM_INC -I/tmp/SkyAPM-php-sdk/include -I/tmp/SkyAPM-php-sdk/main -I/tmp/SkyAPM-php-sdk -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/tmp/SkyAPM-php-sdk/src/grpc -I/tmp/SkyAPM-php-sdk/src -DHAVE_CONFIG_H -std=c++11 -Isrc/report/deps/boost -DDEBUG -c /tmp/SkyAPM-php-sdk/src/greeter_client.cc  -fPIC -DPIC -o src/.libs/greeter_client.o
/tmp/SkyAPM-php-sdk/src/greeter_client.cc:25:44: fatal error: grpc/register/Register.grpc.pb.h: No such file or directory
 #include "grpc/register/Register.grpc.pb.h"
                                            ^
compilation terminated.
make: *** [src/greeter_client.lo] Erreur 1

**Comment by heyanlong** [comment]
Need preinstall `grpc_cpp_plugin` and `protoc`
see: [github.com/grpc/grpc](github.com/grpc/grpc)

**Comment by gguillory** [comment]
okay thanx

**Comment by heyanlong** [comment]
Retry last release
