### ISSUE TITLE
json.exception.type_error.305

### ISSUE THREAD

**Issue by hhpp33** [SkyAPM/SkyAPM-php-sdk#65]
send `/tmp/skywalking.1557797862-3966.log` to skywalking service
send 4.3966.15577978600012 to skywalking service
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with a string argument with array
Aborted

**Comment by heyanlong** [comment]
@goerzh

**Comment by heyanlong** [comment]
Retry last release
