### ISSUE TITLE
json.exception.type_error.302

### ISSUE THREAD

**Issue by hhpp33** [SkyAPM/SkyAPM-php-sdk#66]
send `/tmp/skywalking.1557798374-5642.log` to skywalking service
send 4.5642.15577983730010 to skywalking service
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is array
Aborted

**Comment by heyanlong** [comment]
@goerzh

**Comment by heyanlong** [comment]
Retry last release
