### ISSUE TITLE
skywalking-php-agent make 编译报错

### ISSUE THREAD

**Issue by yifeichongtiang** [SkyAPM/SkyAPM-php-sdk#70]
root@ubuntu-30-29:/data/SkyAPM-php-sdk# make
/bin/bash /data/SkyAPM-php-sdk/libtool --mode=compile cc -Wall -Werror -std=c++11 -I. -I/data/SkyAPM-php-sdk -DPHP_ATOM_INC -I/data/SkyAPM-php-sdk/include -I/data/SkyAPM-php-sdk/main -I/data/SkyAPM-php-sdk -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/local/include -I/data/SkyAPM-php-sdk/src/report/deps/boost -I/data/SkyAPM-php-sdk/src/grpc -I/data/SkyAPM-php-sdk/src  -DHAVE_CONFIG_H  -g -O2   -c /data/SkyAPM-php-sdk/skywalking.c -o skywalking.lo 
libtool: compile:  cc -Wall -Werror -std=c++11 -I. -I/data/SkyAPM-php-sdk -DPHP_ATOM_INC -I/data/SkyAPM-php-sdk/include -I/data/SkyAPM-php-sdk/main -I/data/SkyAPM-php-sdk -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/local/include -I/data/SkyAPM-php-sdk/src/report/deps/boost -I/data/SkyAPM-php-sdk/src/grpc -I/data/SkyAPM-php-sdk/src -DHAVE_CONFIG_H -g -O2 -c /data/SkyAPM-php-sdk/skywalking.c  -fPIC -DPIC -o .libs/skywalking.o
cc1: error: command line option '-std=c++11' is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
make: *** [skywalking.lo] Error 1

**Comment by FlyLand** [comment]
同样问题无法解决。已升级g++版本

**Comment by okami-chen** [comment]
> 同样问题无法解决。已升级g++版本

升级g++版本能解决？

**Comment by FlyLand** [comment]
> 
> 
> > 同样问题无法解决。已升级g++版本
> 
> 升级g++版本能解决？

去掉Makefile里边的 Werror 提醒，可以编译成功。

**Comment by zsmlinux** [comment]
> > > 同样问题无法解决。已升级g++版本
> > 
> > 
> > 升级g++版本能解决？
> 
> 去掉Makefile里边的 Werror 提醒，可以编译成功。

遇到同样问题，gcc 升级到4.8 依然不行。
请问怎么去掉Werror 提醒？

**Comment by okami-chen** [comment]
git chckout 2.0.2

**Comment by zdwork** [comment]
请问下有人解决这个问题了吗 我也遇到同样的问题了

**Comment by heyanlong** [comment]
各位别急，正在移除c++ grpc等依赖，尽量简化安装过程
6月底发布新版本
@zdwork @okami-chen @zsmlinux @yifeichongtiang @FlyLand

**Comment by zdwork** [comment]
您好 到时会支持php5.5吗？

**Comment by heyanlong** [comment]
> 你好到时会支持php5.5吗？

不支持

**Comment by okami-chen** [comment]
目前看只有curl，如何手动加入埋点?
使用GuzzleHttp\Client貌似上报不正确？

**Comment by nicedu123** [comment]
同样的错误 请问有解决了的吗

**Comment by heyanlong** [comment]
Retry last release
