### ISSUE TITLE
php-fpm 无法重启

### ISSUE THREAD

**Issue by nicedu123** [SkyAPM/SkyAPM-php-sdk#72]
<b>Warning</b>:  PHP Startup: Unable to load dynamic library '/alidata/server/php-7.1.19/lib/php/extensions/no-debug-non-zts-20160303/skywalking.so' - /alidata/server/php-7.1.19/lib/php/extensions/no-debug-non-zts-20160303/skywalking.so: undefined symbol: _ZTIN6google8protobuf7MessageE in <b>Unknown</b> on line <b>0</b><br />

**Comment by heyanlong** [comment]
retry 3.1.0
