### ISSUE TITLE
docker 安装./configure  时，出现checking for libgrpc files in default path... not found

### ISSUE THREAD

**Issue by sinbad01234** [SkyAPM/SkyAPM-php-sdk#73]
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
+ cd SkyAPM-php-sdk-master
+ phpize
+ ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20170718
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable skywalking support... yes, shared
checking for libgrpc support... yes, shared
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
configure: error: Please install libgrpc - See https://github.com/grpc/grpc

**Comment by sinbad01234** [comment]
dockerfile文件
FROM php:7.2
ENV INSTALL_LIB_DEP="wget zip unzip"
RUN apt-get update 
RUN apt-get install -y $INSTALL_LIB_DEP 
RUN apt-get update && apt-get install -y -q git rake ruby-ronn zlib1g-dev && apt-get clean

# install composer
RUN cd /usr/local/bin && curl -sS https://getcomposer.org/installer | php
RUN cd /usr/local/bin && mv composer.phar composer

RUN pecl install grpc

#install protoc
RUN mkdir -p /tmp/protoc && \
    curl -L https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip > /tmp/protoc/protoc.zip && \
    cd /tmp/protoc && \
    unzip protoc.zip && \
    cp /tmp/protoc/bin/protoc /usr/local/bin && \
    cd /tmp && \
    rm -r /tmp/protoc && \
    docker-php-ext-enable grpc


RUN set -ex \
        && cd /opt \
        && wget https://github.com/SkyAPM/SkyAPM-php-sdk/archive/master.zip -O master.zip \
        && unzip master.zip \
        && cd SkyAPM-php-sdk-master \
        && phpize \
        && ./configure \
        && make && make install \
        && cd src/report \
        && make \
        && cp report_client /usr/bin

**Comment by heyanlong** [comment]
grpc 没有安装
另外，明天会发布新版本，彻底修复现有编译问题

**Comment by infamt** [comment]
非常感谢，期待明天发布的版本!




------------------ 原始邮件 ------------------
发件人: "何延龙"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 晚上6:46
收件人: "SkyAPM/SkyAPM-php-sdk"<SkyAPM-php-sdk@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [SkyAPM/SkyAPM-php-sdk] docker 安装./configure  时，出现checking for libgrpc files in default path... not found (#73)




grpc 没有安装
 另外，明天会发布新版本，彻底修复现有编译问题

**Comment by sinbad01234** [comment]
非常感谢，期待新版本

**Comment by heyanlong** [comment]
https://github.com/SkyAPM/SkyAPM-php-sdk/releases/tag/3.0.0

**Comment by sinbad01234** [comment]
ok.thanks
