### ISSUE TITLE
report_client 上报日志无响应

### ISSUE THREAD

**Issue by infamt** [SkyAPM/SkyAPM-php-sdk#74]
### 基础环境

- **Centos 7.6**
- **SkyWalking: 6.1.0**
- **ElasticSearsh: 6.3.2**
- **PHP: 7.0.28**
- **skywalking-php-sdk: 2.0.2**
 - **php.ini:**
![image](https://user-images.githubusercontent.com/31602462/60090961-1d98d080-9776-11e9-999e-dc59a9bb1ff5.png)

 - **php -m 无报错**
 - **请求 php 时 agent 日志目录会生成日志**

### 问题描述
- **SkyWalking Server 端接收不到 agent 搜集的数据信息**
![image](https://user-images.githubusercontent.com/31602462/60090988-2ab5bf80-9776-11e9-9fc1-3a74a385ee2c.png)

- **report_client 客户端显示发送日志到 Server 并把日志清除**
![image](https://user-images.githubusercontent.com/31602462/60091001-31dccd80-9776-11e9-80b1-fdc739f235dd.png)

> 
- **SkyWalking Server 端启动正常；**
- **初始化 ElasticSearsh 时无异常，成功创建索引。**

**Comment by xiaohuasheng** [comment]
> ### 基础环境
> * **Centos 7.6**
> * **SkyWalking: 6.1.0**
> * **ElasticSearsh: 6.3.2**
> * **PHP: 7.0.28**
> * **skywalking-php-sdk: 2.0.2**
> * **php.ini:**
>   ![image](https://user-images.githubusercontent.com/31602462/60090961-1d98d080-9776-11e9-999e-dc59a9bb1ff5.png)
> * **php -m 无报错**
> * **请求 php 时 agent 日志目录会生成日志**
> 
> ### 问题描述
> * **SkyWalking Server 端接收不到 agent 搜集的数据信息**
>   ![image](https://user-images.githubusercontent.com/31602462/60090988-2ab5bf80-9776-11e9-9fc1-3a74a385ee2c.png)
> * **report_client 客户端显示发送日志到 Server 并把日志清除**
>   ![image](https://user-images.githubusercontent.com/31602462/60091001-31dccd80-9776-11e9-80b1-fdc739f235dd.png)
> 
> > 
> 
> * **SkyWalking Server 端启动正常；**
> * **初始化 ElasticSearsh 时无异常，成功创建索引。**

我也差不多是这样呀，PHP7，有服务，但没有追踪数据
![image](https://user-images.githubusercontent.com/11706254/60275257-3ba83180-992c-11e9-8b84-eded7d6e7efd.png)

**Comment by heyanlong** [comment]
请使用3.0.0
对于6.x支持，请等待3.0.1
