### ISSUE TITLE
report_client上报没有收到信息

### ISSUE THREAD

**Issue by sinbad01234** [SkyAPM/SkyAPM-php-sdk#77]
report_client 172.26.112.220:11800
Segmentation fault
这是什么情况。我的是skywalking 是6的版本。用的fpm。

**Comment by heyanlong** [comment]
暂时不支持6.x

**Comment by sinbad01234** [comment]
> 暂时不支持6.x

谢谢

**Comment by heyanlong** [comment]
Retry last release
