### ISSUE TITLE
关于php探针安装和使用

### ISSUE THREAD

**Issue by liushuo9999** [SkyAPM/SkyAPM-php-sdk#78]
我按照install-agent.md文档进行了安装，但是不知道如何使用这个探针，在控制台只显示了一个hello。

**Comment by heyanlong** [comment]
php ini 配置了吗

**Comment by liushuo9999** [comment]
配置了是按照文档配置的
但是在phpinfo中看不到不知道正不正常

**Comment by heyanlong** [comment]
看不到是PHP 扩展没加载成功

**Comment by liushuo9999** [comment]
这里我就不清楚了，我也重启php-fpm了为什么会加载不成功呢？

**Comment by tristan-tsl** [comment]
when i use the comand to restart the php-fpm:

kill -USR2 `cat /usr/local/php/var/run/php-fpm.pid`

and use the commad to find skyalking php extion:
php -r 'phpinfo();' | grep skywalking

and use the commnad to run skywalking-php-agent:
sky_php_agent 192.168.86.124:11800

but it also just print:
2019/07/05 15:07:37 hello

**Comment by liushuo9999** [comment]
在查看php扩展这里我会打印如下信息，其他的我都会成功

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/skywalking.so' - /usr/lib64/php/modules/skywalking.so: undefined symbol: php_json_encode in Unknown on line 0

**Comment by tristan-tsl** [comment]
skywalking
skywalking.app_code => MyProjectName => MyProjectName
skywalking.enable => On => On
skywalking.grpc => 192.168.86.124:11800 => 192.168.86.124:11800
skywalking.log_path => /data/tristan/logs/ => /data/tristan/logs/
skywalking.version => 6 => 6
PWD => /data/tristan/apache-skywalking-apm-bin/logs
OLDPWD => /data/tristan/apache-skywalking-apm-bin/logs
$_SERVER['PWD'] => /data/tristan/apache-skywalking-apm-bin/logs
$_SERVER['OLDPWD'] => /data/tristan/apache-skywalking-apm-bin/logs

**Comment by tristan-tsl** [comment]
is 3.0 is stable?

**Comment by heyanlong** [comment]
@liushuo9999 php -m
查看是否存在json extension

**Comment by heyanlong** [comment]
Retry last release

**Comment by holen** [comment]
客户端在哪里启动

**Comment by luyang-yanglu** [comment]
Try this in php.ini
[skywalking]
extension=json.so
extension=skywalking.so
skywalking.app_code = apiv2-phoenix
skywalking.enable = 1
skywalking.version = 8
skywalking.sock_path = /tmp/sky-agent.sock
