### ISSUE TITLE
warning: passing argument 1 of ‘strlen’ from incompatible pointer type [enabled by default]

### ISSUE THREAD

**Issue by ming200825** [SkyAPM/SkyAPM-php-sdk#79]
![image](https://user-images.githubusercontent.com/4900401/60753030-d0332380-9fff-11e9-8aa3-fda91e8f4ae2.png)

**Comment by heyanlong** [comment]
System ?
GCC version ?
PHP version ?

**Comment by bostin** [comment]
see #88
