### ISSUE TITLE
Missing the documents about how to upstream segment to agent.

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/SkyAPM-php-sdk#8]
As you mentioned, this sdk supported to write data into logs, but you miss the part about how to uplink these logs to the skywalking collector, and the UI visualization. 

This is an important documents for end users.

**Comment by heyanlong** [comment]
report_client is responsible for sending logs to the skywalking collector
e.g.
```shell
./report_client 120.0.0.1:11800 /tmp
```

**Comment by wu-sheng** [comment]
I want you could provide a step by step document to guide users to use this. Then, we could put you in SkyWalking supported language list.

Will be good for others choose this project. Right now, people are hard to get start.
