### ISSUE TITLE
Is it supports skywalking 6.x now?

### ISSUE THREAD

**Issue by chidaodezhongsheng** [SkyAPM/SkyAPM-php-sdk#81]
Is it supports skywalking 6.x now?

**Comment by iZRIdJJ53S** [comment]
yes. Supported as of (sky_php_agent) version 3.1.1
https://github.com/SkyAPM/SkyAPM-php-sdk/releases
- v3.1.0 (skywalking 6.x Support)
- v3.1.1 (fix bugs)

↓ For your reference
https://github.com/SkyAPM/SkyAPM-php-sdk/issues/80#issuecomment-510023048

```
 it was OK even with nginx + php-fpm

Nginx v1.17.0
php-fpm PHP 7.2.14 (fpm-fcgi)
skywalking v6.2.0
sky_php_agent v3.1.1
```

**Comment by heyanlong** [comment]
@iZRIdJJ53S said the right. 😄
