### ISSUE TITLE
Can only view the HttpClient, won't be able to see the MYSQL database information

### ISSUE THREAD

**Issue by xaviertoo** [SkyAPM/SkyAPM-php-sdk#82]
Docker apache/skywalking:6.2
SkyAPM-php-sdk:3.1.1
PHP Version 7.2.15 FPM

Can only view the HttpClient, won't be able to see the MYSQL database information.
The current version does not support？

**Comment by heyanlong** [comment]
The current version does not support.
Developing

**Comment by xaviertoo** [comment]
Thanks！
