### ISSUE TITLE
report_client上报没有收到信息，命令行显示hello skywalking

### ISSUE THREAD

**Issue by sinbad01234** [SkyAPM/SkyAPM-php-sdk#84]
#  report_client 172.26.112.220:11800 /data/log/3.log
hello skywalking

使用的最新版本的
https://github.com/SkyAPM/SkyAPM-php-sdk/releases/download/3.1.2/sky_php_agent_linux_x64

php.ini 也正常
 skywalking 6+。

**Comment by sinbad01234** [comment]
![image](https://user-images.githubusercontent.com/48613293/61293626-b7e4b500-a806-11e9-8519-7789691fe621.png)

**Comment by sinbad01234** [comment]
![image](https://user-images.githubusercontent.com/48613293/61293729-ec587100-a806-11e9-91dc-ed9bac93786d.png)

**Comment by sinbad01234** [comment]
![image](https://user-images.githubusercontent.com/48613293/61293752-f8dcc980-a806-11e9-9f7c-03c9dbc8d96f.png)

**Comment by heyanlong** [comment]
是同一个用户吗？

发自我的 iPhone

**Comment by sinbad01234** [comment]
> 是同一个用户吗？ 发自我的 iPhone
> […](#)
> 在 2019年7月16日，20:19，sinbad01234 ***@***.***> 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.



> 是同一个用户吗？ 发自我的 iPhone
> […](#)
> 在 2019年7月16日，20:19，sinbad01234 ***@***.***> 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

是同一个用户

**Comment by sinbad01234** [comment]
是同一个用户

**Comment by heyanlong** [comment]
请执行如下操作，并反馈
ps aux | grep php
ps aux | grep report_client
ls -l /tmp/sky_agent*

**Comment by sinbad01234** [comment]
![image](https://user-images.githubusercontent.com/48613293/61364314-2c2b6100-a8b8-11e9-9a12-301efe4869ce.png)

**Comment by heyanlong** [comment]
明显不在一个用户运行，使用www-data 运行 report_client 就好了

**Comment by sinbad01234** [comment]
能上传日志了，但是有个问题。nginx报错，有些接口返回正常，个别接口请求返回 502. 不是因为超时，nginx日志如下：
2019/07/20 11:36:23 [error] 7#7: *856 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /place/search HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000"

**Comment by sinbad01234** [comment]
我修改了php-fpm.conf也不起作用。修改如下：
pm = dynamic
pm.max_children = 200
pm.start_servers = 30
pm.min_spare_servers = 15
pm.max_spare_servers = 45
pm.max_requests = 10000
rlimit_files = 51200
request_terminate_timeout = 150 

request_slowlog_timeout = 8s
slowlog = /data/www-slow.log

**Comment by heyanlong** [comment]
是特定接口永久502吗？

发自我的 iPhone

**Comment by sinbad01234** [comment]
对，都是特定接口，目前就两个接口这样，一个是请求阿里云oss上传图片的，一个是请求elastic search的搜索。
