### ISSUE TITLE
skyphpsdk现在支持哪些版本php

### ISSUE THREAD

**Issue by iwzd520** [SkyAPM/SkyAPM-php-sdk#89]
如题，支持哪些版本php，老版本5.6现在到底支持不？

**Comment by heyanlong** [comment]
不支持

发自我的 iPhone

**Comment by iwzd520** [comment]
有计划支持5.6版本的PHP嘛?
Are there plans to support version 5.6 of PHP?

**Comment by heyanlong** [comment]
永远不会支持5.6
![image](https://user-images.githubusercontent.com/3367958/61622891-41cdcb80-aca8-11e9-8162-f32ea63847b5.png)

**Comment by iwzd520** [comment]
看了这个图，我就瞬间明白啦，感谢！


 
---原始邮件---
发件人: "何延龙"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 下午5:44
收件人: "SkyAPM/SkyAPM-php-sdk"<SkyAPM-php-sdk@noreply.github.com>;
抄送: "iwzd520"<iwzd@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [SkyAPM/SkyAPM-php-sdk] skyphpsdk现在支持哪些版本php (#89)



永远不会支持5.6
