### ISSUE TITLE
加入report_client 进程后，nginx报错，有些接口返回正常，个别接口请求返回 502

### ISSUE THREAD

**Issue by sinbad01234** [SkyAPM/SkyAPM-php-sdk#90]
能上传日志了，但是有个问题。nginx报错，有些接口返回正常，个别接口请求返回 502. 不是因为超时，nginx日志如下：
2019/07/20 11:36:23 [error] 7#7: *856 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /place/search HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000"

杀掉report_client进程，接口请求都是正常的。
其中一个返回502的接口是请求elastic search，search索引。用的是官方的es-php sdk。
目前看，有问题的接口，都是涉及到请求第三方的服务。

**Comment by heyanlong** [comment]
只要杀掉report_client 就正常？

**Comment by sinbad01234** [comment]
> 只要杀掉report_client 就正常？
对

**Comment by sinbad01234** [comment]
目前就两个接口这样，一个是请求阿里云oss上传图片的，一个是请求elastic search的搜索。
杀掉report_client进程，接口请求都是正常的。

**Comment by heyanlong** [comment]
你这个场景很负责，理论上report不会影响PHP进程运行

**Comment by sinbad01234** [comment]
> 你这个场景很负责，理论上report不会影响PHP进程运行
应该是程序调用elastic search时，php-fpm进程被杀死了，没有返回。nginx就报错了。

**Comment by bostin** [comment]
php 版本是多少？
我在7.3遇到过502问题。
场景是，A机器，部署local.a.com, local.b.com, local.c.com； B机器，部署local.aa.com, local.bb.com
只要是在同一台机器互相请求，没有问题；一旦跨机器相互请求，就会出现问题。目前我能排查出的就是php7.3对php_url的结构体修改，导致skywalking-php-sdk在获取peer时有问题。

**Comment by sinbad01234** [comment]
> php 版本是多少？
> 我在7.3遇到过502问题。
> 场景是，A机器，部署local.a.com, local.b.com, local.c.com； B机器，部署local.aa.com, local.bb.com
> �只要是在同一台机器互相请求，没有问题；一旦跨机器相互请求，就会出现问题。目前我能排查出的就是php7.3对php_url的结构体修改，导致skywalking-php-sdk在获取peer时有问题。

php:7.2-fpm

**Comment by heyanlong** [comment]
cli模式不启动skywalking收集
可以把部分代码和composer.json 发上来吗？

**Comment by heyanlong** [comment]
求回复

**Comment by sinbad01234** [comment]
> 求回复

就是简单的调用es（"elasticsearch/elasticsearch": "~6.7.0"）。晚上我单独弄一个项目出来。

**Comment by heyanlong** [comment]
好的

**Comment by heyanlong** [comment]
拉取最新master代码，试试，应该修复了

**Comment by sinbad01234** [comment]
好的。我刚弄出一个干净的项目出来。如果需要，我再提供，我先试下最新的代码

**Comment by sinbad01234** [comment]
/opt/SkyAPM-php-sdk-master/skywalking.c:38:10: fatal error: ext/mysqli/php_mysqli_structs.h: No such file or directory
 #include "ext/mysqli/php_mysqli_structs.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:193: skywalking.lo] Error 1

**Comment by sinbad01234** [comment]
> 拉取最新master代码，试试，应该修复了

 编译报错，centos的系统
/opt/SkyAPM-php-sdk-master/skywalking.c:38:10: fatal error: ext/mysqli/php_mysqli_structs.h: No such file or directory
 #include "ext/mysqli/php_mysqli_structs.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:193: skywalking.lo] Error 1

**Comment by heyanlong** [comment]
你没安装mysqli扩展吗？


发自我的 iPhone

**Comment by sinbad01234** [comment]
> 你没安装mysqli扩展吗？ 发自我的 iPhone
> […](#)
> 在 2019年7月26日，19:44，sinbad01234 ***@***.***> 写道： 拉取最新master代码，试试，应该修复了 编译报错，centos的系统 /opt/SkyAPM-php-sdk-master/skywalking.c:38:10: fatal error: ext/mysqli/php_mysqli_structs.h: No such file or directory #include "ext/mysqli/php_mysqli_structs.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:193: skywalking.lo] Error 1 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

安装了扩展了。以前编译没问题。就现在的mater版本有问题。
今天编译报这个错了
/usr/local/include/php/ext/mysqli/php_mysqli_structs.h:63:10: fatal error: my_global.h: No such file or directory
 #include <my_global.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:193: skywalking.lo] Error 1

**Comment by heyanlong** [comment]
不行QQ或者微信聊吧，你这个好复杂，这么多天了

发自我的 iPhone

**Comment by sinbad01234** [comment]
> 不行QQ或者微信聊吧，你这个好复杂，这么多天了 发自我的 iPhone
> […](#)
> 在 2019年7月28日，18:48，sinbad01234 ***@***.***> 写道： 你没安装mysqli扩展吗？ 发自我的 iPhone … 在 2019年7月26日，19:44，sinbad01234 @.***> 写道： 拉取最新master代码，试试，应该修复了 编译报错，centos的系统 /opt/SkyAPM-php-sdk-master/skywalking.c:38:10: fatal error: ext/mysqli/php_mysqli_structs.h: No such file or directory #include "ext/mysqli/php_mysqli_structs.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:193: skywalking.lo] Error 1 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread. 安装了扩展了。以前编译没问题。就现在的mater版本有问题。 今天编译报这个错了 /usr/local/include/php/ext/mysqli/php_mysqli_structs.h:63:10: fatal error: my_global.h: No such file or directory #include <my_global.h> ^~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:193: skywalking.lo] Error 1 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

微信扫一下
![image](https://user-images.githubusercontent.com/48613293/62029207-9c20dc00-b214-11e9-9435-6213ebfe71c9.png)

**Comment by xaviertoo** [comment]
@sinbad01234 请问编译报错问题解决了吗？
我用php 7.1和7.2 docker镜像，也遇到找不到/usr/local/include/php/ext/mysqli/php_mysqli_structs.h:63:10: fatal error: my_global.h: No such file or directory问题。

In file included from /app/SkyAPM-php-sdk/skywalking.c:38:0:
/usr/local/include/php/ext/mysqli/php_mysqli_structs.h:63:23: fatal error: my_global.h: No such file or directory
 #include <my_global.h>
                       ^
compilation terminated.
make: *** [skywalking.lo] Error 1

### Dockerfile
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y git automake bison flex g++ git libtool make pkg-config openssl libssl-dev libcurl4-openssl-dev ruby-ronn zlib1g-dev tzdata default-libmysqlclient-dev libmariadbclient-dev-compat mysql-client
RUN docker-php-ext-install pdo_mysql mysqli
RUN  git clone https://github.com/SkyAPM/SkyAPM-php-sdk.git \
  && cd SkyAPM-php-sdk \
  && phpize \
  && ./configure \
  && make && make install

### php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
grpc
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
oneapm
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Comment by heyanlong** [comment]
正在处理

**Comment by heyanlong** [comment]
retry last master @sinbad01234 @xaviertoo @michaelsembwever

**Comment by DavenAaron** [comment]
我这遇到同样的问题， 有一个接口502 ,   这个接口内部httpclient请求了两个其他服务的接口，我们是跑在kubernetes 1.12 下

**Comment by heyanlong** [comment]
@DavenAaron 你用的什么版本代码，请求的接口是什么，代码可以发一下吗

**Comment by DavenAaron** [comment]
master 当前master分支

**Comment by DavenAaron** [comment]
public function actionInit()
    {
        $code = 0;
        $data = [
            'serverTime' => date('Y-m-d H:i:s', time()),
        ];

        $params = $this->request->get();

        // 校验参数
        $fieldRequired = [
            'appVersion',
            'serialNo',
            'brand',
            'model',
            'shopId',
            'initCode',
        ];
        foreach ($fieldRequired as $v) {
            if (!isset($params[$v]) || empty($params[$v])) {
                return $this->response(1001, ['field' => $v]);
            }
        }
        $params['shopNo'] = strtoupper($params['shopId']); // 变量更名
        unset($params['shopId']);

        // 获取门店信息
        $shopInfo = ApiClient::call('ospApi', 'shop', 'getInfo', ['shopNo' => $params['shopNo']]);
        if ($shopInfo['code'] == 100) {
            // 校验初始化密码
            if (strtoupper($params['initCode']) != $shopInfo['data']['info']['initCode']) {
                return $this->response(1007);
            }
            unset($shopInfo['data']['info']['initCode']);
            $shopInfo['data']['info']['shopId'] = $shopInfo['data']['info']['shopNo'];
            unset($shopInfo['data']['info']['shopNo']);
            $data['shopInfo'] = $shopInfo['data']['info'];

            // 注册设备
            $deviceInfo = ApiClient::call('ssdMisc', 'device', 'registry', $params);

            if ($deviceInfo['code'] == 100) {
                $code = 100;
                $data['deviceInfo'] = (object)$deviceInfo['data'];
            } else {
                $code = $deviceInfo['code'];
                Log::error('注册设备失败');
            }
        } else {
            $code = 1008;
            $data = [];
        }

        return $this->response($code, $data);
    }

**Comment by DavenAaron** [comment]
校验初始化密码 &&  注册设备 这两个接口调用程序日志里边记录正常
