### ISSUE TITLE
master 分支代码在 php7.3下 启动php-fpm报错

### ISSUE THREAD

**Issue by qinlodestar** [SkyAPM/SkyAPM-php-sdk#91]
php-fpm /etc/init.d/php-fpm: line 54: 2236313 Segmentation fault      $php_fpm_BIN --daemonize $php_opts

**Comment by heyanlong** [comment]
Retry last release

**Comment by G-Bruin** [comment]
SkyAPM-php-sdk-3.3.2 最新版本也遇到同样的问题

**Comment by G-Bruin** [comment]
[root@centos6 conf]# /etc/init.d/php-fpm start
Starting php-fpm /etc/init.d/php-fpm: line 53: 12444 段错误               $php_fpm_BIN --daemonize $php_opts
 failed

![image](https://user-images.githubusercontent.com/20853074/84998622-aaf0e400-b182-11ea-8266-de7b02b62cdd.png)

**Comment by heyanlong** [comment]
发一下coredump

**Comment by G-Bruin** [comment]
找不到对应的 dump，不知道具体再什么位置

**Comment by heyanlong** [comment]
找一下吧，这是唯一途径，另外你PHP是zts版本吗？

**Comment by G-Bruin** [comment]
是的 
![image](https://user-images.githubusercontent.com/20853074/85003872-6583e500-b189-11ea-881b-46abe7a619a7.png)

**Comment by G-Bruin** [comment]
换个低版本的会不会有用？

**Comment by heyanlong** [comment]
不支持ZTS，为什么要用ZTS？

**Comment by G-Bruin** [comment]
也就是说要用nts 版本的对吧？

**Comment by G-Bruin** [comment]
可以了多谢大佬指点
