### ISSUE TITLE
出现502报错

### ISSUE THREAD

**Issue by jefry86** [SkyAPM/SkyAPM-php-sdk#93]
php.ini加处skywalking扩展；curl请求外部资源出现502。

配置如下：

[skywalking]
;扩展so
extension=skywalking.so
;是否启用：0 关闭；1 启用 (默认值为0)
skywalking.enable=1
;skywalking的版本：5或者6（默认值为6）
skywalking.version=6
;app_code代码，不要含特殊字符，请使用数字、字母、下换线。(默认为：hello_skywalking)
skywalking.app_code=hello_skywalking
;sock文件路径（默认值为/tmp/sky_agent.sock）
skywalking.sock_path=/tmp/sky_agent.sock

php error.log

[24-Jul-2019 20:56:18] WARNING: [pool www] child 29451 exited on signal 11 (SIGSEGV) after 25.828844 seconds from start
[24-Jul-2019 20:56:18] NOTICE: [pool www] child 29558 started

php 代码：

<?php
$url='http://www.baidu.com';
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 3);
curl_setopt($ch, CURLOPT_URL, $url);
$result = curl_exec($ch);
curl_close($ch);

**Comment by jefry86** [comment]
$url = 'http://www.baidu.com';
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 3);
curl_setopt($ch, CURLOPT_URL, $url);
curl_exec($ch);
curl_close($ch);

不是curl请求的没报502错误

**Comment by heyanlong** [comment]
PHP版本多少？用的什么版本的扩展？master？

**Comment by jefry86** [comment]
@heyanlong 

PHP 7.0.29  

master分支

skywalking version： 5.0.0

skywalking 配置：
;扩展so
extension=skywalking.so
;是否启用：0 关闭；1 启用 (默认值为0)
skywalking.enable=1
;skywalking的版本：5或者6（默认值为6）
skywalking.version=6
;app_code代码，不要含特殊字符，请使用数字、字母、下换线。(默认为：hello_skywalking)
skywalking.app_code=hello_skywalking
;sock文件路径（默认值为/tmp/sky_agent.sock）
skywalking.sock_path=/tmp/sky_agent.sock

**Comment by heyanlong** [comment]
你的master是什么时候clone的？commit id是多少？我本地测试7.0.32不存在任何问题

**Comment by heyanlong** [comment]
我尝试一下7.0.29

**Comment by jefry86** [comment]
commit f791f4182a675f233ea39c80569e37dbf1a8d124
Author: heyanlong <yanlong.hee@gmail.com>
Date:   Wed Jul 24 17:51:45 2019 +0800

**Comment by heyanlong** [comment]
尝试一下最新的吧，另外不建议用master，不稳定，release比较稳定
