### ISSUE TITLE
Do you have plan to support agent.authentication 

### ISSUE THREAD

**Issue by qinlodestar** [SkyAPM/SkyAPM-php-sdk#94]

**Comment by heyanlong** [comment]
What exactly does it mean?

**Comment by qinlodestar** [comment]
If collector is configured agent.authentication，but agent has no authentication  option.
./sky_php_agent_linux_x64 127.0.0.1:11800 /tmp/sky_agent.sock

**Comment by heyanlong** [comment]
Add later

**Comment by ttlovedu** [comment]
skywalking server端版本：7.0 或 5.0
php版本：php7.1
sky_php_agent version：3.2.8
skywalking.so 扩展参数： skywalking.version=5或6  

现在支持 header头中报文，带有 authentication  验证头信息 收集么？
sky_php_agent 在skywalking服务器启动状态下。php的skywalking扩展不能正常工作，get访问方式无法获取到业务接口数据。目前，7.0 和5.0版本的skywalking 都测试过。启用就会影响接口数据get获取。

启动后header头缺少如下部分信息，导致get方式无法获取接口数据。
    ["authorization"]=>
    array(1) {
      [0]=>
      string(25) "a6HEqpDQyZrPL1ZlMBgPU11zL"
    }
    ["content-type"]=>
    array(1) {
      [0]=>
      string(31) "application/json; charset=utf-8"
    }

**Comment by heyanlong** [comment]
会把authorization 删掉？

**Comment by it-liwow** [comment]
sky-php-agent --grpc 192.168.1.29:11800 --socket /var/run/sky-agent.sock
sky-php-agent -v
sky_php_agent version 3.2.8

经过多次测试。步骤如下：（skywalking服务端，sky-php-agent，skywalking.so扩展都正常启动加载）
A,关闭skywalking服务端后，重启php-fpm，可一直get获取到接口数据，接口状态正常，报文header头信息中可获取到authorization信息。
B,重新启动skywalking服务端并正常记录链路追踪信息，接口就无法get获取数据，此时报文header头信息中丢失authorization信息，导致验证失败，无法get获取数据。
C,重启php-fpm,第一次可以正常get到数据(清浏览器确认不是缓存)，第二次之后开始便无法get获取到数据,报文header头信息中丢失authorization信息。

无论是skywalking7.0 （skywalking.version=6）还是5.0 版本（skywalking.version=5） 都会出现同样的情况。

异常情况：
array(3) {
  ["code"]=>
  int(200)
  ["data"]=>
  array(5) {
    ["accept"]=>
    array(1) {
      [0]=>
      string(3) "*/*"
    }
    ["host"]=>
    array(1) {
      [0]=>
      string(30) "dev.test.xxx.com"
    }
    ["user-agent"]=>
    array(1) {
      [0]=>
      string(70) "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
    }
    ["content-length"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
    ["content-type"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
  }
  ["message"]=>
  string(7) "success"
}

正常情况：
array(3) {
  ["code"]=>
  int(200)
  ["data"]=>
  array(6) {
    ["authorization"]=>
    array(1) {
      [0]=>
      string(25) "a6HEqpDQyZrPL1ZlMBgPU11zL"
    }
    ["content-type"]=>
    array(1) {
      [0]=>
      string(31) "application/json; charset=utf-8"
    }
    ["accept"]=>
    array(1) {
      [0]=>
      string(3) "*/*"
    }
    ["host"]=>
    array(1) {
      [0]=>
      string(30) "dev.test.xxx.com"
    }
    ["user-agent"]=>
    array(1) {
      [0]=>
      string(70) "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
    }
    ["content-length"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
  }
  ["message"]=>
  string(7) "success"
}

**Comment by heyanlong** [comment]
使用的什么框架？

**Comment by it-liwow** [comment]
使用的lumen 和 phalcon，目前因 其他项目。暂时未跟进这个问题。还在排查..  节后再继续查这个问题。

**Comment by it-liwow** [comment]
不好意思，问题已解决。 
是研发再提交gitlab代码里。配置文件缺省了协议导致authorization丢失问题。 如：STOCK_URL=www.abc.com     改为：STOCK_URL=http://www.abc.com  则正常 。

**Comment by Veitor** [comment]
Is `agent.authentication` added？ I need it when I use AliYun's TracingAnalysis Product

**Comment by heyanlong** [comment]
No need
