### ISSUE TITLE
make问题

### ISSUE THREAD

**Issue by tianxiaojiang** [SkyAPM/SkyAPM-php-sdk#96]
在老的版本里，编译可以通过，使用没问题。最新的版本，发现编译报错。
我使用时通过的版本号是：1cbabdc742ce43fdacb32759f4108754094139011cbabdc742ce43fdacb32759f410875409413901

编译报错的php版本：7.1.18
报错信息是：
`/home/soft/SkyAPM-php-sdk/skywalking.c: 在函数‘sky_execute_internal’中:
/home/soft/SkyAPM-php-sdk/skywalking.c:415:56: 错误：‘MYSQLND_CONN_DATA’没有名为‘host’的成员
                         char *host = mysql->mysql->data->host;`

**Comment by tristan-tsl** [comment]
+ 1 ,i meet this mistake too

**Comment by tristan-tsl** [comment]
clone the branches of master again
